### ISSUE TITLE
doesn't launch with or without `CAP_SYS_NICE=eip` on NVIDIA

### ISSUE THREAD

**Issue by flippette** [ValveSoftware/gamescope#1000]
Doesn't launch on NVIDIA at all, with or without `CAP_SYS_NICE=eip` set.

With:

```
~ ❯ gamescope -- glxgears
wlserver: [backend/headless/backend.c:68] Creating headless backend
vulkan: physical device 10de:1f06 compute queue doesn't support presenting on our surface, using graphics queue
vulkan: selecting physical device 'NVIDIA GeForce RTX 2060 SUPER': queue family 0 (general queue family 0)
vulkan: physical device supports DRM format modifiers
vulkan: vkCreateDevice failed (VkResult: -3)
Failed to initialize Vulkan
```

Without:

```
~ ❯ gamescope -- glxgears
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
wlserver: [backend/headless/backend.c:68] Creating headless backend
vulkan: physical device 10de:1f06 compute queue doesn't support presenting on our surface, using graphics queue
vulkan: selecting physical device 'NVIDIA GeForce RTX 2060 SUPER': queue family 0 (general queue family 0)
vulkan: physical device supports DRM format modifiers
fish: Job 1, 'gamescope -- glxgears' terminated by signal SIGSEGV (Address boundary error)
```

System Info:
- OS: Arch Linux
- Driver: nvidia-open-dkms 535.113.01-6
- Kernel: 6.5.8-zen1-1-zen

**Comment by sharkautarch** [comment]
Can confirm the bug with nvidia
I tried reverting commit bd722f786f5a74f8282d903bd5eb3d331c4cd920 which was thought to be the commit where this issue started, as discusssed in https://github.com/ValveSoftware/gamescope/issues/948.
It actually seems like reverting just that commit (after fixing the compiler errors reverting it caused) makes gamescope work on nvidia again

Though I do have to run gamescope with `--prefer-vk-device <nvidia-gpu-id>` in order for it to run
You can find the ID of your gpu by running: `MESA_VK_DEVICE_SELECT=list vulkaninfo` (vulkaninfo is in the vulkan-tools package for archlinux, debian and ubuntu)

I am on a hybrid graphics nvidia/intel laptop, but running `nvidia-smi` also confirms that gamescope is running on the nvidia gpu for me. 
On the other hand, now I have the *opposite* problem: when trying to run gamescope on anything *but* my nvidia gpu, it crashes!

Here's a fork I made with the revert:
https://github.com/sharkautarch/gamescope/tree/nvidia-fix
note that the revert is only in the 'nvidia-fix' branch of it
Press the 'Download Zip' button to download from the 'nvidia-fix' branch,
or clone the fork and then do `cd gamescope; git checkout nvidia-fix`
