### ISSUE TITLE
Assert in rendervulkan due to missing exportable flag

### ISSUE THREAD

**Issue by llandwerlin-intel** [ValveSoftware/gamescope#1002]
Gamescope on Intel/Mesa Gfx9 is trying to export a dmabuf from the memory backing an image : https://github.com/ValveSoftware/gamescope/blob/master/src/rendervulkan.cpp#L2424

But it's failing with an assert in the driver because it is not creating the memory as exportable at allocation time : https://github.com/ValveSoftware/gamescope/blob/master/src/rendervulkan.cpp#L2023

There should be a validation error for this.

**Comment by djdeath** [comment]
Closing, this appears to have been fixed in my last testing.

Could be related to https://github.com/ValveSoftware/gamescope/commit/243582c0c7625577a2535c3363ae345de713f323
