### ISSUE TITLE
Colors are wrong when using steam link or capturing the screen using gstreamer and pipewiresrc

### ISSUE THREAD

**Issue by safijari** [ValveSoftware/gamescope#1011]
Ever since https://github.com/ValveSoftware/gamescope/commit/06532b071c0c09b4ecfa4f32335171c71b44a265 the colors are wrong (see picture below) when capturing the screen using gstreamer and pipewiresrc. 

![image](https://github.com/ValveSoftware/gamescope/assets/5191844/5d78d17e-3b77-46e9-a6c9-a275d07c9c15)

Edit: colors are also wrong when using Steam Link

![image](https://github.com/ValveSoftware/gamescope/assets/5191844/7f59b59f-5345-47eb-a2e6-d212dc4f13da)

**Comment by safijari** [comment]
Looks like this happens because CTM is being applied twice. `cs_rgb_to_nv12.comp` is the shader that gets used to make the pipewire stream. It calls sampleLayer from composite.h which is where the `color.rgb = vec4(color.rgb, 1.0f) * u_ctm[offsetLayerIdx];` line was added in the offending commit. The shader also applies the ctm itself after calling `sampleLayer` Making it so that the shader does not apply the CTM (and just does a linear to srgb conversion instead) makes the colors mostly correct but the resulting picture is pretty dark.

![Screenshot Fri Nov 10 10:27:24 AM CST 2023](https://github.com/ValveSoftware/gamescope/assets/5191844/03ca5631-ed83-4229-83fd-2abc549a88c8)

**Comment by Joshua-Ashton** [comment]
Looks like its off by a Gamma 2.2, thanks for finding that.

**Comment by safijari** [comment]
I'm not going to pretend like I know what I'm doing but https://github.com/ValveSoftware/gamescope/compare/master...safijari:gamescope:pipewire_color_issue?expand=1 seems to fix things. In addition to removing the application of the CTM in the rgb to nv12 shader, I'm also changing the colorspace from srgb to linear in rendervulkan.cpp since the shader seems to expect linear and does a conversion to srgb.

Is this right? I feel like there's still something a hair off. The saturation feels too high.

![image](https://github.com/ValveSoftware/gamescope/assets/5191844/2a3d9227-a749-4e29-9aa8-fcc4468628af)

**Comment by safijari** [comment]
Addressed by https://github.com/ValveSoftware/gamescope/commit/add96e3ba8a9ba5aa60adfe6c9b4e654cf6de23e
