### ISSUE TITLE
gamescope treats numlock state as being off upon launch, it will only react when toggling it if gamescope is being focused

### ISSUE THREAD

**Issue by simifor** [ValveSoftware/gamescope#1025]
There are two numlock related issues I've found.

1) When you start gamescope, the program running inside gamescope will behave as if the numlock was off. This happens when the numlock was set to off (which would be correct), but also if it was set to on (which would be incorrect).
2) Gamescope programs won't react to you toggling the numlock unless it is focused. Toggling the numlock key while gamescope is focused will switch the state from on to off, or from off to on depending on the current state, but it won't necessarily match the keyboard's numlock state.

One way to test this issue is to try to load https://hwtests.com/keyboard-test-for-linux from a browser running on gamescope.

I've attached an image that should hopefully make it easier to understand the issue: ![diagram](https://github.com/ValveSoftware/gamescope/assets/70454800/8eb70eba-84b1-4bb1-8285-278713673c0b)

**Comment by kisak-valve** [comment]
Hello @simifor, this issue is already being tracked at #969. Feel free to add your findings to the older issue report.

Closing as a duplicate.
