### ISSUE TITLE
Inverse Tonemapping doesn't quite seem to work in Gamescope.

### ISSUE THREAD

**Issue by isaboll1** [ValveSoftware/gamescope#1034]
When launching gamescope using _--hdr-itm-enable_, there doesn't seem to be any changes made for SDR content being played on HDR screens, with respect to Inverse Tonemapping.

Investigating a bit, the ITM boolean value doesn't seem to be passed in the [process of binding pipelines](https://github.com/ValveSoftware/gamescope/blob/146da86c89a392d61ab562c1ef355c5097086fed/src/rendervulkan.cpp#L3762), unlike how it was when the [feature was first introduced](https://github.com/ValveSoftware/gamescope/commit/7bd30dd6d8fe998806bfd7f4b53af42240a266e9#diff-0ca179f8adb820354aba0b6a063350f9e32689950ead39e8bbeca021fa8ba0e0R3464), despite pipelines [seemingly allowing for the boolean value ](https://github.com/ValveSoftware/gamescope/blob/master/src/rendervulkan.cpp#L1112). Likewise, the [constant id used for ITM in pipelines](https://github.com/ValveSoftware/gamescope/blob/146da86c89a392d61ab562c1ef355c5097086fed/src/rendervulkan.cpp#L1017) seems off compared to [what's expected with regards to descriptor sets ](https://github.com/ValveSoftware/gamescope/blob/146da86c89a392d61ab562c1ef355c5097086fed/src/shaders/descriptor_set.h#L10).

**Comment by kodatarule** [comment]
At least according to my tests, it seems that the option _--hdr-itm-enable_, really doesn't kick in and doesn't change anything on my KDE Plasma 6 it just looks the same as if SDR content is running on HDR which it already does without gamescope.

**Comment by isaboll1** [comment]
I can notice the itm flag working with recent testing. Closing
