### ISSUE TITLE
SSD Swap from LCD to OLED made RPCS 3 Games not work anymore in gamemode

### ISSUE THREAD

**Issue by Ichigo07** [ValveSoftware/gamescope#1039]
Only happens in game mode.

Assertion Failed! Vulkan API call failed with unrecoverable error: Requested extension not available (VK_ERROR_EXTENSION_NOT_PRESENT)
(in file /rpcs3/rpcs3/Emu/RSX/VK/vkutils/instance.hpp:301[:93], in function operator()) (errno=11=Resource temporarily unavailable)
(in file /rpcs3/rpcs3/Emu/RSX/VK/vkutils/shared.cpp:114[:4], in function die_with_error) (errno=11=Resource temporarily unavailable)

**Comment by parkerlreed** [comment]
So what was the error/fix?

**Comment by Ichigo07** [comment]
Did not find one, i reimaged Steam OS on that SSD
