### ISSUE TITLE
[Regression] Gamescope 3.13.17-1+ cursor scaling issue

### ISSUE THREAD

**Issue by Kagukara** [ValveSoftware/gamescope#1054]
The cursor in Guild Wars 2 is tiny compared to previous version. Not sure what else I can say, let me know if more information is needed and how to provide it.

Downgrading to 3.13.11-1 fixed the issue. Unable to check 3.13.16-1 as I get `error: failed retrieving file 'gamescope-3.13.16-1-x86_64.pkg.tar.zst' from archive.archlinux.org : SSL connection timeout` with `downgrade`.

- WM: sway version 1.8.1
- Proton Version: Proton Experimental
- Launch Options: `gamescope -w 3840 -h 1800 -W 3840 -H 1800 -f -F fsr --fsr-sharpness 0 -S auto -- %command%`

gamescope 3.13.17-1:
![screenshot_2023-12-10_14-31-52](https://github.com/ValveSoftware/gamescope/assets/43391109/13038621-d090-4cf8-aead-ddee62d6cb0a)

gamescope 3.13.11-1:
![screenshot_2023-12-10_14-31-32](https://github.com/ValveSoftware/gamescope/assets/43391109/ccfb37f7-39fb-452b-806e-3c6c6418decc)

**Comment by rankynbass** [comment]
I can confirm a similar issue with Final Fantasy XIV when using XIVLauncher or Steam. The cursor is unscaled, and the in-game scaling options *do not* work. Reverting to 3.13.16 or earlier fixes the cursor issue.

- CachyOS with KDE wayland session (Arch-based)
- Wine-GE 8-24 (although it's the same with all versions of wine and proton I tested)
- Launch options: `gamescope --force-grab-cursor --expose-wayland -f -H 2160 -h 1800 -F fsr -r 120 -- %command%`

gamescope 3.13.17-1
![FFXIV_small_cursor](https://github.com/ValveSoftware/gamescope/assets/109918887/6b79da2b-dfcc-434a-801b-f949b388d38d)

gamescope 3.13.16-1
![FFXIV_large_cursor](https://github.com/ValveSoftware/gamescope/assets/109918887/41759226-67fa-4a8c-b288-3542b118b2c9)

**Comment by zeparu** [comment]
can confirm the same issue here as well, especially on ffxiv, the hardware-ffxiv-cursor is affected, the hardware-os-cursor and software cursors are not affected by this.

**Comment by Kagukara** [comment]
This is still happening in Gamescope Version: 3.13.19-1.

**Comment by Kagukara** [comment]
Can confirm using gamescope-git on the aur which installed 3.13.19.r24.g1a008fa-1 has the fix and works. Using `gamescope -w 3840 -h 1800 -W 3840 -H 1800 -f -r 120 -- %command%`

`gamescope-3.13.19-1`
![capture_2024-01-07_01-45-17](https://github.com/ValveSoftware/gamescope/assets/43391109/897e68b1-1061-4a19-978a-048045da0ff7)

`gamescope-git-3.13.19.r25.g58509f0-1`
![capture_2024-01-07_01-45-28](https://github.com/ValveSoftware/gamescope/assets/43391109/e966efb8-e8fd-4daf-ba1a-070216c60267)

No `gamescope` (Cursor just have more white gradient then when in `gamescope`)
![capture_2024-01-07_01-45-36](https://github.com/ValveSoftware/gamescope/assets/43391109/ea9d07f7-b7fd-4a6e-a018-87f1c0228f46)
