### ISSUE TITLE
Is there possible to custom X display id?

### ISSUE THREAD

**Issue by l12436** [ValveSoftware/gamescope#1077]
Is there any possible to add ability to choose different display id by argument. like -d :10, and gamescope will open X display on that id.
I have using X tool to send text inside gamescope, but without custom display id. I always need to try which display id is mine.

**Comment by Joshua-Ashton** [comment]
This isn't possible unfortunately -- you can use something like `gamescope-type` though.

https://github.com/Joshua-Ashton/gamescope-type

**Comment by l12436** [comment]
OK, Thanks for your information
