### ISSUE TITLE
readme build instructions lacks a list of dependancies

### ISSUE THREAD

**Issue by RGD2** [ValveSoftware/gamescope#1079]
On a fresh installation of Debian sid/trixie, 
following the instructions causes the `meson build/` to repeatedly fail due to lacking dependencies with a message of `(tried pkgconfig and system)`.  Each failure required manually finding the required package to install.

Something like the apt get line following allowed a build, but without any backends.

What's missing for those? 

Also, is it too much to ask that the following line appear *somewhere* in the readme, preferably under 'building on debian' ?
```
sudo apt install libwayland-dev libvulkan-dev wayland-protocols libx11-xcb-dev libglm-dev libxdamage-dev libxcomposite-dev libxcursor-dev libxxf86vm-dev libxtst-dev libxres-dev libxmu-dev libdrm-dev libxkbcommon-dev libsdl2-dev libavif-dev libpixman-1-dev libseat-dev libinput-dev libxcb-composite0-dev libxcb-ewmh-dev libxcb-icccm4-dev libxcb-res0-dev libcap-dev libstb-dev libdisplay-info-dev edid-decode libbenchmark-dev libxcb-dri3-dev libxcb-screensaver0 libxcb-util-dev libxcb-randr0-dev libxcb-render-util0-dev libxcb-xinput-dev ibxcb-sync-dev libxcb-present-dev
```

**Comment by Joshua-Ashton** [comment]
This list can change pretty frequently, it'd be nice if there was a way for something to look at the meson and give build deps automatically or something.

That being said, I am happy to have the list of dependencies in the readme if you want to make an MR.

**Comment by eli-schwartz** [comment]
```
/tmp/gamescope $ meson introspect meson.build --scan-dependencies | jq '.[].name' | sort
"benchmark"
"epoll-shim"
"glm"
"glm"
"hwdata"
"libavif"
"libcap"
"libdisplay-info"
"libdrm"
"libliftoff"
"libpipewire-0.3"
"openvr"
"SDL2"
"stb"
"threads"
"vkroots"
"vulkan"
"wayland-client"
"wayland-client"
"wayland-protocols"
"wayland-protocols"
"wayland-scanner"
"wayland-server"
"wlroots"
"x11"
"x11-xcb"
"xcb"
"xcomposite"
"xcursor"
"xdamage"
"xext"
"xfixes"
"xi"
"xkbcommon"
"xmu"
"xrender"
"xres"
"xtst"
"xxf86vm"
```

This is a list of dependency names. You'll by and large need, for each of these, any one of:
- a {name}.pc file
- a subprojects/{name}/ directory
- a subprojects/{name}.wrap file

Not all will be needed. Each name will have a "required" and "conditional" tag as well, detailing whether the dependency is mandatory (via the required: kwarg, or via only being looked up inside an if/else block).

The .pc files can be found on Debian with `apt-file search {name}.pc` (may require installing apt-file first, sorry).

**Comment by Joshua-Ashton** [comment]
Thanks, I assume we can use pacman -Fy for getting arch package for the PC?

**Comment by linuxazo** [comment]
This is the official and up-to-date list of dependencies for Gamescope Debian packaging:
`https://salsa.debian.org/sapphire/gamescope/-/blob/debian/latest/debian/control?ref_type=heads`

You can always do `apt build-dep gamescope` to install the dependencies from the above link.
Please note, it does need Debian specific patches in order to build successfully (e.g. reshade-shaders submodule at the moment, and patches to make the meson build system use system installed dependencies, in lieu of git submodules).

**Comment by RGD2** [comment]
Thanks all: Good information on this ticket, should anyone else stumble on it.

I'm not going to fix this, but this ticket itself should be found by anyone troubled by dep, so I'll mark it so for now.
