### ISSUE TITLE
[FR] Supersample when downscaling

### ISSUE THREAD

**Issue by Firepal** [ValveSoftware/gamescope#1089]
Would be neat to have supersampled downscaling when the internal resolution is bigger than the output resolution. 
Right now it seems to do the classic linear sampling without anything special to avoid aliasing.

**Comment by kisak-valve** [comment]
Hello @Firepal, this issue is already being tracked at #692. Closing in favor of the older issue report.

**Comment by Firepal** [comment]
Excuse me! I tried to look for it but probably didn't use the right keywords.
