### ISSUE TITLE
No video output

### ISSUE THREAD

**Issue by Akeem29** [ValveSoftware/gamescope#1095]
When run under x11 (I tried GNOME on Xorg and Openbox), trying to run gamescope from Steam or from terminal spawns a window that is filled with what appears to be a screenshot of part of the screen that were behind this window when it appeared (this may be a part of wallpaper or parts of windows), sound of the launched game however does get played and it seems like window could stay in this state indefinitely with no change. When run under Wayland (I tried GNOME on Wayland and Weston), any attempt to run gamescope results in segmentation fault. I attached two text files with terminal output of command "gamescope -W 1920 -H 1080 -r 60 -- supertuxkart"

CPU: Intel Core i5 2400
GPU: NVIDIA GeForce GTX 1650
NVIDIA driver version: 545.29.06
Distribution: Fedora 39
Linux kernel version: 6.6.9-200.fc39.x86_64

[Gamescope X11 output.txt](https://github.com/ValveSoftware/gamescope/files/13904114/Gamescope.X11.output.txt)
[Gamescope wayland output.txt](https://github.com/ValveSoftware/gamescope/files/13904117/Gamescope.wayland.output.txt)

**Comment by Akeem29** [comment]
When run with --expose-wayland under wayland, the result is the same. Here's an example in GNOME on Wayland:
`
$ gamescope --expose-wayland -W 1920 -H 1080 -r 60 -- supertuxkart
vblank: Using timerfd.
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
wlserver: [backend/headless/backend.c:67] Creating headless backend

(gamescope:19994): Gtk-WARNING **: 20:06:14.672: Failed to parse /home/akeem29/.config/gtk-3.0/settings.ini: Key file does not have group ?Settings?
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
vulkan: physical device 10de:1f82 compute queue doesn't support presenting on our surface, using graphics queue
vulkan: selecting physical device 'NVIDIA GeForce GTX 1650': queue family 0 (general queue family 0)
vulkan: physical device supports DRM format modifiers
Segmentation fault (core dumped)

`

**Comment by november781** [comment]
+1
https://paste.gloriouseggroll.tv/?dab1a0fd40a2641b#3bfNrvaDDPU2Jo4jarg2kEba4rYg3KnWJrYswFXkkj8P

Also loaded up SuperTuxKart. Didn't get a seg fault using --expose-wayland tho. Just the same window. In my case it was black and not transparent. 

gamescope will not shut down under this bug on my machine and I have to sigkill it to close the process

[neofetch.txt](https://github.com/ValveSoftware/gamescope/files/13945507/neofetch.txt)

**Comment by dgacek** [comment]
I encountered the same problem when trying to launch Baldur's Gate in a Wine virtual desktop.
[gamescope x11 output.txt](https://github.com/ValveSoftware/gamescope/files/14151360/gamescope.x11.output.txt)
[gamescope x11 output 2.txt](https://github.com/ValveSoftware/gamescope/files/14151361/gamescope.x11.output.2.txt)

In the 2nd attempt I ran the game directly (without a launcher) and it played what I think was the first 1 sec of the sound from the logo video in a loop.

OS: Arch Linux x64
Kernel: 6.7.3-arch1-1
DE: Plasma 5.27.10
WM: kwin
Platform: X11
CPU: Intel Core i9 10850k
GPU: NVIDIA GeForce RTX 3080 10GB LHR

**Comment by Tatsh** [comment]
Getting a black screen with music playing of the loading screen with The Sims (and it works fine without Gamescope). Using HEAD:

```shell
~/dev/gamescope/build/src/gamescope --force-grab-cursor -F nis --sharpness 15  -- wine Sims.exe -r1024x768 -skip_intro
```

OS: Gentoo Linux x64
Kernel: 6.9.5 PREEMPT_DYNAMIC TKG
DE: Plasma 6.0.90
Platform: Wayland
CPU: Intel(R) Core(TM) i9-11900K
GPU: GeForce RTX 3080 Ti
GPU Drivers: nvidia 555.52.04

**Comment by Akeem29** [comment]
Update on this issue - for me it's gone. I don't know for what reason though because apart from updates of Gamescope, NVIDIA drivers, my disribution and even my hardware got updated since the publishing of this issue. My current system is:
OS: Fedora Linux 40
Kernel: Linux 6.10.6-200.fc40.x86_64
DE: GNOME 46
Platform: X11
CPU: Intel(R) Core(TM) i5-12400
GPU: NVIDIA GeForce GTX 1650
GPU Drivers: NVIDIA 555.58.02
