### ISSUE TITLE
GPU crash on Tekken 8 after ~15 minutes of game session (Possibly happens in all UE5 games)

### ISSUE THREAD

**Issue by RiQuY** [ValveSoftware/gamescope#1109]
Description
---

The GPU crashes showing artifacts on screen and freezing the SO after  ~15 minutes of game session in Tekken 8, think this also happens on all UE5 games. The only option to recover from this crash is changing the TTY and rebooting or shutting down the PC from the physical button.

System info
---
OS: openSUSE Tumbleweed x86_64 
Kernel: 6.6.11-1-default 
Resolution: 2560x1440 
DE: Plasma 5.27.10 
WM: kwin 
CPU: AMD Ryzen 7 1700X (16) @ 3.400GHz 
GPU: AMD ATI Radeon RX 5600 OEM/5600 XT / 5700/5700 XT 
Memory: 5330MiB / 32016MiB 

Relevant package versions
---
gamescope: 3.13.19-1.1
gamemode: 1.8.1-1.1 (And all related lbraries, gamemoded, libgamemode0, etc)
Mesa: 23.2.1-1699.364.pm.3 (And all related lbraries, Mesa-galium, Mesa-libGL, Mesa-libEGL, etc)
steam: 1.0.0.78-2.3

Steam info
---
Game: TEKKEN 8 Demo
Proton Experimental
Parameters: gamemoderun gamescope -W 2560 -H 1440 -r 60 -f -- %command%

System logs
---

`coredumpctl info /usr/bin/gamescope`
<details>
  <summary>click to collapse</summary>
<pre>
<code>
           PID: 13062 (gamescope-wl)
           UID: 1000 (ricardo)
           GID: 1000 (ricardo)
        Signal: 6 (ABRT)
     Timestamp: Mon 2024-01-22 22:31:34 CET (12min ago)
  Command Line: gamescope -W 2560 -H 1440 -r 60 -f -- /home/ricardo/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=2524440 -- /home/ricardo/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- /media/Almacen/Juegos/Steam/steamapps/common/SteamLinuxRuntime_sniper/_v2-entry-point --verb=waitforexitandrun -- $'/media/Almacen/Juegos/Steam/steamapps/common/Proton - Experimental/proton' waitforexitandrun $'/media/Almacen/Juegos/Steam/steamapps/common/TEKKEN 8 Demo/TEKKEN 8 Demo.exe'
    Executable: /usr/bin/gamescope
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-steam-36a34ca6ee364de7943c77267d5d60e8.scope
          Unit: user@1000.service
     User Unit: app-steam-36a34ca6ee364de7943c77267d5d60e8.scope
         Slice: user-1000.slice
     Owner UID: 1000 (ricardo)
       Boot ID: e5dabc1178e747fd8b46cea88f09c586
    Machine ID: 7705050f974844688d71b678d48a076b
      Hostname: localhost.localdomain
       Storage: /var/lib/systemd/coredump/core.gamescope-wl.1000.e5dabc1178e747fd8b46cea88f09c586.13062.1705959094000000.zst (present)
  Size on Disk: 17.8M
       Message: Process 13062 (gamescope-wl) of user 1000 dumped core.
                
                Stack trace of thread 13097:
                #0  0x00007fa45aa91dec __pthread_kill_implementation (libc.so.6 + 0x91dec)
                #1  0x00007fa45aa3f0c6 raise (libc.so.6 + 0x3f0c6)
                #2  0x00007fa45aa268d7 abort (libc.so.6 + 0x268d7)
                #3  0x00007fa45aa267eb __assert_fail_base.cold (libc.so.6 + 0x267eb)
                #4  0x00007fa45aa37016 __assert_fail (libc.so.6 + 0x37016)
                #5  0x000055b6a4f8824e n/a (gamescope + 0x8324e)
                #6  0x000055b6a505630a n/a (gamescope + 0x15130a)
                #7  0x000055b6a504b752 n/a (gamescope + 0x146752)
                #8  0x000055b6a4f64969 n/a (gamescope + 0x5f969)
                #9  0x000055b6a4f7b2c2 n/a (gamescope + 0x762c2)
                #10 0x000055b6a4f7bdf9 n/a (gamescope + 0x76df9)
                #11 0x00007fa45aee89f3 n/a (libstdc++.so.6 + 0xe89f3)
                #12 0x00007fa45aa8ff44 start_thread (libc.so.6 + 0x8ff44)
                #13 0x00007fa45ab184ec __clone3 (libc.so.6 + 0x1184ec)
                
                Stack trace of thread 13074:
                #0  0x00007fa45ab18966 epoll_wait (libc.so.6 + 0x118966)
                #1  0x000055b6a504d382 n/a (gamescope + 0x148382)
                #2  0x000055b6a4f7644c n/a (gamescope + 0x7144c)
                #3  0x00007fa45aee89f3 n/a (libstdc++.so.6 + 0xe89f3)
                #4  0x00007fa45aa8ff44 start_thread (libc.so.6 + 0x8ff44)
                #5  0x00007fa45ab184ec __clone3 (libc.so.6 + 0x1184ec)
                
                Stack trace of thread 13062:
                #0  0x00007fa45ab09d9f __poll (libc.so.6 + 0x109d9f)
                #1  0x000055b6a4f7fc36 n/a (gamescope + 0x7ac36)
                #2  0x000055b6a4f2b6d5 n/a (gamescope + 0x266d5)
                #3  0x00007fa45aa281b0 __libc_start_call_main (libc.so.6 + 0x281b0)
                #4  0x00007fa45aa28279 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x28279)
                #5  0x000055b6a4f4d7f5 n/a (gamescope + 0x487f5)
                
                Stack trace of thread 13076:
                #0  0x00007fa45aa8c4ee __futex_abstimed_wait_common (libc.so.6 + 0x8c4ee)
                #1  0x00007fa45aa8f230 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x8f230)
                #2  0x00007fa455e1bc2b n/a (libvulkan_radeon.so + 0x21bc2b)
                #3  0x00007fa455e3da17 n/a (libvulkan_radeon.so + 0x23da17)
                #4  0x00007fa45aa8ff44 start_thread (libc.so.6 + 0x8ff44)
                #5  0x00007fa45ab184ec __clone3 (libc.so.6 + 0x1184ec)
                
                Stack trace of thread 13075:
                #0  0x00007fa45ab09d9f __poll (libc.so.6 + 0x109d9f)
                #1  0x00007fa45b546d12 n/a (libSDL2-2.0.so.0 + 0x100d12)
                #2  0x00007fa45b495a28 n/a (libSDL2-2.0.so.0 + 0x4fa28)
                #3  0x000055b6a4f83048 n/a (gamescope + 0x7e048)
                #4  0x00007fa45aee89f3 n/a (libstdc++.so.6 + 0xe89f3)
                #5  0x00007fa45aa8ff44 start_thread (libc.so.6 + 0x8ff44)
                #6  0x00007fa45ab184ec __clone3 (libc.so.6 + 0x1184ec)
                
                Stack trace of thread 13079:
                #0  0x00007fa45ab161dd syscall (libc.so.6 + 0x1161dd)
                #1  0x000055b6a4f8429a n/a (gamescope + 0x7f29a)
                #2  0x000055b6a4f8c406 n/a (gamescope + 0x87406)
                #3  0x00007fa45aee89f3 n/a (libstdc++.so.6 + 0xe89f3)
                #4  0x00007fa45aa8ff44 start_thread (libc.so.6 + 0x8ff44)
                #5  0x00007fa45ab184ec __clone3 (libc.so.6 + 0x1184ec)
                
                Stack trace of thread 13095:
                #0  0x00007fa45ab18966 epoll_wait (libc.so.6 + 0x118966)
                #1  0x00007fa4574c5e64 n/a (libspa-support.so + 0x15e64)
                #2  0x00007fa4574b86fd n/a (libspa-support.so + 0x86fd)
                #3  0x00007fa45b1bdd54 n/a (libpipewire-0.3.so.0 + 0x47d54)
                #4  0x00007fa45aa8ff44 start_thread (libc.so.6 + 0x8ff44)
                #5  0x00007fa45ab184ec __clone3 (libc.so.6 + 0x1184ec)
                
                Stack trace of thread 13077:
                #0  0x00007fa45aa8c4ee __futex_abstimed_wait_common (libc.so.6 + 0x8c4ee)
                #1  0x00007fa45aa8f230 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x8f230)
                #2  0x00007fa4583e867c n/a (/home/ricardo/.local/share/Steam/ubuntu12_64/libVkLayer_steam_fossilize.so + 0x7e67c)
                ELF object binary architecture: AMD x86-64
</code>
</pre>
</details>

`journalctl -e --no-pager -b -1`
<details>
  <summary>click to collapse</summary>
<pre>
<code>
ene 22 22:31:35 localhost.localdomain kwin_wayland[2218]: kwin_scene_opengl: Waiting for glGetGraphicsResetStatus to return GL_NO_ERROR timed out!
ene 22 22:31:35 localhost.localdomain kwin_wayland[2218]: OpenGL vendor string:                   AMD
ene 22 22:31:35 localhost.localdomain kwin_wayland[2218]: OpenGL renderer string:                 AMD Radeon RX 5700 XT (navi10, LLVM 17.0.6, DRM 3.54, 6.6.11-1-default)
ene 22 22:31:35 localhost.localdomain kwin_wayland[2218]: OpenGL version string:                  4.6 (Core Profile) Mesa 23.2.1
ene 22 22:31:35 localhost.localdomain kwin_wayland[2218]: OpenGL shading language version string: 4.60
ene 22 22:31:35 localhost.localdomain kwin_wayland[2218]: Driver:                                 Unknown
ene 22 22:31:35 localhost.localdomain kwin_wayland[2218]: GPU class:                              Unknown
ene 22 22:31:35 localhost.localdomain kwin_wayland[2218]: OpenGL version:                         4.6
ene 22 22:31:35 localhost.localdomain kwin_wayland[2218]: GLSL version:                           4.60
ene 22 22:31:35 localhost.localdomain kwin_wayland[2218]: Mesa version:                           23.2.1
ene 22 22:31:35 localhost.localdomain kwin_wayland[2218]: Linux kernel version:                   6.6.11
ene 22 22:31:35 localhost.localdomain kwin_wayland[2218]: Requires strict binding:                no
ene 22 22:31:35 localhost.localdomain kwin_wayland[2218]: GLSL shaders:                           yes
ene 22 22:31:35 localhost.localdomain kwin_wayland[2218]: Texture NPOT support:                   yes
ene 22 22:31:35 localhost.localdomain kwin_wayland[2218]: Virtual Machine:                        no
ene 22 22:31:35 localhost.localdomain kwin_wayland[2218]: BlurConfig::instance called after the first use - ignoring
ene 22 22:31:35 localhost.localdomain kwin_wayland[2218]: ZoomConfig::instance called after the first use - ignoring
ene 22 22:31:35 localhost.localdomain kwin_wayland[2218]: WindowViewConfig::instance called after the first use - ignoring
ene 22 22:31:35 localhost.localdomain kwin_wayland[2218]: SlidingPopupsConfig::instance called after the first use - ignoring
ene 22 22:31:35 localhost.localdomain kwin_wayland[2218]: SlideConfig::instance called after the first use - ignoring
ene 22 22:31:35 localhost.localdomain kwin_wayland[2218]: OverviewConfig::instance called after the first use - ignoring
ene 22 22:31:35 localhost.localdomain kwin_wayland[2218]: KscreenConfig::instance called after the first use - ignoring
ene 22 22:31:35 localhost.localdomain kwin_wayland[2218]: DesktopGridConfig::instance called after the first use - ignoring
ene 22 22:31:35 localhost.localdomain kwin_wayland_wrapper[2218]: amdgpu: The CS has been rejected (-125). Recreate the context.
ene 22 22:31:36 localhost.localdomain kwin_wayland_wrapper[2218]: amdgpu: The CS has been rejected (-125). Recreate the context.
ene 22 22:31:36 localhost.localdomain kwin_wayland_wrapper[2218]: amdgpu: The CS has been rejected (-125). Recreate the context.
ene 22 22:31:36 localhost.localdomain plasmashell[2390]: QSocketNotifier: Socket notifiers cannot be enabled or disabled from another thread
ene 22 22:31:36 localhost.localdomain plasmashell[2390]: QtDBus: cannot relay signals from parent QObject(0x55826ac79590 "") unless they are emitted in the object's thread QThread(0x55826a04f6a0 ""). Current thread is QThread(0x55826cdb3b00 "").
ene 22 22:31:36 localhost.localdomain kwin_wayland_wrapper[2218]: amdgpu: The CS has been rejected (-125). Recreate the context.
ene 22 22:31:36 localhost.localdomain kwin_wayland_wrapper[2218]: amdgpu: The CS has been rejected (-125). Recreate the context.
ene 22 22:31:36 localhost.localdomain kwin_wayland_wrapper[2218]: amdgpu: The CS has been rejected (-125). Recreate the context.
ene 22 22:31:36 localhost.localdomain kwin_wayland_wrapper[2218]: amdgpu: The CS has been rejected (-125). Recreate the context.
ene 22 22:31:36 localhost.localdomain kwin_wayland_wrapper[2218]: amdgpu: The CS has been rejected (-125). Recreate the context.
ene 22 22:31:36 localhost.localdomain kwin_wayland[2218]: kwin_scene_opengl: A graphics reset attributable to the current GL context occurred.
ene 22 22:31:36 localhost.localdomain systemd-coredump[14673]: [🡕] Process 13062 (gamescope-wl) of user 1000 dumped core.
                                                               
                                                               Stack trace of thread 13097:
                                                               #0  0x00007fa45aa91dec __pthread_kill_implementation (libc.so.6 + 0x91dec)
                                                               #1  0x00007fa45aa3f0c6 raise (libc.so.6 + 0x3f0c6)
                                                               #2  0x00007fa45aa268d7 abort (libc.so.6 + 0x268d7)
                                                               #3  0x00007fa45aa267eb __assert_fail_base.cold (libc.so.6 + 0x267eb)
                                                               #4  0x00007fa45aa37016 __assert_fail (libc.so.6 + 0x37016)
                                                               #5  0x000055b6a4f8824e n/a (gamescope + 0x8324e)
                                                               #6  0x000055b6a505630a n/a (gamescope + 0x15130a)
                                                               #7  0x000055b6a504b752 n/a (gamescope + 0x146752)
                                                               #8  0x000055b6a4f64969 n/a (gamescope + 0x5f969)
                                                               #9  0x000055b6a4f7b2c2 n/a (gamescope + 0x762c2)
                                                               #10 0x000055b6a4f7bdf9 n/a (gamescope + 0x76df9)
                                                               #11 0x00007fa45aee89f3 n/a (libstdc++.so.6 + 0xe89f3)
                                                               #12 0x00007fa45aa8ff44 start_thread (libc.so.6 + 0x8ff44)
                                                               #13 0x00007fa45ab184ec __clone3 (libc.so.6 + 0x1184ec)
                                                               
                                                               Stack trace of thread 13074:
                                                               #0  0x00007fa45ab18966 epoll_wait (libc.so.6 + 0x118966)
                                                               #1  0x000055b6a504d382 n/a (gamescope + 0x148382)
                                                               #2  0x000055b6a4f7644c n/a (gamescope + 0x7144c)
                                                               #3  0x00007fa45aee89f3 n/a (libstdc++.so.6 + 0xe89f3)
                                                               #4  0x00007fa45aa8ff44 start_thread (libc.so.6 + 0x8ff44)
                                                               #5  0x00007fa45ab184ec __clone3 (libc.so.6 + 0x1184ec)
                                                               
                                                               Stack trace of thread 13062:
                                                               #0  0x00007fa45ab09d9f __poll (libc.so.6 + 0x109d9f)
                                                               #1  0x000055b6a4f7fc36 n/a (gamescope + 0x7ac36)
                                                               #2  0x000055b6a4f2b6d5 n/a (gamescope + 0x266d5)
                                                               #3  0x00007fa45aa281b0 __libc_start_call_main (libc.so.6 + 0x281b0)
                                                               #4  0x00007fa45aa28279 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x28279)
                                                               #5  0x000055b6a4f4d7f5 n/a (gamescope + 0x487f5)
                                                               
                                                               Stack trace of thread 13076:
                                                               #0  0x00007fa45aa8c4ee __futex_abstimed_wait_common (libc.so.6 + 0x8c4ee)
                                                               #1  0x00007fa45aa8f230 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x8f230)
                                                               #2  0x00007fa455e1bc2b n/a (libvulkan_radeon.so + 0x21bc2b)
                                                               #3  0x00007fa455e3da17 n/a (libvulkan_radeon.so + 0x23da17)
                                                               #4  0x00007fa45aa8ff44 start_thread (libc.so.6 + 0x8ff44)
                                                               #5  0x00007fa45ab184ec __clone3 (libc.so.6 + 0x1184ec)
                                                               
                                                               Stack trace of thread 13075:
                                                               #0  0x00007fa45ab09d9f __poll (libc.so.6 + 0x109d9f)
                                                               #1  0x00007fa45b546d12 n/a (libSDL2-2.0.so.0 + 0x100d12)
                                                               #2  0x00007fa45b495a28 n/a (libSDL2-2.0.so.0 + 0x4fa28)
                                                               #3  0x000055b6a4f83048 n/a (gamescope + 0x7e048)
                                                               #4  0x00007fa45aee89f3 n/a (libstdc++.so.6 + 0xe89f3)
                                                               #5  0x00007fa45aa8ff44 start_thread (libc.so.6 + 0x8ff44)
                                                               #6  0x00007fa45ab184ec __clone3 (libc.so.6 + 0x1184ec)
                                                               
                                                               Stack trace of thread 13079:
                                                               #0  0x00007fa45ab161dd syscall (libc.so.6 + 0x1161dd)
                                                               #1  0x000055b6a4f8429a n/a (gamescope + 0x7f29a)
                                                               #2  0x000055b6a4f8c406 n/a (gamescope + 0x87406)
                                                               #3  0x00007fa45aee89f3 n/a (libstdc++.so.6 + 0xe89f3)
                                                               #4  0x00007fa45aa8ff44 start_thread (libc.so.6 + 0x8ff44)
                                                               #5  0x00007fa45ab184ec __clone3 (libc.so.6 + 0x1184ec)
                                                               
                                                               Stack trace of thread 13095:
                                                               #0  0x00007fa45ab18966 epoll_wait (libc.so.6 + 0x118966)
                                                               #1  0x00007fa4574c5e64 n/a (libspa-support.so + 0x15e64)
                                                               #2  0x00007fa4574b86fd n/a (libspa-support.so + 0x86fd)
                                                               #3  0x00007fa45b1bdd54 n/a (libpipewire-0.3.so.0 + 0x47d54)
                                                               #4  0x00007fa45aa8ff44 start_thread (libc.so.6 + 0x8ff44)
                                                               #5  0x00007fa45ab184ec __clone3 (libc.so.6 + 0x1184ec)
                                                               
                                                               Stack trace of thread 13077:
                                                               #0  0x00007fa45aa8c4ee __futex_abstimed_wait_common (libc.so.6 + 0x8c4ee)
                                                               #1  0x00007fa45aa8f230 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x8f230)
                                                               #2  0x00007fa4583e867c n/a (/home/ricardo/.local/share/Steam/ubuntu12_64/libVkLayer_steam_fossilize.so + 0x7e67c)
                                                               ELF object binary architecture: AMD x86-64
ene 22 22:31:36 localhost.localdomain plasmashell[13082]: (EE) failed to read Wayland events: Broken pipe
ene 22 22:31:36 localhost.localdomain plasmashell[13199]: X connection to :2 broken (explicit kill or server shutdown).
ene 22 22:31:36 localhost.localdomain plasmashell[13266]: X connection to :2 broken (explicit kill or server shutdown).
ene 22 22:31:36 localhost.localdomain plasmashell[13248]: X connection to :2 broken (explicit kill or server shutdown).
ene 22 22:31:36 localhost.localdomain plasmashell[13248]: X connection to :2 broken (explicit kill or server shutdown).
ene 22 22:31:36 localhost.localdomain plasmashell[13248]: X connection to :2 broken (explicit kill or server shutdown).
ene 22 22:31:36 localhost.localdomain plasmashell[13285]: XIO:  fatal IO error 110 (Connection timed out) on X server ":2"
ene 22 22:31:36 localhost.localdomain plasmashell[13285]:       after 1331 requests (1331 known processed) with 0 events remaining.
ene 22 22:31:36 localhost.localdomain systemd[2162]: Started Launch DrKonqi for a systemd-coredump crash (PID 14696/UID 0).
ene 22 22:31:36 localhost.localdomain drkonqi-coredump-launcher[14756]: Unable to find file for pid 13062 expected at "kcrash-metadata/13062.ini"
ene 22 22:31:36 localhost.localdomain drkonqi-coredump-launcher[14756]: QFile::remove: Empty or null file name
ene 22 22:31:36 localhost.localdomain drkonqi-coredump-launcher[14756]: Nothing handled the dump :O
ene 22 22:31:37 localhost.localdomain gamemoded[12492]: ERROR: Could not inspect tasks for client [13062]! Skipping ioprio optimisation.
</code>
</pre>
</details>

`DEBUGINFOD_URLS="https://debuginfod.opensuse.org/" sudo -E coredumpctl gdb /usr/bin/gamescope`
<details>
  <summary>click to collapse</summary>
<pre>
<code>
           PID: 13062 (gamescope-wl)
           UID: 1000 (ricardo)
           GID: 1000 (ricardo)
        Signal: 6 (ABRT)
     Timestamp: Mon 2024-01-22 22:31:34 CET (22min ago)
  Command Line: gamescope -W 2560 -H 1440 -r 60 -f -- /home/ricardo/.local/share/Steam/ubuntu12_32/reaper SteamLaunch AppId=2524440 -- /home/ricardo/.local/share/Steam/ubuntu12_32/steam-launch-wrapper -- /media/Almacen/Juegos/Steam/steamapps/common/SteamLinuxRuntime_sniper/_v2-entry-point --verb=waitforexitandrun -- $'/media/Almacen/Juegos/Steam/steamapps/common/Proton - Experimental/proton' waitforexitandrun $'/media/Almacen/Juegos/Steam/steamapps/common/TEKKEN 8 Demo/TEKKEN 8 Demo.exe'
    Executable: /usr/bin/gamescope
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-steam-36a34ca6ee364de7943c77267d5d60e8.scope
          Unit: user@1000.service
     User Unit: app-steam-36a34ca6ee364de7943c77267d5d60e8.scope
         Slice: user-1000.slice
     Owner UID: 1000 (ricardo)
       Boot ID: e5dabc1178e747fd8b46cea88f09c586
    Machine ID: 7705050f974844688d71b678d48a076b
      Hostname: localhost.localdomain
       Storage: /var/lib/systemd/coredump/core.gamescope-wl.1000.e5dabc1178e747fd8b46cea88f09c586.13062.1705959094000000.zst (present)
  Size on Disk: 17.8M
       Message: Process 13062 (gamescope-wl) of user 1000 dumped core.
                
                Stack trace of thread 13097:
                #0  0x00007fa45aa91dec __pthread_kill_implementation (libc.so.6 + 0x91dec)
                #1  0x00007fa45aa3f0c6 raise (libc.so.6 + 0x3f0c6)
                #2  0x00007fa45aa268d7 abort (libc.so.6 + 0x268d7)
                #3  0x00007fa45aa267eb __assert_fail_base.cold (libc.so.6 + 0x267eb)
                #4  0x00007fa45aa37016 __assert_fail (libc.so.6 + 0x37016)
                #5  0x000055b6a4f8824e n/a (gamescope + 0x8324e)
                #6  0x000055b6a505630a n/a (gamescope + 0x15130a)
                #7  0x000055b6a504b752 n/a (gamescope + 0x146752)
                #8  0x000055b6a4f64969 n/a (gamescope + 0x5f969)
                #9  0x000055b6a4f7b2c2 n/a (gamescope + 0x762c2)
                #10 0x000055b6a4f7bdf9 n/a (gamescope + 0x76df9)
                #11 0x00007fa45aee89f3 n/a (libstdc++.so.6 + 0xe89f3)
                #12 0x00007fa45aa8ff44 start_thread (libc.so.6 + 0x8ff44)
                #13 0x00007fa45ab184ec __clone3 (libc.so.6 + 0x1184ec)
                
                Stack trace of thread 13074:
                #0  0x00007fa45ab18966 epoll_wait (libc.so.6 + 0x118966)
                #1  0x000055b6a504d382 n/a (gamescope + 0x148382)
                #2  0x000055b6a4f7644c n/a (gamescope + 0x7144c)
                #3  0x00007fa45aee89f3 n/a (libstdc++.so.6 + 0xe89f3)
                #4  0x00007fa45aa8ff44 start_thread (libc.so.6 + 0x8ff44)
                #5  0x00007fa45ab184ec __clone3 (libc.so.6 + 0x1184ec)
                
                Stack trace of thread 13062:
                #0  0x00007fa45ab09d9f __poll (libc.so.6 + 0x109d9f)
                #1  0x000055b6a4f7fc36 n/a (gamescope + 0x7ac36)
                #2  0x000055b6a4f2b6d5 n/a (gamescope + 0x266d5)
                #3  0x00007fa45aa281b0 __libc_start_call_main (libc.so.6 + 0x281b0)
                #4  0x00007fa45aa28279 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x28279)
                #5  0x000055b6a4f4d7f5 n/a (gamescope + 0x487f5)
                
                Stack trace of thread 13076:
                #0  0x00007fa45aa8c4ee __futex_abstimed_wait_common (libc.so.6 + 0x8c4ee)
                #1  0x00007fa45aa8f230 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x8f230)
                #2  0x00007fa455e1bc2b n/a (libvulkan_radeon.so + 0x21bc2b)
                #3  0x00007fa455e3da17 n/a (libvulkan_radeon.so + 0x23da17)
                #4  0x00007fa45aa8ff44 start_thread (libc.so.6 + 0x8ff44)
                #5  0x00007fa45ab184ec __clone3 (libc.so.6 + 0x1184ec)
                
                Stack trace of thread 13075:
                #0  0x00007fa45ab09d9f __poll (libc.so.6 + 0x109d9f)
                #1  0x00007fa45b546d12 n/a (libSDL2-2.0.so.0 + 0x100d12)
                #2  0x00007fa45b495a28 n/a (libSDL2-2.0.so.0 + 0x4fa28)
                #3  0x000055b6a4f83048 n/a (gamescope + 0x7e048)
                #4  0x00007fa45aee89f3 n/a (libstdc++.so.6 + 0xe89f3)
                #5  0x00007fa45aa8ff44 start_thread (libc.so.6 + 0x8ff44)
                #6  0x00007fa45ab184ec __clone3 (libc.so.6 + 0x1184ec)
                
                Stack trace of thread 13079:
                #0  0x00007fa45ab161dd syscall (libc.so.6 + 0x1161dd)
                #1  0x000055b6a4f8429a n/a (gamescope + 0x7f29a)
                #2  0x000055b6a4f8c406 n/a (gamescope + 0x87406)
                #3  0x00007fa45aee89f3 n/a (libstdc++.so.6 + 0xe89f3)
                #4  0x00007fa45aa8ff44 start_thread (libc.so.6 + 0x8ff44)
                #5  0x00007fa45ab184ec __clone3 (libc.so.6 + 0x1184ec)
                
                Stack trace of thread 13095:
                #0  0x00007fa45ab18966 epoll_wait (libc.so.6 + 0x118966)
                #1  0x00007fa4574c5e64 n/a (libspa-support.so + 0x15e64)
                #2  0x00007fa4574b86fd n/a (libspa-support.so + 0x86fd)
                #3  0x00007fa45b1bdd54 n/a (libpipewire-0.3.so.0 + 0x47d54)
                #4  0x00007fa45aa8ff44 start_thread (libc.so.6 + 0x8ff44)
                #5  0x00007fa45ab184ec __clone3 (libc.so.6 + 0x1184ec)
                
                Stack trace of thread 13077:
                #0  0x00007fa45aa8c4ee __futex_abstimed_wait_common (libc.so.6 + 0x8c4ee)
                #1  0x00007fa45aa8f230 pthread_cond_wait@@GLIBC_2.3.2 (libc.so.6 + 0x8f230)
                #2  0x00007fa4583e867c n/a (/home/ricardo/.local/share/Steam/ubuntu12_64/libVkLayer_steam_fossilize.so + 0x7e67c)
                ELF object binary architecture: AMD x86-64

GNU gdb (GDB; openSUSE Tumbleweed) 13.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-suse-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.opensuse.org/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/gamescope...

This GDB supports auto-downloading debuginfo from the following URLs:
  <https://debuginfod.opensuse.org/>
Enable debuginfod for this session? (y or [n]) y
Debuginfod has been enabled.
To make this setting permanent, add 'set debuginfod enabled on' to .gdbinit.
Downloading separate debug info for /usr/bin/gamescope
(No debugging symbols found in /usr/bin/gamescope)                                                                                                                                                                                           

warning: Can't open file /dev/shm/ValveIPCSHM_1000 (deleted) during file-backed mapping note processing

warning: Can't open file /memfd:xwayland-shared (deleted) during file-backed mapping note processing

warning: Can't open file /memfd:pipewire-memfd:flags=0x0000000f,type=2,size=2312 (deleted) during file-backed mapping note processing

warning: Can't open file /memfd:xshmfence (deleted) during file-backed mapping note processing

warning: Can't open file /dev/shm/u1000-Shm_76023885 during file-backed mapping note processing

warning: Can't open file /dev/shm/u1000-Shm_61fec723 during file-backed mapping note processing

warning: Can't open file /dev/shm/u1000-Shm_4df7c983 during file-backed mapping note processing

warning: Can't open file /dev/shm/u1000-Shm_89ba8124 during file-backed mapping note processing
[New LWP 13097]
[New LWP 13074]
[New LWP 13062]
[New LWP 13076]
[New LWP 13075]
[New LWP 13079]
[New LWP 13095]
[New LWP 13077]
[New LWP 13377]
[New LWP 13096]
[New LWP 13099]
[New LWP 13489]
[New LWP 13430]                                                                                                                                         
[Thread debugging using libthread_db enabled]                                                                                                                                                                                                
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `gamescope -W 2560 -H 1440 -r 60 -f -- /home/ricardo/.local/share/Steam/ubuntu12'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fa45aa91dec in __pthread_kill_implementation () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7fa43d7fa6c0 (LWP 13097))]
</code>
</pre>
</details>

**PD**: I'll try to run the game again with PROTON_LOG=1 %command% parameter and without gamescope, if it crashes again I'll update this issue and move it to Mesa or Proton repo if related.

**Comment by RiQuY** [comment]
Update: It crashes even without gamescope active, I opened an issue in the Mesa repo feel free to close this one if the error is not related to gamescope anymore.

- https://gitlab.freedesktop.org/mesa/mesa/-/issues/10483

**Comment by RiQuY** [comment]
Update: The issue stop happening after ugprading the video drivers to Mesa 23.3.3. Feel free to close the issue if it is not relevant anymore.

**Comment by Joshua-Ashton** [comment]
This is just the result of the game hanging. Not a Gamescope bug.
