### ISSUE TITLE
gamepad and mouse input not working on non-steam games

### ISSUE THREAD

**Issue by DocMAX** [ValveSoftware/gamescope#1116]
i am on arch with a clean system, just gamescope and steam. problem is if i start non-steam games via gamescope, mouse and gamepad inputs work. if i start the game with steam they dont. any idea why?

**Comment by kisak-valve** [comment]
Hello @DocMAX, this reads more like an issue with the Steam client's Steam Input subsystem than an issue with gamescope.

There's a similar issue reported at https://github.com/ValveSoftware/steam-for-linux/issues/10430. Closing in favor of the older issue report.

**Comment by DocMAX** [comment]
I "fixed" this by starting gamescope with sddm. Using sddm gamepad input works, why?
