### ISSUE TITLE
Zenity and GTK 3.0 input dialogs don't accept text in Gaming Mode on Steam Deck with SteamOS 3.

### ISSUE THREAD

**Issue by styromaniac** [ValveSoftware/gamescope#1119]
No matter the language or GUI framework, I can never get my application fully working. What doesn't work is the input dialogs. I've tried both Zenity and GTK 3.

**Comment by kisak-valve** [comment]
Hello @styromaniac, this issue is being tracked at https://github.com/ValveSoftware/SteamOS/issues/1039.

Closing a duplicate.
