### ISSUE TITLE
Steam Deck Oled Mura Compensation broken with FSR and NIS upscaling

### ISSUE THREAD

**Issue by JDGBOLT** [ValveSoftware/gamescope#1142]
By enabling the gamescope mura compensation that is put in place for galileo/Steam Deck Oled using the command:
`DISPLAY=:0 xprop -root -f GAMESCOPE_COLOR_MURA_CORRECTION_DISABLED 32c -set GAMESCOPE_COLOR_MURA_CORRECTION_DISABLED 0`
When using the FSR and NIS upscaling methods, the screen with FSR seems to be overlaying the mura map directly onto the screen, and with NIS it becomes very washed out, as follows:

FSR:
![PXL_20240217_032659023 MP](https://github.com/ValveSoftware/gamescope/assets/791804/d5417a59-e919-44f2-840f-aa5ea7c60358)
![PXL_20240217_010159600](https://github.com/ValveSoftware/gamescope/assets/791804/e8a724a1-4d00-49fd-a1cb-c361138feff8)

NIS:
![PXL_20240217_032714543 MP](https://github.com/ValveSoftware/gamescope/assets/791804/a55dd1eb-72b4-486f-8933-4f07155567a0)

Seems like the shader is occurring at the wrong place in the chain perhaps, though could very well be something else that is messing with things. For reference both games were set to 960x600/540 on the steam deck oled with auto for the scaling mode. Do realize that this is definitely something that is not the default and likely unsupported at this time, just thought I would file an issue as with the map being available finally for my Deck Oled via the updates to galileo-mura, thought I would test things and noticed this being the current behavior. For reference this is the main channel 20240216.1000 image with gamescope 3.14.1.

**Comment by JDGBOLT** [comment]
As of the latest Steam Beta Client and the Steam Deck main channel, this is enabled by default when starting up the gamescope-session and steam, so as a result out of the box on this particular configuration this will show up always when running the main channel with the beta client and run a game or general window with fsr or nis upscaling enabled.

**Comment by Joshua-Ashton** [comment]
This is fixed now.
