### ISSUE TITLE
Unreasonably high mouse sensitivity when in game [Overwatch 2]

### ISSUE THREAD

**Issue by lividhen** [ValveSoftware/gamescope#1145]
Game is launched from steam with `gamescope -W 2560 -H 1440 -e -- %command%`. Mouse sensitivity when in control of a character is unreasonably high even when the in game sensitivity is turned to 0. Using hyprland (wlroots based compositor).

Video example:
https://nextcloud.chickenserver.org/s/54PqDq42y3EMotX

**Comment by Joshua-Ashton** [comment]
This looks like relative pointer stuff isn't working for you. Can you give more info as to how you are running Gamescope?

**Comment by lividhen** [comment]
It is running nested in my normal desktop. I am running it from the steam launch options with the command above. It is installed from the AUR package.

**Comment by Joshua-Ashton** [comment]
What is your desktop?

**Comment by lividhen** [comment]
Desktop as in environment or distro?
Running hyprland on Wayland on arch if that was the question, sorry.

**Comment by Joshua-Ashton** [comment]
Does that support pointer constraints?

**Comment by lividhen** [comment]
It should. Phasmophobia seems to be able to when in gamescope. Apps being displayed natively also can (eg. blender, minecraft).

**Comment by sharkautarch** [comment]
Hmmm, not sure if this is actually relevant to the issue, but some of the cursor-related code seems to be doing some implicit conversions between floats and double: (the `misc-no-implicit-conversions` thingy is from a [custom version of clang-tidy](https://github.com/lefticus/llvm-project/tree/add-implicit-conversion-checks))
```
src/main.cpp:268:28: warning: implicit conversion from 'double' to 'float' affects readability [misc-no-implicit-conversions]
float g_mouseSensitivity = 1.0;
...
src/main.cpp:616:26: warning: implicit conversion from 'double' to 'float' affects readability [misc-no-implicit-conversions]
                                g_mouseSensitivity = atof( optarg );
...
src/wlserver.cpp:270:17: warning: implicit conversion from 'float' to 'double' affects readability [misc-no-implicit-conversions]
                unaccel_dx *= g_mouseSensitivity;
                              ^
src/wlserver.cpp:271:17: warning: implicit conversion from 'float' to 'double' affects readability [misc-no-implicit-conversions]
                unaccel_dy *= g_mouseSensitivity;
                              ^
src/wlserver.cpp:277:26: warning: implicit conversion from 'float' to 'double' affects readability [misc-no-implicit-conversions]
                server->ctx->accum_x = modf(server->ctx->accum_x, &dx);
                                       ^
src/wlserver.cpp:277:31: warning: implicit conversion from 'double' to 'float' affects overload resolution, and might change meaning if more overloads are added [misc-no-implicit-conversions]
                server->ctx->accum_x = modf(server->ctx->accum_x, &dx);
                                            ^
src/wlserver.cpp:278:26: warning: implicit conversion from 'float' to 'double' affects readability [misc-no-implicit-conversions]
                server->ctx->accum_y = modf(server->ctx->accum_y, &dy);
                                       ^
src/wlserver.cpp:278:31: warning: implicit conversion from 'double' to 'float' affects overload resolution, and might change meaning if more overloads are added [misc-no-implicit-conversions]
                server->ctx->accum_y = modf(server->ctx->accum_y, &dy);
                                            ^
src/wlserver.cpp:280:61: warning: implicit conversion from 'float' to 'int' affects readability [misc-no-implicit-conversions]
                XTestFakeRelativeMotionEvent( server->get_xdisplay(), int(dx), int(dy), CurrentTime );
                                                                          ^
src/wlserver.cpp:280:70: warning: implicit conversion from 'float' to 'int' affects readability [misc-no-implicit-conversions]
                XTestFakeRelativeMotionEvent( server->get_xdisplay(), int(dx), int(dy), CurrentTime );
```

IMO, probably best to just change `g_mouseSensitivity`, `dx`, and `dy` to be double, which will then make `modf` be a double precision operation instead of single precision.
Oh, and cppref says that atof returns a double anyhow: https://en.cppreference.com/w/c/string/byte/atof

**Comment by tmuehlbacher** [comment]
I didn't check the issues first and so I also did the same git bisect as mentioned in #1141 on NixOS with the Steam version of Cyberpunk 2077 and did notice a pretty stark difference in mouse sensitvity when the rectangle issue occurs. I am pretty sure this issue also stems from https://github.com/ValveSoftware/gamescope/commit/88eb1b477d8b1efbe6d7087dcde74052dad84049. But since it's a pretty big commit it would take some effort to figure out what to do to fix these two issues.

**Comment by lividhen** [comment]
It does look very similar to the issue i am having in a couple other games inside gamescope. Not sure why overwatch is behaving the way it is though.

**Comment by notpeelz** [comment]
If this is the same issue as #1141, it's liked fixed by a5d853accd176d8ff8bb4c5d54b4b4cd8053b4d7

**Comment by sharkautarch** [comment]
> If this is the same issue as #1141, it's liked fixed by [a5d853a](https://github.com/ValveSoftware/gamescope/commit/a5d853accd176d8ff8bb4c5d54b4b4cd8053b4d7)

yea probably

**Comment by DomiStyle** [comment]
I ran the latest git right after that commit and both issues (rectangle mouse and high mouse sensitivity) are fixed for me.

Didn't test with Overwatch but had the rectangle issue in Helldivers 2 and the mouse sensitivity issue in Armored Core. Both work perfectly now.

**Comment by notpeelz** [comment]
I can reproduce the high-sens issue on Apex Legends.
a5d853accd176d8ff8bb4c5d54b4b4cd8053b4d7 indeed fixes it

**Comment by lividhen** [comment]
a5d853accd176d8ff8bb4c5d54b4b4cd8053b4d7 Does indeed fix it!
