### ISSUE TITLE
Build failure on Debian 12

### ISSUE THREAD

**Issue by faizanwahla** [ValveSoftware/gamescope#1153]
After installing all dependencies it still give me build error. Kindly help me out with this !

ninja logs attached*
[ninja_log.txt](https://github.com/ValveSoftware/gamescope/files/14397683/ninja_log.txt)

`ninja: Entering directory build'
[268/419] Compiling C++ object layer/libVkLayer_FROG_gamescope_wsi_x86_64.so.p/VkLayer_FROG_gamescope_wsi.cpp.o
FAILED: layer/libVkLayer_FROG_gamescope_wsi_x86_64.so.p/VkLayer_FROG_gamescope_wsi.cpp.o 
c++ -Ilayer/libVkLayer_FROG_gamescope_wsi_x86_64.so.p -Ilayer -I../layer -Isubprojects/vkroots -I../subprojects/vkroots -Isubprojects/glm-0.9.9.8 -I../subprojects/glm-0.9.9.8 -Iprotocol -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -std=c++20 -O0 -g -DWLR_USE_UNSTABLE -Wno-unused-parameter -Wno-missing-field-initializers -Wno-invalid-offsetof -Wno-unused-const-variable -Wno-volatile -Wno-ignored-qualifiers -Wno-missing-braces -ffast-math -DHAVE_PIPEWIRE=1 -DHAVE_OPENVR=1 '-DHWDATA_PNP_IDS="//usr/share/hwdata/pnp.ids"' -fPIC -MD -MQ layer/libVkLayer_FROG_gamescope_wsi_x86_64.so.p/VkLayer_FROG_gamescope_wsi.cpp.o -MF layer/libVkLayer_FROG_gamescope_wsi_x86_64.so.p/VkLayer_FROG_gamescope_wsi.cpp.o.d -o layer/libVkLayer_FROG_gamescope_wsi_x86_64.so.p/VkLayer_FROG_gamescope_wsi.cpp.o -c ../layer/VkLayer_FROG_gamescope_wsi.cpp
../layer/VkLayer_FROG_gamescope_wsi.cpp: In static member function ‘static void GamescopeWSILayer::VkInstanceOverrides::GetPhysicalDeviceFeatures2(const vkroots::VkInstanceDispatch*, VkPhysicalDevice, VkPhysicalDeviceFeatures2*)’:
../layer/VkLayer_FROG_gamescope_wsi.cpp:516:194: error: no matching function for call to ‘FindInChainMutable<VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SWAPCHAIN_MAINTENANCE_1_FEATURES_EXT, VkPhysicalDeviceSwapchainMaintenance1FeaturesEXT>(VkPhysicalDeviceFeatures2*&)’
  516 |       auto pSwapchainMaintenance1Features = vkroots::FindInChainMutable<VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SWAPCHAIN_MAINTENANCE_1_FEATURES_EXT, VkPhysicalDeviceSwapchainMaintenance1FeaturesEXT>(pFeatures);
      |                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
In file included from ../layer/VkLayer_FROG_gamescope_wsi.cpp:4:
../subprojects/vkroots/vkroots.h:59:9: note: candidate: ‘template<class Type, class AnyStruct> Type* vkroots::FindInChainMutable(AnyStruct*)’
   59 |   Type* FindInChainMutable(AnyStruct* obj) {
      |         ^~~~~~~~~~~~~~~~~~
../subprojects/vkroots/vkroots.h:59:9: note:   template argument deduction/substitution failed:
../layer/VkLayer_FROG_gamescope_wsi.cpp:516:194: error: type/value mismatch at argument 1 in template parameter list for ‘template<class Type, class AnyStruct> Type* vkroots::FindInChainMutable(AnyStruct*)’
  516 |       auto pSwapchainMaintenance1Features = vkroots::FindInChainMutable<VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SWAPCHAIN_MAINTENANCE_1_FEATURES_EXT, VkPhysicalDeviceSwapchainMaintenance1FeaturesEXT>(pFeatures);
      |                                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
../layer/VkLayer_FROG_gamescope_wsi.cpp:516:194: note:   expected a type, got ‘VK_STRUCTURE_TYPE_PHYSICAL_DEVICE_SWAPCHAIN_MAINTENANCE_1_FEATURES_EXT’
../layer/VkLayer_FROG_gamescope_wsi.cpp: In static member function ‘static VkResult GamescopeWSILayer::VkDeviceOverrides::QueuePresentKHR(const vkroots::VkDeviceDispatch*, VkQueue, const VkPresentInfoKHR*)’:
../layer/VkLayer_FROG_gamescope_wsi.cpp:911:125: error: no matching function for call to ‘FindInChain<VK_STRUCTURE_TYPE_PRESENT_TIMES_INFO_GOOGLE, const VkPresentTimesInfoGOOGLE>(const VkPresentInfoKHR*&)’
  911 |       auto pPresentTimes = vkroots::FindInChain<VK_STRUCTURE_TYPE_PRESENT_TIMES_INFO_GOOGLE, const VkPresentTimesInfoGOOGLE>(pPresentInfo);
      |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
../subprojects/vkroots/vkroots.h:50:15: note: candidate: ‘template<class Type, class AnyStruct> const Type* vkroots::FindInChain(const AnyStruct*)’
   50 |   const Type* FindInChain(const AnyStruct* obj) {
      |               ^~~~~~~~~~~
../subprojects/vkroots/vkroots.h:50:15: note:   template argument deduction/substitution failed:
../layer/VkLayer_FROG_gamescope_wsi.cpp:911:125: error: type/value mismatch at argument 1 in template parameter list for ‘template<class Type, class AnyStruct> const Type* vkroots::FindInChain(const AnyStruct*)’
  911 |       auto pPresentTimes = vkroots::FindInChain<VK_STRUCTURE_TYPE_PRESENT_TIMES_INFO_GOOGLE, const VkPresentTimesInfoGOOGLE>(pPresentInfo);
      |                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
../layer/VkLayer_FROG_gamescope_wsi.cpp:911:125: note:   expected a type, got ‘VK_STRUCTURE_TYPE_PRESENT_TIMES_INFO_GOOGLE’
[273/419] Compiling C object subprojects/wlroots/libwlroots.a.p/types_wlr_linux_dmabuf_v1.c.o
ninja: build stopped: subcommand failed.
`

**Comment by faizanwahla** [comment]
got it working by editing some code

**Comment by billbeans** [comment]
i have the same problem. how to fix?

Update: I was able to get it compiled with gcc 13 but with no wayland backend. The SDL backend works
