### ISSUE TITLE
Gamescope destroys my system

### ISSUE THREAD

**Issue by prufaraSS** [ValveSoftware/gamescope#1166]
Operating System: Arch Linux 
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.115.0
Qt Version: 5.15.12
Kernel Version: 6.7.6-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 8 × AMD Ryzen 5 2400G with Radeon Vega Graphics
Memory: 15.3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
Manufacturer: Micro-Star International Co., Ltd.
Product Name: MS-7A36
System Version: 1.0

Launching expensive Proton games (in my case Remnant: From the Ashes) causes game to launch for too long and in the process corrupts whole system.
The symptoms are (all of these are rid by simply rebooting the system):
* Video stop playing and won't load anymore (it caches as usual but only shows first loaded frame and infinitely load)
* For whatever reason sound devices are no longer seen by system, so no sound (restarting pulseaudio won't fix it)
* Discord (or chromium itself?) are getting crashed
* Applications that survived this bugathon just pretend to feel good but after several interactions are getting froze until kill
* ^ Applies for KDE Plasma taskbar as well - if you open any contest menu it will freeze as well as the taskbar
* Starting a new application creates an invisible window and it's freeze as well. (fixes after 4-5 restarts)

And after that game just starts like nothing happened! And works completely fine! (except there's no sound at all...)

Whats lead to this is that I've been trying to fix ANOTHER gamescope issue, which also doesn't seem for anyone to had!!! This issue was a thing for CS 2 and Remnant: From the Ashes, and is about that game would update only when my mouse is moving inside a game window, otherwise the game would update (and function as well) only 1 time in ~10 seconds. So, in case of fixing it the latest thing I've tried and so it lead to the current problem is downloading Winetricks (I had GStreamer plugins error and was trying to work around it), but trying to do so required for me to update all installed packages, since pacman's databases were outdated and it constantly threw 404 and "no rsync support" errors. And this is very unfortunate, because it updated amd ucodes, nvidia drivers, KDE packages and etc...

What I've tried to do:
* Downgrade nvidia drivers to 545, unsuccessful though, after reboot linux couldn't see installed drivers at all
* Every gamescope option which related to X11, Vulkan, flips or layers. (--debug-hud doesn't seem to do anything)
* Killing pulseaudio and starting it again. It actually restarted but no audio devices appeared.
* Downgrading gamescope to whatever old version from 2023, it was successful this time, but nothing changed sadly.

Showcase Video: https://youtu.be/APsIEzjNVRs

journalctl: https://pastebin.com/tww3tqrd

If something more required for problem investigation feel free to ask I'll try to get information.

**Comment by sharkautarch** [comment]
> Operating System: Arch Linux KDE Plasma Version: 5.27.10 KDE Frameworks Version: 5.115.0 Qt Version: 5.15.12 Kernel Version: 6.7.6-arch1-1 (64-bit) Graphics Platform: X11 Processors: 8 × AMD Ryzen 5 2400G with Radeon Vega Graphics Memory: 15.3 GiB of RAM Graphics Processor: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 Manufacturer: Micro-Star International Co., Ltd. Product Name: MS-7A36 System Version: 1.0
> 
> Launching expensive Proton games (in my case Remnant: From the Ashes) causes game to launch for too long and in the process corrupts whole system. The symptoms are (all of these are rid by simply rebooting the system):
> 
>     * Video stop playing and won't load anymore (it caches as usual but only shows first loaded frame and infinitely load)
> 
>     * For whatever reason sound devices are no longer seen by system, so no sound (restarting pulseaudio won't fix it)
> 
>     * Discord (or chromium itself?) are getting crashed
> 
>     * Applications that survived this bugathon just pretend to feel good but after several interactions are getting froze until kill
> 
>     * ^ Applies for KDE Plasma taskbar as well - if you open any contest menu it will freeze as well as the taskbar
> 
>     * Starting a new application creates an invisible window and it's freeze as well. (fixes after 4-5 restarts)
> 
> 
> And after that game just starts like nothing happened! And works completely fine! (except there's no sound at all...)
> 
> Whats lead to this is that I've been trying to fix ANOTHER gamescope issue, which also doesn't seem for anyone to had!!! This issue was a thing for CS 2 and Remnant: From the Ashes, and is about that game would update only when my mouse is moving inside a game window, otherwise the game would update (and function as well) only 1 time in ~10 seconds. So, in case of fixing it the latest thing I've tried and so it lead to the current problem is downloading Winetricks (I had GStreamer plugins error and was trying to work around it), but trying to do so required for me to update all installed packages, since pacman's databases were outdated and it constantly threw 404 and "no rsync support" errors. And this is very unfortunate, because it updated amd ucodes, nvidia drivers, KDE packages and etc...
> 
> What I've tried to do:
> 
>     * Downgrade nvidia drivers to 545, unsuccessful though, after reboot linux couldn't see installed drivers at all
> 
>     * Every gamescope option which related to X11, Vulkan, flips or layers. (--debug-hud doesn't seem to do anything)
> 
>     * Killing pulseaudio and starting it again. It actually restarted but no audio devices appeared.
> 
>     * Downgrading gamescope to whatever old version from 2023, it was successful this time, but nothing changed sadly.
> 
> 
> Showcase Video: https://youtu.be/APsIEzjNVRs
> 
> journalctl: https://pastebin.com/tww3tqrd
> 
> If something more required for problem investigation feel free to ask I'll try to get information.


Question:
does this issue still happen if you launch gamescope with:
`ENABLE_GAMESCOPE_WSI=0 gamescope <other gamescope params> -- %command%`

**Comment by prufaraSS** [comment]
> > Replying to [#1166 (comment)](https://github.com/ValveSoftware/gamescope/issues/1166#issue-2160983883)
> 
> Question: does this issue still happen if you launch gamescope with: `ENABLE_GAMESCOPE_WSI=0 gamescope <other gamescope params> -- %command%`

Yes, This command doesn't affect anything in fresh system. Game launches instantly in broken system though, not sure if it's done because of this command.
> EDIT: from youy journalctl log:
> 
> > Feb 29 15:26:40 localhost plasmashell[1938]: [2024-02-29 15:26:35] Startup - Steam Client launched with: '/home/max/.local/share/Steam/ubuntu12_32/steam' 'gamescope' '-e' '--'
> 
> are you launching steam client with gamescope, or are you running proton games w/ gamescope via steam launch options?

I'm running proton games with gamescope via steam launch options.
I'm gonna try downgrading to 535 drivers and build your fork next day for sure.
P.s. One thing is I'm using "nvidia" package for drivers, not the dkms one.

**Comment by prufaraSS** [comment]
building 535 drivers ended in a complete failure. rebuilding kernel with DKMS driver caused driver to throw a lot of errors in which it can't find kernel directories, and also building nvidia settings threw me this error:
```
make[1]: Leaving directory '/home/max/nvidia-535xx-settings/src/nvidia-settings-535.161.07/samples'
make[1]: Entering directory '/home/max/nvidia-535xx-settings/src/nvidia-settings-535.161.07/doc'
   HOST_CC      ../src/gen-manpage-opts.c
   HOST_CC      ../src/common-utils/gen-manpage-opts-helper.c
   HOST_LINK    home/max/nvidia-535xx-settings/src/nvidia-settings-535.161.07/doc/out/gen-manpage-opts
   M4           nvidia-settings.1.m4
/bin/sh: line 2: m4: command not found
make[1]: *** [Makefile:112: out/nvidia-settings.1] Error 127
make[1]: *** Deleting file 'out/nvidia-settings.1'
make[1]: Leaving directory '/home/max/nvidia-535xx-settings/src/nvidia-settings-535.161.07/doc'
make: *** [Makefile:25: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...

```
(can't provide full log since its flooded with gtk-3.0 warnings of deprecated functions)
I guess for now I can only hope that in recent 550 version they're fixed compatibilities and try to compile a patched gamescope version.

**Comment by sharkautarch** [comment]
> building 535 drivers ended in a complete failure. rebuilding kernel with DKMS driver caused driver to throw a lot of errors in which it can't find kernel directories, and also building nvidia settings threw me this error:
> 
> ```
> make[1]: Leaving directory '/home/max/nvidia-535xx-settings/src/nvidia-settings-535.161.07/samples'
> make[1]: Entering directory '/home/max/nvidia-535xx-settings/src/nvidia-settings-535.161.07/doc'
>    HOST_CC      ../src/gen-manpage-opts.c
>    HOST_CC      ../src/common-utils/gen-manpage-opts-helper.c
>    HOST_LINK    home/max/nvidia-535xx-settings/src/nvidia-settings-535.161.07/doc/out/gen-manpage-opts
>    M4           nvidia-settings.1.m4
> /bin/sh: line 2: m4: command not found
> make[1]: *** [Makefile:112: out/nvidia-settings.1] Error 127
> make[1]: *** Deleting file 'out/nvidia-settings.1'
> make[1]: Leaving directory '/home/max/nvidia-535xx-settings/src/nvidia-settings-535.161.07/doc'
> make: *** [Makefile:25: all] Error 2
> ==> ERROR: A failure occurred in build().
>     Aborting...
> ```
> 
> (can't provide full log since its flooded with gtk-3.0 warnings of deprecated functions) I guess for now I can only hope that in recent 550 version they've fixed compatibilities and try to compile a patched gamescope version.


hmmm... weird
you don't *strictly* need the nvidia-settings package, unless you want custom settings I guess...
can you post a pastebin link for the errors you got when building the nvidia 535 driver?

**Comment by prufaraSS** [comment]
@sharkautarch
I've tried a few more things (gamescope is still with ENABLE_GAMESCOPE_WSI=0 prefix):
1) Installed gamescope-nvidia AUR package
2) Tested out different Proton versions
3) Installed gamescope with nvidia-fix-latest-upstream
4) Removed gst related plugins (still didn't tested it out)
5) Installed nouveau driver (i've got shocked it literally doesn't use GPU and doesn't work with Vulkan...)
6) Tried to install 535 nvidia dkms driver again. Full log starting from downloading package here: https://pastebin.com/VCnRbxkY

**Comment by sharkautarch** [comment]
> Replying to https://github.com/ValveSoftware/gamescope/issues/1166#issuecomment-1973556797

hmmmm since your computer has hybrid graphics (amd iGPU and nvidia discrete GPU) you might need to pass the `--prefer-vk-device` param to gamescope, like so:

`ENABLE_GAMESCOPE_WSI=0 gamescope --prefer-vk-device $(lspci -nn | grep 3D | grep NVIDIA | tr -d '][' | tr ' ' $'\n' | grep 10de) ...`

if that still doesn't work, as a sanity check, see if it also fails to run glxgears:
`ENABLE_GAMESCOPE_WSI=0 gamescope --prefer-vk-device $(lspci -nn | grep 3D | grep NVIDIA | tr -d '][' | tr ' ' $'\n' | grep 10de) -- glxgears`
If still fails to run, you probably need to try installing nvidia 535 dkms again, and I think I know what you need to do to get the driver dkms package to compile right:
- double check that you're using the normal linux kernel package:
 `pacman -Qs linux | grep -B 1 kernel`
- make sure you have the linux kernel **headers** installed:
 `pacman -Qs linux | grep -B 1 kernel | grep header`
- if you don't see `local/linux-headers`, then that was your problem. do: `pacman -S linux-headers`
- If you already had the linux-headers installed, or if the package still fails to build for you then try using the PKGBUILD that I had installed on my system (seems like my version is slightly different from the AUR one, probably because I never cared to update it): https://gist.github.com/sharkautarch/7c4b0f5c12434efdd8f28b4216d62382

**Comment by prufaraSS** [comment]
The problem with driver compiling truly was in linux headers, you've got bullseye with this one. Soooo...
1. With 535 nothing changed.
2. With --prefer-vk-device nothing changed.
3. Trying out gamescope glxgears caused system a bit of freeze before showing up window (my video stopped showing for a few seconds)
4. Its not KDE fault as well - same problem occurs on Xfce4

**Comment by prufaraSS** [comment]
I've just find out it breaks the system even without getting started as a gamescope app 💀

**Comment by prufaraSS** [comment]
I've got back to the moment when game starts just fine but in gamescope it updates only on mouse movement. ENABLE_GAMESCOPE_WSI=0 changed nothing. I'm not sure what to do with this thread now, since the main problem solved, but gamescope still doesn't function well.
Just for archive: I've been trying to remove every audio-related package in my system just for curiosity, and it turned out my desktop environment started freezing every boot. Then I've decided to remove 535 drivers and get back my 550 drivers. SDDM stopped launching at all... I had no idea why: the last time it happened i figured out i have no driver at all (i just forgor to install them 💀 ), so I've started checking blacklists, xorg (there actually was a problem, that there was no driver specified for device), sddm config, ended up just removing and reinstalling drivers and it worked. So, after my boot I've decided to test out game again, and noticed i have no steam, no discord, no firefox. I've installed steam and like 999 dependencies for it, started the game, and it started as before! I guess the problem was in conflicting in steam dependencies.

**Comment by prufaraSS** [comment]
Installing 535 again made me finally successfully launch the game on gamescope! But... Poor performance. I can clearly see game never shows me more than 60 fps. gfxgears show me that in fullscreen average fps is 60, while in windowed mode average is 116

**Comment by prufaraSS** [comment]
Changing to X11 solved framerate issue. Gamescope works as intended now, thanks to @sharkautarch !

**Comment by Milor123** [comment]
How can use it in KDE plasma 6 in wayland, its bug again for me :/ I have a 4070, Driver Version: 550.120  in manjaro

**Comment by prufaraSS** [comment]
> How can use it in KDE plasma 6 in wayland, its bug again for me :/ I have a 4070, Driver Version: 550.120 in manjaro
> 
> ```
> console: gamescope version 3.15.11+ (gcc 14.2.1)
> No CAP_SYS_NICE, falling back to regular-priority compute and threads.
> Performance will be affected.
> ATTENTION: default value of option vk_khr_present_wait overridden by environment.
> ATTENTION: default value of option vk_khr_present_wait overridden by environment.
> [gamescope] [Info]  vulkan: selecting physical device 'NVIDIA GeForce RTX 4070': queue family 2
> [gamescope] [Info]  vulkan: physical device supports DRM format modifiers
> [gamescope] [Error] vulkan: vkCreateDevice failed (VkResult: -7)
> terminate called without an active exception
> ```

if still relevant, just system update, everything works amazing now
