### ISSUE TITLE
Gamescope Crashes with `Failed to create backend` starting from `ce1156a` 

### ISSUE THREAD

**Issue by sonic2kk** [ValveSoftware/gamescope#1178]
### Information
- Version: Tested Gamescope built from source from `ce1156af053239e662aa021dbfc6a64cb770f64a` up to `e48bfc87d26dab50c5aad5a6f696c6e21c1ac22b` (latest at time of writing) (ce1156a...e48bfc8).
- OS: Arch Linux + KDE Plasma Wayland 5.27.10
- GPU: AMD 7900XTX
- Drivers: Mesa 24.0.2

When trying to run GameScope with any application (i.e. `gamescope -- glxgears`, or something a bit more exotic like `gamescope --expose-wayland -- protonup-qt`), it crashes early on with the following output, starting from ce1156af053239e662aa021dbfc6a64cb770f64a:

```
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
Your Wayland compositor does NOT support wp_presentation/presentation-time which is required for VK_KHR_present_wait and VK_KHR_present_id.
Please complain to your compositor vendor for support. Falling back to X11 window with less accurate present wait.
xdg_backend: Couldn't create Wayland objects.
Failed to create backend.
```

The rest of this logging is present in working Gamescope versions, so the notable lines I believe are:

```
xdg_backend: Couldn't create Wayland objects.
Failed to create backend.
```

This issue does not occur in 14a1db3a57612e5cfbba6d4c19688eafdc6c4043 and below at least a few commits below. I believe before updating I was using ba5f9e8e0c490ebadc1012ff1e6f5a38cb4a00f7 and it was also working.

**Comment by sonic2kk** [comment]
This issue may be specific to Plasma 5, once Plasma 6 makes its way to my distribution in stable repos I'll retry and see if the issue persists.

**Comment by Zoarial94** [comment]
The issue is likely that gamescope started using a new Wayland backend when it detects Wayland. Unfortunately there's no software switch to change backends. Can you try 14a1db3a57612e5cfbba6d4c19688eafdc6c4043? That commit still uses SDL.

**Comment by Zoarial94** [comment]
You're right. I did miss it. I would assume that Plasma 6 brought new features to WKin that Gamescope now relies on. You could try editing main.cpp to use the SDL backend instead of Wayland and see if that resolves your problem. I don't have the time to write it out, sorry. 

I'm sure there's someone with deeper knowledge who can chime in. I also think it wouldn't be a bad idea to add a flag to toggle which backend is in use (at least while Wayland is being developed)

**Comment by Kizaing** [comment]
As of the 3.14.2 update, I have also been getting this error, previously it worked fine

OpenSUSE Tumbleweed
Kernel 6.7.7
Plasma 5.27.10

**Comment by Joshua-Ashton** [comment]
The fallback should be there in master

**Comment by sonic2kk** [comment]
I'm on Plasma 6 now but if someone can test that this works on Plasma 5 I will close this issue.

Thanks!

**Comment by dpanter** [comment]
Running Siduction (Debian sid base) with Plasma Wayland 5.27.10, 6900XT, Mesa-git 24.1

Built `9567fb3` just now, chokes with the same error.
```
$ gamescope
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
Your Wayland compositor does NOT support wp_presentation/presentation-time which is required for VK_KHR_present_wait and VK_KHR_present_id.
Please complain to your compositor vendor for support. Falling back to X11 window with less accurate present wait.
xdg_backend: Couldn't create Wayland objects.
terminate called without an active exception
Aborted
```

Built `14a1db3` and it works normally. It also complains about wp_presentation/presentation-time.
