### ISSUE TITLE
Cursor escaping even in full-screen

### ISSUE THREAD

**Issue by VeilSilence** [ValveSoftware/gamescope#1181]
- OS: Arch linux
-  Hyprland ( wlroots ) based compositor
- GPU: Nvidia 3090 RTX
- Driver: 550.54.14-1
- Gamescope commit: e48bfc87d26dab50c5aad5a6f696c6e21c1ac22b
- Software cursor enabled coz nvidia.
After moving to wayland backend, gamescope finally works with nvidia for me. It even eliminates glitches because of lacking implicit sync in nvidia driver. 
However, my mouse escaping in all the games I tested with dual monitors. 
Side note: In dota for example, if i'm trying to set "advanced setting" "Display mode: Desktop-friendly Fullscreen" image freezes in dota with these errors:
```shell
pipewire: renegotiating stream params (size: 2560x1440)
warning: The VAD has been replaced by a hack pending a complete rewrite
[Gamescope WSI] Creating swapchain for xid: 0x400209 - minImageCount: 6 - format: VK_FORMAT_R8G8B8A8_SRGB - colorspace: VK_COLOR_SPACE_SRGB_NONLINEAR_KHR - flip: true
[Gamescope WSI] Created swapchain for xid: 0x400209 - imageCount: 6
wlserver: create_swapchain: Surface already had a gamescope_swapchain! Overriding.
xwm: waylandres but no win
xwm: waylandres but no win
xwm: waylandres but no win
xwm: waylandres but no win
xwm: waylandres but no win
xwm: waylandres but no win
```

**Comment by sharkautarch** [comment]
> * OS: Arch linux
> 
>     * Hyprland ( wlroots ) based compositor
> 
>     * GPU: Nvidia 3090 RTX
> 
>     * Driver: 550.54.14-1
> 
>     * Gamescope commit: [e48bfc8](https://github.com/ValveSoftware/gamescope/commit/e48bfc87d26dab50c5aad5a6f696c6e21c1ac22b)
> 
>     * Software cursor enabled coz nvidia.
>       After moving to wayland backend, gamescope finally works with nvidia for me. It even eliminates glitches because of lacking implicit sync in nvidia driver.
>       However, my mouse escaping in all the games I tested with dual monitors.
>       Side note: In dota for example, if i'm trying to set "advanced setting" "Display mode: Desktop-friendly Fullscreen" image freezes in dota with these errors:
> 
> 
> ```shell
> pipewire: renegotiating stream params (size: 2560x1440)
> warning: The VAD has been replaced by a hack pending a complete rewrite
> [Gamescope WSI] Creating swapchain for xid: 0x400209 - minImageCount: 6 - format: VK_FORMAT_R8G8B8A8_SRGB - colorspace: VK_COLOR_SPACE_SRGB_NONLINEAR_KHR - flip: true
> [Gamescope WSI] Created swapchain for xid: 0x400209 - imageCount: 6
> wlserver: create_swapchain: Surface already had a gamescope_swapchain! Overriding.
> xwm: waylandres but no win
> xwm: waylandres but no win
> xwm: waylandres but no win
> xwm: waylandres but no win
> xwm: waylandres but no win
> xwm: waylandres but no win
> ```


Does running gamescope with: `ENABLE_GAMESCOPE_WSI=0 gamescope <other params> -- <program>` 
change anything?

**Comment by VeilSilence** [comment]
`ENABLE_GAMESCOPE_WSI=0 gamescope -w 2560 -h 1440 -f  glxgears` for example. Gamescope make glxgears fullscreen on my monitor, but mouse still escaping monitor easily

**Comment by sharkautarch** [comment]
> `ENABLE_GAMESCOPE_WSI=0 gamescope -w 2560 -h 1440 -f glxgears` for example. Gamescope make glxgears fullscreen on my monitor, but mouse still escaping monitor easily Same for dota 2.


hmm does it also happen when not fullscreened?

**Comment by Joshua-Ashton** [comment]
Well, cursor escaping on glxgears is expected -- it doesn't hide the cursor, which we interpret as going into 'grab'/relative mode.

You can `--force-grab-cursor` if you want that behaviour always.

**Comment by VeilSilence** [comment]
Pardon for bad example then. 
Dota 2. Steam launch option `gamescope -w 2560 -h 1440 -f --force-grab-cursor  gamemoderun mangohud  %command% ` 
Not sure how to properly record two monitors at same time, so sorry for that.

https://github.com/ValveSoftware/gamescope/assets/132572320/e64b2231-b9ef-462a-8cbe-0e5c60110afd

With `--force-grab-cursor ` cursor moves slowly in dota 2, but still can escape by itself to the right monitor as i'm trying to show on video. Without gamescope, dota 2 with "Desktop friendly fullscreen" can hold cursor in game, but it's unusable atm on nvidia.

**Comment by Joshua-Ashton** [comment]
Am not able to reproduce here on labwc or Plasma Wayland... Perhaps this is a Hyprland bug with cursor locking?

**Comment by VeilSilence** [comment]
Tested on sway and yea, with `--force-grab-cursor` even in glxgears cursor locked on gamescope, so i'm going to do issue on Hyprland then.
One last thing before I close this issue.
Should i make a separate issue of this bug, where dota is freezing when i'm trying to set "Desktop Friendly-Desktop"?

https://github.com/ValveSoftware/gamescope/assets/132572320/bd5cc596-a49f-48fb-a9a2-3424c3822536

after that, i see this errors endlessly. 
```shell
xwm: waylandres but no win
xwm: waylandres but no win
xwm: waylandres but no win
```

**Comment by sharkautarch** [comment]
> One last thing before I close this issue. Should i make a separate issue of this bug, where dota is freezing when i'm trying to set "Desktop Friendly-Desktop"?
>
> after that, i see this errors endlessly.
> 
> ```shell
> xwm: waylandres but no win
> xwm: waylandres but no win
> xwm: waylandres but no win
> ```


Does it happen when you launch dota + gamescope with `ENABLE_GAMESCOPE_WSI=0 gamescope ...` ?

**Comment by VeilSilence** [comment]
> > One last thing before I close this issue. Should i make a separate issue of this bug, where dota is freezing when i'm trying to set "Desktop Friendly-Desktop"?
> > after that, i see this errors endlessly.
> > ```shell
> > xwm: waylandres but no win
> > xwm: waylandres but no win
> > xwm: waylandres but no win
> > ```
> 
> Does it happen when you launch dota + gamescope with `ENABLE_GAMESCOPE_WSI=0 gamescope ...` ?

Just tested and no, when i click apply, dota working.

**Comment by sharkautarch** [comment]
> > Replying to [#1181 (comment)](https://github.com/ValveSoftware/gamescope/issues/1181#issuecomment-1981624055)
> 
> Just tested and no, when i click apply, dota working like intended. Note that i tested this behavior on plasma 6. Same thing. I also tested cursor escaping in plasma 6 and sway. Dota 2 again with `gamescope --params %command%`. Cursor escaping my monitor in menu/game in both cases. With `--force-grab-cursor` it stays in dota 2 boundaries in both compositors.


Didn't seem entirely clear from your reply, but can you confirm that you don't experience freezing w/ "Desktop Friendly-Desktop" if you run with `ENABLE_GAMESCOPE_WSI=0`?
Because if so, then the freezing problem is probably the same issue as w/ https://github.com/ValveSoftware/gamescope/issues/1091
Which Joshua-Ashton is working on addressing

**Comment by VeilSilence** [comment]
Yes, in `ENABLE_GAMESCOPE_WSI=0` works as intended. 
Thanks for the assistance.

**Comment by Joshua-Ashton** [comment]
That makes nooo sense, what? That doesn't change anything about what we do with the cursor...

**Comment by VeilSilence** [comment]
> That makes nooo sense, what? That doesn't change anything about what we do with the cursor...

To clarify: `ENABLE_GAMESCOPE_WSI=0` only fixing that you can change in dota 2 settings. Like you can change resolution and set "Desktop Friendly Fullscreen", without making game freeze.
Another bug is that cursor leaving game. `ENABLE_GAMESCOPE_WSI=0` not fixing this. `--force-grab-cursor` helps in plasma and wlroots for me. 
I just reported two bugs in same thread, sorry for confusion.
