### ISSUE TITLE
HDR crash on AMDGPU

### ISSUE THREAD

**Issue by perroboc** [ValveSoftware/gamescope#1189]
Using vk_hdr_layer from git, and gamescope 3.14.2 from fedora 40, testing Ori on a HDR enabled monitor. 

Steam launched with `VK_LOADER_DEBUG=error,warn,info ENABLE_HDR_WSI=1 gamescope --hdr-enabled --hdr-debug-force-output --steam -- env ENABLE_GAMESCOPE_WSI=1 DXVK_HDR=1 DISABLE_HDR_WSI=1 steam -bigpicture`

Launching Ori (HDR enabled game) crashes gamescope (I think).

Log: https://gist.github.com/perroboc/73dcfb816b4dcc7c2557513b42238ec8

**Comment by Joshua-Ashton** [comment]
If you try latest Gamescope master, no layer stuff is necessary, just --hdr-enabled.

**Comment by perroboc** [comment]
> If you try latest Gamescope master, no layer stuff is necessary, just --hdr-enabled.

Awesome! Thank you! It works now :)
![image](https://github.com/ValveSoftware/gamescope/assets/2722773/aa7eab27-0885-4ef3-a555-30b2319fe2bc)

Note for anyone in Fedora 40 wanting to build gamescope: Had a bit of trouble with gcc 14 (gcc complained about libliftoff and wlroots). I've summarized my findings in https://gist.github.com/perroboc/e090a556d262c9775f88295bd4f6b361 but basically, you need to apply some patches to change the order of the arguments in some calls.

Now I was able to run steam normally in my plasma 6 desktop, and set Ori to run as `gamescope --hdr-enabled %command%`, and it works! This is AWESOME!
