### ISSUE TITLE
Display corruption and doesn't change resolution or refresh rate when starting from or switching to tty in embedded

### ISSUE THREAD

**Issue by MCPO-Spartan-117** [ValveSoftware/gamescope#1191]
**Kernel:** 6.7.6 with patches from CachyOS, TKG, Gentoo and RT
**Distro:** Artix(Updated system a day ago)
**PKGBUILD:** https://github.com/Frogging-Family/gamescope-git
**DISPLAY:** AW3423DWF
**GPU:** RX 6700 xt
**Mesa:** 24.0.2
**Commands:**
`gamescope -r 168 -w 2064 -h 864 --reshade-effect LUT.fx -F fsr --fsr-sharpness 0 -- strat djentoo ./bwrap-DXVK.sh --embd --lug` (--embd starts urxvt -fg blue -bg black +sb)
`gamescope -W 1920 -H 1080 -w 2064 -h 864 --reshade-effect LUT.fx -F fsr --fsr-sharpness 0 -- strat djentoo ./bwrap-DXVK.sh --embd --lug`
`gamescope -- urxvt`
`gamescope -- freecad`

### Prevents display refresh: 88eb1b477d8b1efbe6d7087dcde74052dad84049 to latest

The display doesn't change refresh rate or resolution as it doesn't seem like it was requested to refresh.

### Display corruption: ce1156af053239e662aa021dbfc6a64cb770f64a to latest

Display corruption is like 9x30 200x200 somewhat transparent square pixel blocks going from the bottom to the top blocking 80% of the screen.

This could be a similar issue to #669, as i am using Xorg beside it.

Using `RADV_DEBUG=zerovram` clears the corruption.

**Comment by MCPO-Spartan-117** [comment]
**Kernel:** 6.8.0 with RT patches
**Distro:** Gentoo
**Ebuild:** Manual
**DISPLAY:** ASUS PG248Q
**GPU:** RTX 3080
**Nvidia Drivers:** 535.161.07
**Commands:**
`gamescope vkcube`
`gamescope -r 120 vkcube`
`gamescope -H 720 vkcube`

### Prevents display refresh:

Nvidia GPUs are also affected by this commit, as they cannot change refresh rate or resolution.

### Display corruption:

Wasn't affected, but uses wayland(hyprland) with xwayland.

**Comment by alzheimerspenguin** [comment]
mine is borked also; display artifacts; can't set refresh rate, no image at all until i switch away from and then back to gamescopes tty.

Arch Linux
ROG Strix G513QY
6.8.1-arch1-1
AMD 6800M
mesa head
gamescope head
display: LG G3

**Comment by alzheimerspenguin** [comment]
Hi,

After looking at your recent commits I rebuilt.
The artifacts problem appears to be solved.
Display correctly set to 120Hz as I expected; rather than 60Hz.

...Although; mouse input is now possibly broken....
I will do more testing!

**Comment by MCPO-Spartan-117** [comment]
These issues have been fixed by these commits.
Prevents display refresh: 4a487853258754d72e5f43a78e717040ee24a406
Display corruption: 7ed173f385a8a0c345dae256d523c699f51cd2c6
