### ISSUE TITLE
Duvida sobre o gamescope

### ISSUE THREAD

**Issue by AgoraSim21** [ValveSoftware/gamescope#1201]
Ola, queria fazer uma pergunta:
tem como instalar o gamescope no linux sem precisar fazer a construcao? o gamescope inclui o limitador de fps, tdp, hz do monitor etc integrado ao big picture ?
no futuro o gamescope vira embutido e por padrao dentro do instalador da Steam, mas facil de configurar aos usuarios leigos ?
Queria poder usar, mas nao sei construir, compilar no momento 😅

Utilizo o Kubuntu lts
laptop ideapad 3 15itl6 82md
1920x1080p 60hz
intel i3 1115G4
ram 4gb
swap 20gb
btrfs
abnt2 ptbr utf8

Desde ja agradeco, sucesso por ai sempre 😄😄

**Comment by PedroHLC** [comment]
> tem como instalar o gamescope no linux sem precisar fazer a construcao?

O Gamescope está disponível no repositório "Multiverse" para todas as variações do Ubuntu 23.10. Seu Kubuntu ta na versão "LTS". Primeiramente, atualize-o para "23.10", depois certifique-se que possui o repositório "Multiverse" habilitado, por fim `sudo apt install gamescope`.

> o gamescope inclui o limitador de fps, tdp, hz do monitor etc integrado ao big picture ?

Não, essas funções são exclusivas do SteamDeck.

> mas facil de configurar aos usuarios leigos?

Isso não seria um trabalho para Valve e sim para os desenvolvedores do Kubuntu. Outras distribuições como o [Nobara Linux](https://nobaraproject.org/) já facilitaram esse processo.

**Comment by AgoraSim21** [comment]
ok thanks, 😄
