### ISSUE TITLE
gamescope causes "Fence fallback timer expired on ring comp_X.Y.Z" every few minutes

### ISSUE THREAD

**Issue by DomiStyle** [ValveSoftware/gamescope#1205]
I played a lot of Helldivers 2 recently through gamescope with HDR enabled and I noticed that gamescope intermittently freezes every few minutes for up to half a second. Sometimes those freezes are shorter but they are long enough to be very distracting.

I thought this is a Helldivers issue but I'm encountering the same thing on Horizon: Forbidden West now. Running those games without gamescope does not produce these freezes.

Looking through the logs I found the following line that pops up in my kernel log every time such a freeze happens:

`[ 2460.769006] [drm] Fence fallback timer expired on ring comp_1.2.1` 

I'm running the latest gamescope from git (09f632b13f85dad92275c43e721bb62de68fbd4a).

gamescope command used: `PROTON_LOG=1 gamescope --hdr-enabled --nested-refresh 165 --fullscreen --steam -w 3440 -W 3440 -h 1440 -H 1440 -- %command%`

Steam log: [steam.txt](https://github.com/ValveSoftware/gamescope/files/14721847/steam.txt)
Proton log: [steam-2420110.log](https://github.com/ValveSoftware/gamescope/files/14721851/steam-2420110.log)
Kernel log only shows the line above.

System info:
```
System:
  Host: domi-pc Kernel: 6.8.0-63.fc40.1.x86_64 arch: x86_64 bits: 64
  Desktop: KDE Plasma v: 6.0.2 Distro: Fedora Linux 40 (KDE Plasma
    Prerelease)
Machine:
  Type: Desktop Mobo: ASRock model: X570 Phantom Gaming 4
    serial: <superuser required> UEFI: American Megatrends v: P4.50
    date: 10/19/2022
Memory:
  System RAM: total: 32 GiB available: 31.26 GiB used: 10.07 GiB (32.2%)
  Array-1: capacity: 128 GiB slots: 4 modules: 4 EC: None
  Device-1: Channel-A DIMM 0 type: DDR4 size: 8 GiB speed: 3200 MT/s
  Device-2: Channel-A DIMM 1 type: DDR4 size: 8 GiB speed: 3200 MT/s
  Device-3: Channel-B DIMM 0 type: DDR4 size: 8 GiB speed: 3200 MT/s
  Device-4: Channel-B DIMM 1 type: DDR4 size: 8 GiB speed: 3200 MT/s
CPU:
  Info: 8-core model: AMD Ryzen 7 5800X3D bits: 64 type: MT MCP cache:
    L2: 4 MiB
  Speed (MHz): avg: 3146 min/max: 2200/4549 cores: 1: 3283 2: 3094 3: 3560
    4: 2879 5: 3267 6: 3584 7: 3562 8: 2200 9: 3551 10: 2874 11: 3177 12: 2873
    13: 3060 14: 3577 15: 2924 16: 2874
Graphics:
  Device-1: AMD Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] driver: amdgpu
    v: kernel
  Device-2: Remo Tech OBSBOT Tiny 4K driver: snd-usb-audio,uvcvideo
    type: USB
  Display: wayland server: X.org v: 1.20.14 with: Xwayland v: 23.2.4
    compositor: kwin_wayland driver: X: loaded: amdgpu
    unloaded: fbdev,modesetting,radeon,vesa dri: radeonsi gpu: amdgpu
    resolution: 3440x1440
  API: EGL v: 1.5 drivers: radeonsi,swrast
    platforms: wayland,x11,surfaceless,device
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.0.0 renderer: AMD
    Radeon RX 6900 XT (radeonsi navi21 LLVM 17.0.6 DRM 3.57
    6.8.0-63.fc40.1.x86_64)
  API: Vulkan v: 1.3.275 drivers: N/A surfaces: xcb,xlib,wayland
```

**Comment by Joshua-Ashton** [comment]
Hwlldivers 2 has a known freezing/hang bug. You should test with latest Mesa git.

**Comment by DomiStyle** [comment]
Should probably have called it stutter rather than freeze. The game works fine, it just stutters. The Helldivers 2 issue was proper freezing on the 7000 series I think?

I did some more testing over the weekend and while mesa-git reduces how often those stutters happen, they still do happen every 15-30 minutes.

I also noticed that if I put my GPU into the "3D fullscreen" mode in corectrl the stutters become more obvious, with one happening every minute or so.

Borrowed a 7900 XTX today so I'm going to test if it happens there as well. For reference, this is what these stutters look like:

https://github.com/ValveSoftware/gamescope/assets/975131/d70584e4-f4b7-4c0e-93ff-a2bd37e77483

**Comment by sharkautarch** [comment]
@DomiStyle 
I’m curious
How does the stuttering differ between playing the game w/ gamescope vs w/o it, when using mesa-git?
If the issue is still significantly worse w/ gamescope, do you also encounter this issue w/ gamescope 3.14.2? (aka the stable gamescope repo package)

**Comment by DomiStyle** [comment]
> How does the stuttering differ between playing the game w/ gamescope vs w/o it, when using mesa-git?

Stutter does not happen w/o gamescope, even on mesa-git. However, the interval between these stutters is big enough on mesa-git that it is hard to reproduce reliably.

> do you also encounter this issue w/ gamescope 3.14.2?

Yes, it also happens on the current gamescope version in the Fedora 40 repo, which is 3.14.2.

Will play some more with the 7900 XTX to see if there's a difference.

**Comment by sharkautarch** [comment]
hmmm
Does running gamescope with `DISABLE_GAMESCOPE_WSI=1 gamescope ...` change anything?

**Comment by sharkautarch** [comment]
Also, I've found an issue on gitlab freedesktop for amd drm that might be relevant:
https://gitlab.freedesktop.org/drm/amd/-/issues/2372#note_2281224

Interestingly, someone claimed that changing a game from using dx12 to dx11 'fixed' the issue for them

**Comment by DomiStyle** [comment]
> Does running gamescope with DISABLE_GAMESCOPE_WSI=1 gamescope ... change anything?

Will have to get back to you when I installed the 6900 XT again. Played with the 7900 XTX for several hours and did not have the issue.

> Interestingly, someone claimed that changing a game from using dx12 to dx11 'fixed' the issue for them

That seems to match with my tests because it only happens with VKD3D games, not DXVK.

**Comment by DomiStyle** [comment]
Did some more testing with the 6900 XT and I'm still seeing the same 500ms stutter.

However, since it only happens with the power profile set in Corectrl I assume the issue lies deeper in Mesa or amdgpu. Closing this and keeping watch of the issue linked by @sharkautarch .
