### ISSUE TITLE
Mouse position incorrectly offset with fractional scaliing

### ISSUE THREAD

**Issue by sonic2kk** [ValveSoftware/gamescope#1208]
## System Information
- Distro: Arch Linux
- Desktop: KDE Plasma Wayland 6.0.2.
- Gamescope version: Commit 09f632b13f85dad92275c43e721bb62de68fbd4a
- GPU: AMD 7900XTX
- Drivers: Mesa 24.0.3

## Issue
- According to a `git bisect`, this issue first started appearing in e5e00b9ffdcce2a8386c5b0a3bfebb50c94cb5b6. I also manually verified that the commit before this, a559b04c3b44f9a02d4d71dc61afb6b023e62b38, works correctly (this was my first time bisecting so wanted to confirm manually as well :slightly_smiling_face:)
    - This was not introduced by 6394fbcdb54f4de9fd767a134c5f522f278c1361, I thought to test this based on the commit message. Mouse behaviour is fine in this commit, and I used this as the first good commit for the bisect.
- Across all bisected commits, the mouse works correctly on unscaled displays.

When using Gamescope on a scaled display, such as a 4k@150%, the mouse will appear in the correct position, but hover behaviour and such is broken. When a mouse is directly over an element, the game will not activate a hover event, likely because it "perceives" the mouse to be in the wrong location. You might have to move it to the side a lot more before the application recognises the mouse position properly.

This behaviour does not happen on unscaled displays.

From looking at the commits it seems like a lot of work is going on around the fractional scaling protocol, so perhaps this is already known.

**Comment by sonic2kk** [comment]
There are some strange exceptions to this behaviour. I'll note my test cases then:

Working:
- SuperTux 2 (Native Linux)

Not working (reproduces this issue):
- PowerWash Simulator (Proton Experimental)
- SuperTuxKart (Native Linux)
- Katawa Shoujo (Flatpak)

**Comment by tornadus** [comment]
A workaround for affected games is forcing the old SDL X11 backend, as I described here: https://github.com/ValveSoftware/gamescope/issues/1245#issuecomment-2081737728
Hopefully this gets fixed soon, I imagine the native wayland backend has some advantages over the old SDL one.

**Comment by dinotheextinct** [comment]
![image](https://github.com/ValveSoftware/gamescope/assets/32158581/abc657b0-a575-4d27-a0f0-a46cc6260e95)

When using the mentioned workaround I still get terrible performance with gamescope. See the frametimes.

**Comment by sonic2kk** [comment]
Fixed with 7f3f82bd62ecc7284cd22b2bd3f933681723942b.

Also, the backend can now be selected as of 11cfc0d5c9785fec058856e68bb53f8cb4bd8f32. You can fall back to SDL with `--backend sdl`.
