### ISSUE TITLE
Counter Strike 2 starting with a black screen.

### ISSUE THREAD

**Issue by SomeDudeNamedAnthony** [ValveSoftware/gamescope#1214]
When trying to use gamescope with CS2, no matter what launch options I set. The splash screen will load but game itself will display a black screen.

During this I get the message `xwm: waylandres but no win` scrolling through the terminal. 
Tried to do some research on this and I couldn't find anything relating to CS2 and gamescope.
Trying the same thing on X11 results in the same outcome.

[Here is the log file](https://gist.github.com/SomeDudeNamedAnthony/f79963fca96bb3a1c322952eedbc63d8)

System Information:
```
Operating System: openSUSE Tumbleweed 20240321
KDE Plasma Version: 6.0.2
KDE Frameworks Version: 6.0.0
Qt Version: 6.6.2
Kernel Version: 6.8.1-1-default (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 1700X Eight-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 6700 XT
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: B450 AORUS PRO WIFI
```

[More system info can be found here](https://gist.github.com/SomeDudeNamedAnthony/f79963fca96bb3a1c322952eedbc63d8)

*Links*:
https://gist.github.com/SomeDudeNamedAnthony/f79963fca96bb3a1c322952eedbc63d8

**Comment by sharkautarch** [comment]
@SomeDudeNamedAnthony 
Looks like steam overlay is enabled for the game
Try seeing if disabling it does anything

**Comment by SomeDudeNamedAnthony** [comment]
Thank you for responding but unfortunately this didn't fix the issue.

**Comment by SomeDudeNamedAnthony** [comment]
I closed this issue as the problem was fixed with the `--steam` flag.
