### ISSUE TITLE
Refresh rate defined not fully respected in embedded mode

### ISSUE THREAD

**Issue by ranplayer** [ValveSoftware/gamescope#1216]
Hello,

I have a steam session defined on my system with the following content (`/usr/share/wayland-sessions/steam.desktop`):
```
[Desktop Entry]
Name=Steam
Comment=Steam session
Exec=gamescope -r 75 -e --hide-cursor-delay 5000 --xwayland-count 2 -- steam-runtime -steamos -pipewire-dmabuf -gamepadui %U
Type=Application
```

It seems in gamescope versions **>= 14.0** the refresh rate (75) is not fully respected in embedded mode. A lower value is assigned instead (e.g: 63). It used to work with version 3.13.19.  Am I missing a new parameter that should be defined as well ?

Specs:
- OS: Arch
- Kernel: 6.6.22
- GPU: RX 6700 XT (Mesa 24.0.3)

Let me know if more information is needed.

**Comment by MorrowxD** [comment]
I agree, I can't get work 165HZ mode, only 60hz is respected.

Im on fedora 40, rx 6800 xt Mesa 24

**Comment by ranplayer** [comment]
It seems to be working fine now for version `3.15.13`. Tested with mesa 24.2.5 and kernel 6.6.57

**Comment by kisak-valve** [comment]
Closing per the last comment.
