### ISSUE TITLE
--mouse-sensitivity isn't applying on latest version

### ISSUE THREAD

**Issue by Mato1111** [ValveSoftware/gamescope#1241]
Recently updated to 3.14.3 on Arch Linux, which stopped -s or --mouse-sensitivity from applying.
I usually have it at 0.5, but it was behaving like it was set to 1 (or just not applied). The movement also feels laggy/stuttery.
The issue does't occur after downgrading to 3.14.2.

**Comment by d07434b2c08f** [comment]
I'm having a possibly related issue with 3.14.3, where mouse input is not recognized at all when a game has been upscaled by gamescope without also using `--force-grab-cursor`. But if I do enable `--force-grab-cursor`, then I have this same issue with the mouse movement being extremely laggy. Downgrading to 3.14.2 fixes both issues for me.

**Comment by Mato1111** [comment]
I am also applying --force-grab-cursor

**Comment by Gibitwit** [comment]
Version 3.14.11-4 on Nobara Linux.  --mouse-sensitivity does not function.  However it does cause the output resolution to be scaled, despite no scalling functions being utilized.

I was hoping to use this to dial in my mouse senstivity for problematic games like Shadow Warrior 3 and Orcs must Die which have a minimum cap that is far too high or insufficient sensivitiy granularity.

**Comment by Joshua-Ashton** [comment]
Can you please test master? I did a fix for this a little while ago

**Comment by Gibitwit** [comment]
I am not sure how to do that, or what you mean by master.  Do you mean to download the code here and build it myself?  There is a newer package in the Nobara repositories for the coming update to Nobara 40, gamescope version 3.14.18.  Do I try using that build?

Do I need to remove the current installed version?
