### ISSUE TITLE
Repeated gamescope session crashes on Deck

### ISSUE THREAD

**Issue by Terrance** [ValveSoftware/gamescope#1243]
(Apologies if this isn't the right place to report -- I'm here based on the error logs I've found so far.)

I'm seeing various games (in particular, both native Linux games and Windows games running under Proton) crashing on the Steam Deck after up to 15 minutes or so, because `gamescope-wl` appears to abort and takes the session down with it.

Visually, the active game would freeze (with sound stuck in a loop) for about 5-10 seconds, after which the screen flickers off and on, then off again while Steam restarts.  It is consistently repeatable, having tried a few times today to complete a round of a game but for it to crash towards the end each time...

So far I've found the following other symptoms in the systemd journal:

```
gamescope: ../src/rendervulkan.cpp:1252: void CVulkanDevice::wait(uint64_t, bool): Assertion `0' failed.
```

```
Stack trace of thread 2123:
#0  0x00007f09c39b226c n/a (libc.so.6 + 0x8926c)
#1  0x00007f09c3962a08 raise (libc.so.6 + 0x39a08)
#2  0x00007f09c394b538 abort (libc.so.6 + 0x22538)
#3  0x00007f09c394b45c n/a (libc.so.6 + 0x2245c)
#4  0x00007f09c395b3d6 __assert_fail (libc.so.6 + 0x323d6)
#5  0x0000546a4ae1fcf7 n/a (gamescope + 0x7fcf7)
#6  0x0000546a4ae2902a n/a (gamescope + 0x8902a)
#7  0x0000546a4adf88c0 n/a (gamescope + 0x588c0)
#8  0x0000546a4adfab5f n/a (gamescope + 0x5ab5f)
#9  0x0000546a4ae15c69 n/a (gamescope + 0x75c69)
#10 0x00007f09c3ce1943 execute_native_thread_routine (libstdc++.so.6 + 0xe1943)
#11 0x00007f09c39b044b n/a (libc.so.6 + 0x8744b)
#12 0x00007f09c3a33e40 n/a (libc.so.6 + 0x10ae40)
```

I had the same kind of crashes about a month ago, but they stopped happening a few days later, possibly as a result of a system update, and the journal doesn't go back far enough to check for similar logs.

<details>
<summary> System Information</summary>

#### Computer Information:
Manufacturer: Valve
Model: Jupiter
Form Factor: Laptop
No Touch Input Detected

#### Processor Information:
CPU Vendor: AuthenticAMD
CPU Brand: AMD Custom APU 0405
CPU Family: 0x17
CPU Model: 0x90
CPU Stepping: 0x2
CPU Type: 0x0
Speed: 2800 MHz
8 logical processors
4 physical processors
Hyper-threading: Supported
FCMOV: Supported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Supported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Supported
AVX2: Supported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Supported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported

#### Operating System Version:
"SteamOS Holo" (64 bit)
Kernel Name: Linux
Kernel Version: 6.1.52-valve16-1-neptune-61
X Server Vendor: The X.Org Foundation
X Server Release: 12101008
X Window Manager: KWin
Steam Runtime Version: steam-runtime_0.20240304.79797

#### Video Card:
Driver: AMD AMD Custom GPU 0405 (vangogh, LLVM 15.0.7, DRM 3.54, 6.1.52-valve16-1-neptune-61)
Driver Version: 4.6 (Compatibility Profile) Mesa 23.1.3 (git-87ebaf765d)
OpenGL Version: 4.6
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID: 0x1002
DeviceID: 0x163f
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 800 x 1280
Desktop Resolution: 1280 x 800
Primary Display Size: 2.36" x 2.36" (3.31" diag), 6.0cm x 6.0cm (8.4cm diag)
Primary VRAM: 1024 MB

#### Sound card:
Audio device: ATI R6xx HDMI

#### Memory:
RAM: 14814 Mb

#### VR Hardware:
VR Headset: None detected

#### Miscellaneous:
UI Language: English
LANG: en_GB.UTF-8
Total Hard Disk Space Available: 229340 MB
Largest Free Hard Disk Block: 4855 MB

#### Storage:
Number of SSDs: 1
SSD sizes: 256G
Number of HDDs: 0
Number of removable drives: 0
</details>

[runtime-system-information.json](https://github.com/ValveSoftware/gamescope/files/14972112/runtime-system-information.json)

```shell
$ pacman -Q gamescope
gamescope 3.13.16.8-1
```

**Comment by Joshua-Ashton** [comment]
This is the result of a GPU hang -- not anything to do with Gamescope crashing

**Comment by Terrance** [comment]
Noted -- just found https://github.com/ValveSoftware/SteamOS/issues/1312 which appears to be what I'm seeing here.
