### ISSUE TITLE
Invisible mouse cursor on Steam Deck under the 20240417.1000 Main channel OS release with Gamescope 3.14.4

### ISSUE THREAD

**Issue by JDGBOLT** [ValveSoftware/gamescope#1255]
There is a regression that was introduced into gamescope a while ago that causes the mouse cursor not to display when moving around the mouse when in SteamOS that is still present in the current April 16th client as well as the 20240417.1000 main channel OS release. I bisected gamescope earlier today with regards to the problem and it looks like it was introduced with this commit https://github.com/ValveSoftware/gamescope/commit/6394fbcdb54f4de9fd767a134c5f522f278c1361 . It appears some commits were made to try to fix any cursor functionality, but that does not appear to have made any effect on the deck itself.

At least on my Deck Oled, it affects both moving the mouse in the main steam client, where you can see things getting highlighted by an invisible cursor, and also within a game or other application running, so it appears to be universal. As far as specifically what is going on that is preventing the code to work to show/hide the cursor as it did previously, I am not too sure, but just thought I would report the issue.

**Comment by Joshua-Ashton** [comment]
Hellope,

This is because the public version of Steam doesn't use the Gamescope input stuff yet. Should hopefully be fixed soon

**Comment by omfgnuts** [comment]
Same here

**Comment by JDGBOLT** [comment]
I can confirm that as of Gamescope 3.14.6 which has been shipped on the steamos main channel the cursor issues appear to be fixed.
