### ISSUE TITLE
Gamescope doesn't respect keyboard layout settings and keyboard state under X11 environment but fine on Wayland

### ISSUE THREAD

**Issue by MusaSSH** [ValveSoftware/gamescope#1261]
CachyOS, KDE Plasma 6, gamescope 3.14.3

gamescope that run in an X11 desktop environment doesn't respect keyboard layout and uses US layout. It also doesn't get keyboard state from the host. When the host has num lock on, so I can use numbers and the indicator on the keyboard is on it doesn't work in the game that run by gamescope. Pressing num lock when inside the game, turns off the indicator, disables the number keys on host but enables them in the game. No such problems happening on Wayland.

**Comment by kisak-valve** [comment]
Hello @MusaSSH, this issue is already being tracked at #203 and #969. Closing as a duplicate.
