### ISSUE TITLE
Epic Battle Fantasy 5 (432350) visually stuck only on OLED Deck Game Mode

### ISSUE THREAD

**Issue by waspennator** [ValveSoftware/gamescope#1262]
After further testing, figured I'd post about the issue here too since it only seems to happen on oled decks and specifically in game mode.

For some reason, the game will get visually stuck if you launch it on an oled deck in game mode, this game renders fine in desktop mode and LCD Decks do not suffer from this issue.

On OLED in game mode
![309198706-2b59b062-5515-4dc4-8103-f2ffe8789474](https://github.com/ValveSoftware/gamescope/assets/78768499/3e15e43c-c2b8-4318-a937-8623ed72979e)
[steam-432350.log.txt](https://github.com/ValveSoftware/gamescope/files/15069556/steam-432350.log.txt)

On LCD (works on desktop and game mode) or on OLED in desktop mode
![309199098-eb998cea-0f88-4464-a070-a34496cbb603](https://github.com/ValveSoftware/gamescope/assets/78768499/7822e4c8-c346-4ce2-b275-fb8267e1326b)
[steam-432350.log.txt](https://github.com/ValveSoftware/gamescope/files/15069565/steam-432350.log.txt)

**Comment by kisak-valve** [comment]
Duplicate of https://github.com/ValveSoftware/SteamOS/issues/1403

**Comment by waspennator** [comment]
Issue has been resolved as of latest proton experimental update and now renders on my oled deck in game mode.
