### ISSUE TITLE
Cookie clicker (1454400) visually stuck on splash screen on OLED Deck Game Mode 

### ISSUE THREAD

**Issue by waspennator** [ValveSoftware/gamescope#1263]
Even if I already reported it on the steamos github, figured I should report it here too since it's another oled gamescope issue.

Game is currently marked as deck verified, however this game only works on lcd decks, on oled decks in game mode it will get visually stuck before the language selection screen. You can technically click around to get past it, but it takes longer to transition over to gameplay in game mode and the sound effects are weirdly pitched until you click the cookie once. Issues are non existent on LCD Decks and on desktop mode with OLED Decks.

OLED
![309203298-39358b89-dbcd-4e80-8bac-33061e561a40](https://github.com/ValveSoftware/gamescope/assets/78768499/1d372c32-c965-4233-aea4-02f58ccbc3ea)
[steam-1454400.log.txt](https://github.com/ValveSoftware/gamescope/files/15069683/steam-1454400.log.txt)

LCD and Desktop mode OLED 
![download](https://github.com/ValveSoftware/gamescope/assets/78768499/f8fe0156-71af-4537-8c06-c62d9ad0c0e5)
[steam-1454400.log.txt](https://github.com/ValveSoftware/gamescope/files/15069696/steam-1454400.log.txt)

**Comment by kisak-valve** [comment]
Duplicate of https://github.com/ValveSoftware/SteamOS/issues/1404

**Comment by waspennator** [comment]
Issue has been fixed up as of latest proton Experimental build, it no longer gets visually stuck before the language selection screen on my oled deck in game mode.
