### ISSUE TITLE
Crashes in Counter Strike 2

### ISSUE THREAD

**Issue by DavutHaxor** [ValveSoftware/gamescope#1297]
When using gamescope in counter strike 2 and clicking any of the menu elements, it crashes. I use:
`DRI_PRIME=1 gamemoderun obs-gamecapture env OBS_VKCAPTURE=1 gamescope -f -w 1440 -h 1080 -W 1920 -H 1080 -S stretch %command% -fullscreen -high -novid -nojoy`
start option on Arch Linux.  When i remove gamescope from options, game works fine

System Diagnostics from steam client: https://gist.github.com/DavutHaxor/8091f8ab3ac619145cd3d1ef30a2c4c2

**Comment by DavutHaxor** [comment]
Seems its just Counter Strike 2 crashing

**Comment by kisak-valve** [comment]
Likely from https://gitlab.freedesktop.org/drm/amd/-/issues/3343.
