### ISSUE TITLE
Since libliftoff update, Gamescope is always compositing

### ISSUE THREAD

**Issue by Joshua-Ashton** [ValveSoftware/gamescope#1298]
Seems totally busted.

**Comment by sharkautarch** [comment]
> Seems totally busted.

I know w/ compositing in `steamcompmgr.cpp` `paint_all(bool)` does either async or synchronous composition…
Is it currently only doing async or synchronous composition?

Also, maybe try building gamescope w/ `-Dsanitizers=address,undefined`
(Make sure to add `LD_PRELOAD=/usr/lib/libasan.so` when running gamescope)
To see if that shows any bugs in libliftoff?

**Comment by Joshua-Ashton** [comment]
No, it's nothing to do with that.

https://gitlab.freedesktop.org/emersion/libliftoff/-/issues/78
