### ISSUE TITLE
[Feature] gamescope starts with last used audio output

### ISSUE THREAD

**Issue by HiveHivemind** [ValveSoftware/gamescope#1306]
Gamescope will not consider the system's default audio/sink setup or the last selected one, but it seems to pick the latest initialized interface (i.e. if playing with a DualSense controller via USB it will always default to it). 
Although this helps on the user experience of connecting a plug n play audio and already start using it automatically, we should be able to remember the last used audio for docked systems and, _then_, any audio devices connected thereafter are picked up automatically for audio output.

Use case:

1. Have Steam Deck's dock connected to an AVR via HDMI for couch gaming and an USB DAC for streaming
2. Although the USB DAC is the latest interface read on boot, audio out is still the AVR as he set so in gamescope in his last couch gaming session. The USB DAC is defaulted only on Desktop Mode instead (set using KDE's Audio Settings/Pipewire)

Such behavior mimics current gen consoles behavior (PS5/Series X), as well as Windows and KDE.

**Comment by Joshua-Ashton** [comment]
Gamescope actually does nothing at all with audio. I want Pipewire namespacey stuff, but it doesn't exist yet.
