### ISSUE TITLE
Gamescope doesn't grab mouse emulated through steam input

### ISSUE THREAD

**Issue by IDeathByte** [ValveSoftware/gamescope#1307]
I use steam controller. Possible to dualshock/dualsense affected too
For avoid issue with didn't worked steam overlay/input, i launch gamescope in separate window with parameters:
gamescope -w 2560 -h 1080 --expose-wayland --
Also tried --force-grab-cursor
Game launch options like DISPLAY=:2 %command%

Problem is emulated mouse didn't captured by gamescope - no input in game, but i see activity of invisible cursor on my second screen, an in times, on steam in background (it lightning some menu buttons on hover). Symptoms on trackpad and gyro in mouse mode

Capture of my desktop mouse works as well. Trackpads in joystick mode also works

DE: Plasma 6.0.4 (Wayland)
Gamescope compiled from master branch (37577dc89f303f5936b763637ffa1ebd377a4a29), nested mode

**Comment by matte-schwartz** [comment]
If you look at your gamescope logs, do you see any logging that indicates either of these two things?

`[gamescope] [Error] wlserver: Gamescope built without libei, XTEST will not be available!`

or

` wlserver: Successfully initialized libei for input emulation!`

I've found that on the Steam Deck's touchpads, you will also get an invisible cursor if you compile gamescope without `-Dinput_emulation=enabled` and thus see that XTEST error logging. this sounds like it may be the same issue. This issue can happen on SteamOS as well, but gamescope gets built with libei enabled in the steamos-cloud CI unlike the GitHub gamescope CI which still has `-Dinput_emulation=disabled`

**Comment by IDeathByte** [comment]
> I've found that on the Steam Deck's touchpads, you will also get an invisible cursor if you compile gamescope without `-Dinput_emulation=enabled` and thus see that XTEST error logging. this sounds like it may be the same issue. This issue can happen on SteamOS as well, but gamescope gets built with libei enabled in the steamos-cloud CI unlike the GitHub gamescope CI which still has `-Dinput_emulation=disabled`

Im not sure what fixed this issue for me, but now i see request for remote mouse connection, when i launch gamescope and connect controller.
I think, for me helped [krdp](https://github.com/KDE/krdp) package installation (or it just coincidence)

**Comment by kisak-valve** [comment]
Closing per the last comment.
