### ISSUE TITLE
Input errors on Main branch of SteamOS

### ISSUE THREAD

**Issue by Noodlez1232** [ValveSoftware/gamescope#1308]
Input becomes behind by "input units" on the Steamdeck OLED model. This behavior is as if the inputs are getting queued, but not actually being pushed out until other inputs occur. I have a video attached of me playing VBAm (a GBA emulator) that exhibits this behavior, since I think this error is better described by video.

This occurs on the Main branch of SteamOS, but not on Beta or Stable (Gamescope package 3.14.14-1)

[Here's a video demonstrating the problem.](https://github.com/ValveSoftware/gamescope/assets/12480453/64c28a9f-8298-443d-92b4-5cae67a58736) It is a little bit edited (quickly), since it needed to fit into 10MB for GitHub to embed it.

Games tested:

- Geometry Dash (exhibits behavior)
- Bejeweled 2 (Does not exhibit behavior)
- Bejeweled 3 (Exhibits behavior)
- VBAm (from Flatpak, exhibits behavior)
- Besiege (Exhibits behavior)

**Comment by matte-schwartz** [comment]
for what it’s worth, I think this is a known issue since I also ran into something similar. Looks like it is being worked on: https://github.com/ValveSoftware/gamescope/commit/95b6805818158584c1abedc6f99f6edab14799e2

hasn’t been a tagged release that includes that commit yet.

**Comment by Noodlez1232** [comment]
Ahh gotcha thank you! If it ever gets tagged in a release, I'll test it again, and close it if it's fixed as well.

**Comment by matte-schwartz** [comment]
been testing for a few hours now and it seems to be fixed in [3.14.16](https://github.com/ValveSoftware/gamescope/releases/tag/3.14.16), which means it should hopefully make it into the next SteamOS Preview/Main update.
