### ISSUE TITLE
gamescope does not works

### ISSUE THREAD

**Issue by XxRiKxX** [ValveSoftware/gamescope#1315]
gamescope -W 1920 -H 1080 -w 1920 -h 1080 -- gamemoderun wine GhostOfTsushima.exe       
No CAP_SYS_NICE, falling back to regular-priority compute and threads.
Performance will be affected.
ATTENTION: default value of option vk_khr_present_wait overridden by environment.
vulkan: selecting physical device 'AMD Radeon RX 570 Series (RADV POLARIS10)': queue family 1 (general queue family 0)
vulkan: physical device does not support DRM format modifiers
wlserver: [backend/headless/backend.c:67] Creating headless backend
xdg_backend: Seat name: seat0
vulkan: supported DRM formats for sampling usage:
gamescope: ../gamescope/src/wayland_backend.cpp:1276: virtual void gamescope::CWaylandBackend::GetPreferredOutputFormat(VkFormat*, VkFormat*) const: Assertion `u8BitFormat != VK_FORMAT_UNDEFINED' failed.
zsh: IOT instruction (core dumped)  gamescope -W 1920 -H 1080 -w 1920 -h 1080 -- gamemoderun wine

**Comment by kisak-valve** [comment]
Hello @XxRiKxX, this issue is already being tracked at #1258. Closing as a duplicate.
