### ISSUE TITLE
[bisected] Framerate spikes/screen freezing when moving mouse cursor at high pooling rate

### ISSUE THREAD

**Issue by VeilSilence** [ValveSoftware/gamescope#1316]
Greetings

- NixOS 24.05
- Plasma 6 wayland session.
- Nvidia rtx 3090. Hardware cursors enabled.
- 550.78 driver.
- Gamescope 6f185c7f54d4d259d739e0872132d0aabafd296e version

When my mouse is set to an 8000Hz polling rate, every time I see the cursor in-game and move it around the screen, the game basically freezes for about 3-5 seconds (or just straight up crashes) until I stop moving my mouse. At a 1000Hz polling rate, the game no longer freezes, but there is a noticeable framerate/performance drop until I stop moving my mouse. 

I bisected the issue to this commit: febcf34de9993151261047007867bd385de28e57. I reverted this commit and built the git version of Gamescope, and it indeed fixed the performance/freezing issue, but I can't click anything in the game now. 
Probably commit 7c4438a2de94ddc9a98483c3557d5f6449e09099 is the issue, but I couldn't revert this commit and build the Gamescope git version to test it.

This issue probably related to mine also: https://github.com/ValveSoftware/gamescope/issues/1279

**Comment by sharkautarch** [comment]
> Probably commit https://github.com/ValveSoftware/gamescope/commit/7c4438a2de94ddc9a98483c3557d5f6449e09099 is the issue


I built gamescope @  https://github.com/ValveSoftware/gamescope/commit/7c4438a2de94ddc9a98483c3557d5f6449e09099 and then built gamescope from the commit before it.
And then used ddisasm to disassemble the binaries so I could compare them (with difftastic)
Haven't finished looking thru all the dissassembly, but so far, I can see that just by comparing the assembly for `gamescope::CWaylandPlane::Present`, it seems that commit  https://github.com/ValveSoftware/gamescope/commit/7c4438a2de94ddc9a98483c3557d5f6449e09099 has about 6 more mov instructions... 
nothing conclusive so far, tho maybe I'll need to do something in wayland_backend.cpp similar to what I did in https://github.com/ValveSoftware/gamescope/pull/1287
I'll have to look more into it...

**Comment by VeilSilence** [comment]
Oh well, I must apologize for wasting your time. 
Problem is still here, I just somehow bisected to wrong commit sadly...
After verifying at least 3 times and even record on video everything, my result of investigations:

 Git version gamescope freezing showcase

<details><summary>CPU spikes on cursor move</summary>
<p>

https://github.com/ValveSoftware/gamescope/assets/132572320/5bad77c9-db62-4fbe-a789-49156e0d4026

</p>
</details> 


Gamescope ee02018aeb0494171fc2f9625dd5567d9237f1b1 commit:
<details><summary>Video showcase. Wrong cursor position, but no framerate spikes. Cursor can interact with game</summary>
<p>


https://github.com/ValveSoftware/gamescope/assets/132572320/e05726fd-1ad0-423e-9e0f-80f265c5441a

</p>
</details> 


Commit 252a189d07d7eb95ecdb5ff0509718c5d18709da. This is where this problem appears:

<details><summary>Wrong cursor position and frame spikes. Cursor can interact with game</summary>
<p>


https://github.com/ValveSoftware/gamescope/assets/132572320/adffbdc9-bf2b-4864-a3b3-803d04f79862



</p>
</details> 

I was one off of actually problematic commit. In commit 2898ccef1dea7c89248e67bd8049d020eac5f321, my cursor can't interact with game, so framerate was unaffected by this bug...

In the end, I made patch that revert few things from 252a189d07d7eb95ecdb5ff0509718c5d18709da commit.
My result on 6f185c7f54d4d259d739e0872132d0aabafd296e commit + patch:

<details><summary>Final result. Happy end.</summary>
<p>

https://github.com/ValveSoftware/gamescope/assets/132572320/e138b20b-6628-4235-8c06-2e4f693851af


</p>
</details> 


<details><summary>Patch itself</summary>
<p>

```c++
From d0f76adf039f094ea14a2a2b9fe5fc103ab6f968 Mon Sep 17 00:00:00 2001
From: Veil <BoneFeaR@proton.me>
Date: Sun, 19 May 2024 20:54:31 +0300
Subject: [PATCH] Attempt to fix mouse stutters.

---
 src/wayland_backend.cpp | 11 +++++++----
 1 file changed, 7 insertions(+), 4 deletions(-)

diff --git a/src/wayland_backend.cpp b/src/wayland_backend.cpp
index ddc6c10..fffdb98 100644
--- a/src/wayland_backend.cpp
+++ b/src/wayland_backend.cpp
@@ -1927,13 +1927,13 @@ namespace gamescope
     void CWaylandBackend::Wayland_Keyboard_Enter( wl_keyboard *pKeyboard, uint32_t uSerial, wl_surface *pSurface, wl_array *pKeys )
     {
         m_bKeyboardEntered = true;
-
+
         UpdateCursor();
     }
     void CWaylandBackend::Wayland_Keyboard_Leave( wl_keyboard *pKeyboard, uint32_t uSerial, wl_surface *pSurface )
     {
         m_bKeyboardEntered = false;
-
+
         UpdateCursor();
     }

@@ -2309,8 +2309,8 @@ namespace gamescope
     void CWaylandInputThread::Wayland_Pointer_Frame( wl_pointer *pPointer )
     {
         defer( m_uAxisSource = WL_POINTER_AXIS_SOURCE_WHEEL );
-        double x = m_flScrollAccum[0];
-        double y = m_flScrollAccum[1];
+        float x = m_flScrollAccum[0];
+        float y = m_flScrollAccum[1];
         m_flScrollAccum[0] = 0.0;
         m_flScrollAccum[1] = 0.0;

@@ -2320,6 +2320,9 @@ namespace gamescope
         if ( m_uAxisSource != WL_POINTER_AXIS_SOURCE_WHEEL )
             return;

+        if ( x == 0 && y == 0 )
+        return;
+
         wlserver_lock();
         wlserver_mousewheel( x, y, ++m_uFakeTimestamp );
         wlserver_unlock();
--
2.44.0


``` 

</p>
</details> 

I'm new to all this git stuff, and also not code developer, so apologize once again for wrong initial report. Hope this helps.

**Comment by Joshua-Ashton** [comment]
Does latest master fix the issue for you?

**Comment by VeilSilence** [comment]
> Does latest master fix the issue for you?

Confirm, problem solved.
Thanks.
