### ISSUE TITLE
Gamescope hangs with --backend sdl

### ISSUE THREAD

**Issue by grimshins** [ValveSoftware/gamescope#1332]
On tag 3.14.18, launching via `gamescope --backend sdl -- vkcube` will frequently hang on `vulkan: Creating Gamescope nested swapchain with format 64 and colorspace 0`. Launching via `env -u WAYLAND_DISPLAY gamescope -- vkcube` does not exhibit this behavior. Additionally, using `--backend sdl` does not respect `--display-index`, while `env -u WAYLAND_DISPLAY` does. Testing environment: Ubuntu 24.04, Wayland session

**Comment by HanabishiRecca** [comment]
I can't reproduce the hang. But I guess it happens because of

https://github.com/ValveSoftware/gamescope/blob/3805bd7f7e3edef4cc8ad54ce3caedfbbfbbc6ed/src/main.cpp#L795-L804

Could you try to test it with this patch?

```diff
diff --git a/src/main.cpp b/src/main.cpp
index 01dd8ca..f6224f4 100644
--- a/src/main.cpp
+++ b/src/main.cpp
@@ -792,7 +792,7 @@ int main(int argc, char **argv)
 			eCurrentBackend = gamescope::GamescopeBackend::DRM;
 	}
 
-	if ( g_pOriginalWaylandDisplay != NULL )
+	if ( eCurrentBackend == gamescope::GamescopeBackend::Wayland && g_pOriginalWaylandDisplay != NULL )
 	{
         if (CheckWaylandPresentationTime())
         {

```

**Comment by Joshua-Ashton** [comment]
That check is intended for the SDL backend, as it ks the only one that uses Vulkan presnetation.

If it hangs it's likely s compositor bug? Works here on KDE Plasma...

**Comment by HanabishiRecca** [comment]
I suggested it to pinpoint the problem.
But yeah, SDL2 should work fine with Wayland videodriver. Probably a compositor bug.
And I don't have a second monitor to test `--display-index` right now.

**Comment by grimshins** [comment]
I re-tested this after building 3.14.24 with `-Dforce_fallback_for=vkroots,wlroots,libliftoff` as per #1414 and that seems to have resolved the issue. `--display-index` still only works in X11 or with `env -u WAYLAND_DISPLAY` but I'm assuming that this is expected behavior.
