### ISSUE TITLE
Gamescope/libliftoff regression causes artifacts when toggling the Steam Performance Overlay on and off

### ISSUE THREAD

**Issue by matte-schwartz** [ValveSoftware/gamescope#1343]
**Summary** 

I have been able to reliably reproduce artifacting when toggling the Steam performance overlay on and off within Gamescope-session across multiple Deck devices and distros. I have personally been able to repro this now on both a Steam Deck LCD and Steam Deck OLED running SteamOS Main and SteamOS Preview along with Fedora 39 and 40 (no dual booting involved). 

As best as I could bisect, one of the two libliftoff commits in gamescope, https://github.com/ValveSoftware/gamescope/commit/93a90d19a19ea414a165e2f3297c76d9dc9dc062 or https://github.com/ValveSoftware/gamescope/commit/a9199c2097ffc9d7f96ccf1eb8a04004b1f643de, is the cause of the regression

Specifically within libliftoff, by reverting commits one by one within the submodule and testing gamescope builds, I have identified three commits that could be causing the issue
https://gitlab.freedesktop.org/emersion/libliftoff/-/commit/35c06e8995f2eeb9e7fde4bf225fe04fc96cb7ee
https://gitlab.freedesktop.org/emersion/libliftoff/-/commit/c857632cfd34a6454e5f4ce496fb5a62009ccb43
https://gitlab.freedesktop.org/emersion/libliftoff/-/commit/ec867357631605347acefb5f2ccf76914f8537c1

_Note: I have also filed an issue within libliftoff for this as well, as I was unsure where to take this issue report... The linked issue can be found here: https://gitlab.freedesktop.org/emersion/libliftoff/-/issues/81. I can close this if it would be better to keep this limited to the gamescope tracker_

**To reproduce:**

1. From the steam library home page, press A to enter a game's entry
2. From this game entry, now press B to exit back into your library home page
3. Toggle the steam performance overlay from Off -> any of the overlay presets
4. Toggle the steam performance overlay back to Off
5. Repeat 3 and 4 several times, and you should be able to see artifacting as recorded here:

**Artifact Clips**

OLED Deck, SteamOS Main (Gamescope 3.14.18):

https://github.com/ValveSoftware/gamescope/assets/136293710/5e89213b-4b5d-4e09-8b5d-89c1f9c779d3

LCD Deck, SteamOS Preview (Gamescope 3.14.16):

https://github.com/ValveSoftware/gamescope/assets/136293710/38c2830a-7164-45eb-9c07-3220e916e10c

OLED Deck, Fedora 40 (Gamescope 3.14.18 - self compiled):

https://github.com/ValveSoftware/gamescope/assets/136293710/72588743-2955-463b-99b2-b40cb9c2a745

The strangest part is how it happens even when the overlay isn't set to visible over the Steam UI, but that's not very relevant to this specific report.

**How I fixed it (for now)**

1. Revert to parent of first potential bad commit in libliftoff

```
cd subprojects/libliftoff
git checkout c63676eda7d242684bd226ce5c3f94d3728d2f18
cd ../../
```
2. Apply patch to revert https://github.com/ValveSoftware/gamescope/commit/a9199c2097ffc9d7f96ccf1eb8a04004b1f643de and part of https://github.com/ValveSoftware/gamescope/commit/bc064588cdf63252bebdbd3abf7e7c688811eb6f which uses `&lo_options` from the libliftoff update
```
From b453e6457b4cd35c867618b4f68346373b282f29 Mon Sep 17 00:00:00 2001
From: Matthew Schwartz <njtransit215@gmail.com>
Date: Sun, 26 May 2024 19:42:34 -0700
Subject: [PATCH 1/2] Revert "set timeout_ns to max"

This reverts commit a9199c2097ffc9d7f96ccf1eb8a04004b1f643de.
---
 src/drm.cpp | 8 ++------
 1 file changed, 2 insertions(+), 6 deletions(-)

diff --git a/src/drm.cpp b/src/drm.cpp
index 0b73ebc..e1464a7 100644
--- a/src/drm.cpp
+++ b/src/drm.cpp
@@ -1172,7 +1172,7 @@ bool init_drm(struct drm_t *drm, int width, int height, int refresh)
 		return false;
 	if ( liftoff_device_register_all_planes( drm->lo_device ) < 0 )
 		return false;
-	
+
 	drm_log.infof("Connectors:");
 	for ( auto &iter : drm->connectors )
 	{
@@ -2481,11 +2481,7 @@ drm_prepare_liftoff( struct drm_t *drm, const struct FrameInfo_t *frameInfo, boo
 		}
 	}
 
-	struct liftoff_output_apply_options lo_options = {
-		.timeout_ns = std::numeric_limits<int64_t>::max()
-	};
-
-	int ret = liftoff_output_apply( drm->lo_output, drm->req, drm->flags, &lo_options);
+	int ret = liftoff_output_apply( drm->lo_output, drm->req, drm->flags );
 
 	// The NVIDIA 555 series drivers started advertising DRM_CAP_SYNCOBJ, but do
 	// not support IN_FENCE_FD. However, there is no way to hide the IN_FENCE_FD
-- 
2.45.1

From 1b52c18255d7b832d632f6d5975c48dd56c21d11 Mon Sep 17 00:00:00 2001
From: Matthew Schwartz <njtransit215@gmail.com>
Date: Sun, 26 May 2024 19:43:43 -0700
Subject: [PATCH 2/2] hotfix: revert until libliftoff/gamescope issues are
 resolved

---
 src/drm.cpp            | 2 +-
 1 files changed, 1 insertions(+), 1 deletions(-)

diff --git a/src/drm.cpp b/src/drm.cpp
index e1464a7..0d2bd45 100644
--- a/src/drm.cpp
+++ b/src/drm.cpp
@@ -2499,7 +2499,7 @@ drm_prepare_liftoff( struct drm_t *drm, const struct FrameInfo_t *frameInfo, boo
 			liftoff_layer_set_property( drm->lo_layers[ i ], "IN_FENCE_FD", -1 );
 		}
 
-		ret = liftoff_output_apply( drm->lo_output, drm->req, drm->flags, &lo_options );
+		ret = liftoff_output_apply( drm->lo_output, drm->req, drm->flags );
 
 		if ( ret == 0 )
 		{
-- 
2.45.1
```
3. Install the build

**Build testing**

I have confirmed a gamescope build following the steps outlined above totally solves the artifacting on both devices. Here's a clip from my LCD Deck running SteamOS Preview and my OLED Deck running Fedora 40, both using the same gamescope build, with zero artifacting present:

Steam Deck LCD, SteamOS Preview, patched gamescope - from https://github.com/ValveSoftware/gamescope/commit/420eb91387a484fd7b1ea71449091f0480d9e538:

https://github.com/ValveSoftware/gamescope/assets/136293710/0572c859-42e9-4c39-b124-aad5b9b0c7b9

Steam Deck OLED, Fedora 40, patched gamescope - from https://github.com/ValveSoftware/gamescope/commit/420eb91387a484fd7b1ea71449091f0480d9e538:

https://github.com/ValveSoftware/gamescope/assets/136293710/a8655480-806b-42b0-a48e-5f05130cd286

**Comment by italoghost** [comment]
Experiencing this as well! Using gamescope package from Arch Linux repositories (version 3.14.16) on a gamescope session!

**Comment by KyleGospo** [comment]
Thirdeded, experiencing this on Fedora Silverblue 40

**Comment by matte-schwartz** [comment]
> Experiencing this as well! Using gamescope package from Arch Linux repositories (version 3.14.16) on a gamescope session!

Are you on a Steam Deck as well or are you experiencing this on another device? On my end I've only been able to replicate it on a Deck.

**Comment by italoghost** [comment]
I am on my Arch Linux desktop. It started to happen after the update to Mesa 24.1.

**Comment by RodoMa92** [comment]
Same on Fedora Kinoite 40 on my Deck LCD.

**Comment by matte-schwartz** [comment]
I've confirmed it happens on my ROG Ally too on latest upstream gamescope from master. My partial revert patch "fixes" this specific issue but causes washed out colors when toggling VRR/HDR so it's not a viable workaround. 

https://github.com/ValveSoftware/gamescope/assets/136293710/d9d36761-9a47-48a0-b8c5-aac6e3e48f6e

**Comment by matte-schwartz** [comment]
closing into new meta issue for clarity's sake
