### ISSUE TITLE
Wayland backend breaks some fullscreen child windows, including embedded steam, in nested gamescope on Wayland desktops

### ISSUE THREAD

**Issue by matte-schwartz** [ValveSoftware/gamescope#1356]
#### Your system information

* Steam client version (build number or date): 1716584667
* Distribution (e.g. Ubuntu): Fedora, Arch
* Opted into Steam client beta?: Yes
* Have you checked for system updates?: Yes
* Steam Logs: [steam-logs.tar.gz](https://github.com/user-attachments/files/15595732/steam-logs.tar.gz)

* GPU: AMD 7900XTX and Nvidia 4090 (separate rigs)

#### Please describe your issue in as much detail as possible:
After embedded Chromium was updated in early February, trying to use the Steam client within nested gamescope on Plasma 6 breaks `gamescope -f` functionality **only on Wayland**. For instance, `gamescope -e -f -- steam -gamepadui` gives a UI that looks like this where the taskbar still bleeds through and the window is not properly fullscreened. the game windows that it spawns are not properly fullscreened either:
![image](https://github.com/ValveSoftware/steam-for-linux/assets/136293710/a9108109-9a20-45a5-954b-b55d83894d35)

what's interesting is that the loading screen beforehand is fullscreened correctly as seen here:
![image](https://github.com/ValveSoftware/steam-for-linux/assets/136293710/73fbe4ad-2725-48f9-96a7-07a7b7998c09)

The only solution to the issue I have found is to switch my DE from Wayland to X11 which makes the same command work properly:
![image](https://github.com/ValveSoftware/steam-for-linux/assets/136293710/407d953b-b936-42e8-b63c-4ccb2eafde13)
or by downgrading to a Steam client from before February 2024. Both options are just bandaid solutions though.

#### Steps for reproducing this issue:

1. Switch to Wayland desktop and use an up-to-date steam client
2. Launch steam within gamescope `gamescope -e -f -- steam -gamepadui`
3. If it works the first time, quit and try step 2 again. It should start to glitch by now.

This happens on both AMD and NVIDIA cards of mine, so I'm inclined to say it's a Steam issue rather than a driver issue. 

Edit: throughout this whole process, using `gamescope -f` on things other than the Steam client does work properly the entire time fwiw

**Comment by kisak-valve** [comment]
Hello @matte-schwartz, this reads more like an issue between gamescope and kwin_wayland that should be evaluated by one of those projects before the Steam client, so I've transferred this issue report to the gamescope issue tracker. If they find a hint leaning towards a Steam client issue, then they can give me a ping requesting to transfer this issue back to the steam-for-linux issue tracker.

**Comment by matte-schwartz** [comment]
Thanks for the heads up @kisak-valve, wasn't sure where this belonged since I've only been able to change the problematic behavior by way of the Steam Client or desktop compositor instead of anything within Gamescope itself. I've tried back to gamescope 3.14.2 with no effect.

**Comment by matte-schwartz** [comment]
I've confirmed this also happens on Gnome/latest Mutter release

**Comment by matte-schwartz** [comment]
I've done more testing and it looks like it has the ability to affect Steam games launched with gamescope from the normal desktop mode on Wayland as well, but only around 50% of the time:

`gamescope -f -H 1440 -W 3440 -r 144 --adaptive-sync --hdr-enabled --hide-cursor-delay 3000 -- %command%` and trying to launch Ghost of Tsushima on Plasma 6 Wayland left me with the same issue:

![image](https://github.com/ValveSoftware/gamescope/assets/136293710/320927fd-ccff-4679-97b7-ff967e39ade3)

closing the game and trying the exact same command again without changing anything at all made it work:
![Screenshot_20240605_171737](https://github.com/ValveSoftware/gamescope/assets/136293710/1a859f00-26a7-4b8b-b247-661185a11ff4)

and now it seems to go back and forth every other launch.

**Comment by sharkautarch** [comment]
@matte-schwartz it looks like the latest commit joshua-ashton made to gamescope was one that fixed an issue w/ fractional scaling (https://github.com/ValveSoftware/gamescope/commit/09cb7b451d8825e597d15ab9d30e43aee8418670)

on your arch system, try installing the `gamescope-git` package from the AUR, and see if you still get the issue there

**Comment by matte-schwartz** [comment]
> on your arch system, try installing the `gamescope-git` package from the AUR, and see if you still get the issue there

Sorry, should've clarified that all my testing is with self-compiled versions that I built off https://github.com/ValveSoftware/gamescope/commit/09cb7b451d8825e597d15ab9d30e43aee8418670

**Comment by sharkautarch** [comment]
> > on your arch system, try installing the `gamescope-git` package from the AUR, and see if you still get the issue there
> 
> Sorry, should've clarified that all my testing (except past tagged releases which I install from the steamos package mirrors directly) is with self-compiled versions that I built off [09cb7b4](https://github.com/ValveSoftware/gamescope/commit/09cb7b451d8825e597d15ab9d30e43aee8418670)


cool
Does it work if you try running gamescope w/ `—backend=sdl`

**Comment by matte-schwartz** [comment]
> cool Does it work if you try running gamescope w/ `--backend=sdl`

yes, it does seem to work correctly with `gamescope -e -f -H 1440 -W 3440 --backend sdl -- steam -steamdeck -gamepadui -steamos3 -steampal` so perhaps it's limited to the wayland backend only

**Comment by Neubulae** [comment]
I have compiled mine with `gamescope-git` aur package, but the issue seems to persist. Did I do something wrong or that I have to manually set to latest head?

**Comment by matte-schwartz** [comment]
@Neubulae Not sure how the AUR package for gamescope-git works, but you should be able to double check with `cd src/gamescope` from the PKGBUILD base directory, and then making sure you fetch any updates with `git pull` and then `git checkout origin/master`, `cd ../..` and then `makepkg -efsi`. i have not been able to repro the issue anymore on my end with a manual local compile + install.

I'm also testing this on Plasma 6.1.3 if that matters

**Comment by Neubulae** [comment]
> @Neubulae Not sure how the AUR package for gamescope-git works, but you should be able to double check with `cd src/gamescope` from the PKGBUILD base directory, and then making sure you fetch any updates with `git pull` and then `git checkout origin/master`, `cd ../..` and then `makepkg -efsi`. i have not been able to repro the issue anymore on my end with a manual local compile + install.
> 
> I'm also testing this on Plasma 6.1.3 if that matters

I have seemingly mistaken this issue with https://github.com/ValveSoftware/gamescope/issues/1237 one, my bad.

**Comment by slagiewka** [comment]
Can confirm that it fixes a case where Ubisoft's launcher starts first and game wouldn't be full screen in the end. Thank you @CakeKing64!
