### ISSUE TITLE
[3.14.16] Gamescope doesn't switch focus to game window if it starts with Steam gamepad UI nesed inside

### ISSUE THREAD

**Issue by SysError99** [ValveSoftware/gamescope#1365]
Hardware: AMD Ryzen 5 2500U with AMD Radeon Vega 8 Graphics (VivoBook_ASUS Laptop X505ZA_X505ZA)
Software: 6.1.92-1-MANJARO with KDE Plasma 6.0.5 Wayland
Gamescope version: 3.14.16

Gamescope will not switch focus to any game window if Steam with gamepad UI is started inside Gamescope.

Steps to reproduce
1. Start Steam with `-gamepadui` option inside it.
```
gamescope -- steam -gamepadui
```
2. Launch any game.
3. In-game sound plays, but there's nothing on the screen but the gamepad UI in a black state.

**Comment by Zentropivity** [comment]
Can confirm the same issue on Gamescope version `3.14.22` and latest archlinux.

<details>
<summary>System details</summary>
<ul>
<li>OS: Arch Linux x86_64</li>
<li>Kernel: Linux 6.9.8-arch1-1</li>
<li>Display (LG TV SSCR2): 3840x2160 @ 120]</li>
<li>DE: KDE Plasma 6.1.2</li>
<li>WM: KWin (Wayland)</li>
<li>CPU: AMD Ryzen 7 5800X (16) @ 3.80 GHz</li>
<li>GPU: AMD Radeon RX 7900 XT/7900 XTX/79]</li>
</ul>
</details>

**Comment by Joshua-Ashton** [comment]
You need to launch with -e for Steam mode.
