### ISSUE TITLE
Do not bind wl_seat so many times

### ISSUE THREAD

**Issue by nonetrix** [ValveSoftware/gamescope#1366]
I am not a Wayland developer person, but recently Hyprland rewrote much of it's Wayland code. This broke Gamescope for a while and didn't allow it to have any mouse or keyboard input [issue here](https://github.com/hyprwm/Hyprland/issues/6159). Apparently this is somewhat the fault of Gamescope to some degree and Hyprland just wasn't supporting broken behavior, but it was fixed in [this commit](https://github.com/hyprwm/Hyprland/commit/6b6b02c27a21a6a4fe3d66937c709c32e21a9078) but I think it would be best to fix the broken behavior at the root and have this commit around for future broken apps and to just be in line with wlroots

Edit: apparently this is valid in Wayland spec, but might still be perhaps something that should be avoided?

**Comment by Joshua-Ashton** [comment]
We have a dedicated input thread... We bind a seat twice because of that.

You can tell why nobody wants to work with vaxry:
```
        // we will iterate over all bound wl_seat
        // resources here, because some idiotic apps (e.g. those based on smithay)
        // tend to bind wl_seat twice.
        // I can't be arsed to actually pass all events to all seat resources, so we will
        // only pass enter and leave.
        // If you have an issue with that, fix your app.
```

Like jeez, having a dedicated input thread on another queue is a good thing, it's not idiotic.

Calling us "legitmately braindead" because of your bug is fucking stupid.

**Comment by Joshua-Ashton** [comment]
We have a dedicated input thread... We bind a seat twice because of that.

Like jeez, having a dedicated input thread on another queue is a good thing, it's not idiotic.

Calling me "legitmately braindead" because of your bug is simply just plain rude.

**Comment by nonetrix** [comment]
I was not the one who wrote the commit message I agree it's a bit harsh too just reporting issues in hope they can be fixed my bad

**Comment by Joshua-Ashton** [comment]
No worries, not directed at you. I went into some more technical details here: https://github.com/hyprwm/Hyprland/issues/6159#issuecomment-2166965622
