### ISSUE TITLE
"Frame time" degrade after some time

### ISSUE THREAD

**Issue by VeilSilence** [ValveSoftware/gamescope#1367]
Greetings.

- Nvidia rtx 3090. 
- Driver version 555.52.04. It also happened on 550 driver.
- Kernel: Linux Nix 6.9.3-xanmod1 
- KDE 6.0.5 wayland session.
- NixOS 24.11, but this problem was on Arch Linux also for me.
-  Gamescope commit 09cb7b451d8825e597d15ab9d30e43aee8418670 

After some time playing, my game performance drops drastically.Here mangohud Baldur's gate 3 logs for example:
https://flightlessmango.com/games/27057/logs/5383

I noticed that when it happens, GPU utilization also drops from 97% to around 60%. This occurs in any game for me. 
Game running from KDE itself don't have such issue.

**Comment by Joshua-Ashton** [comment]
Try adding `LD_PRELOAD=""` before the gamescope command.

**Comment by VeilSilence** [comment]
`LD_PRELOAD=""  gamescope -w 2560 -h 1440 --mangoapp  %command% `
I'll test again BG3.

**Comment by VeilSilence** [comment]
Hmm 52 minutes and no performance regression. Maybe `gamemoderun` cause the issue. I'm gonna test with `gamemoderun` now

**Comment by kisak-valve** [comment]
Thanks @VeilSilence, that makes this the same issue as #1292. Closing as a duplicate.
