### ISSUE TITLE
Galileo screen stays off after undocking when resolution >720p

### ISSUE THREAD

**Issue by Sterophonick** [ValveSoftware/gamescope#1385]
When undocking a Galileo unit in game mode, the screen tends to stay turned off and is not fixed until a session restart. This can be worked around if the resolution is forced to 720p on the external screen.

Matching SteamOS issue: https://github.com/ValveSoftware/SteamOS/issues/1504

**Comment by matte-schwartz** [comment]
fixed on my end with: https://github.com/ValveSoftware/gamescope/commit/e31b8dea137d2cedd4cf71fede560feb2ad3ffc5
