### ISSUE TITLE
cursor does not reach full length of pop-up menus in certain launchers within gamescope-session

### ISSUE THREAD

**Issue by matte-schwartz** [ValveSoftware/gamescope#1389]
In certain launchers, the cursor no longer reaches the entire span of sub-menus that pop-up. The last known good tagged version of gamescope is 3.14.2.

![IMG_1696](https://github.com/ValveSoftware/gamescope/assets/136293710/b13fbaf1-b586-4f38-b241-fd544b47a84b)

If it's helpful, one commit in May, https://github.com/ValveSoftware/gamescope/commit/455fdfcb, had an effect on the type of sub-menus I am talking about, instead placing the menu in the upper left corner. However, the input issue was unaffected by this.

**Comment by RodoMa92** [comment]
Yeah, can reproduce it personally. It seems that the mouse is stuck in the first rectangle of the window detected, even if gamescope correctly resizes the view if the menu is too long.
