### ISSUE TITLE
Support libdisplay-info >= 0.2.0

### ISSUE THREAD

**Issue by lodriguez** [ValveSoftware/gamescope#1390]
Archlinux did update libdisplay-info to 0.2.0 and right now it's not possible to build gamescope. Is support for libdisplay-info >= 0.2.0 planed anytime soon? 

Edit: @archlinux: A patch using fallback libdisplay-info should get merged very soon.

**Comment by jackun** [comment]
wdym, 3.14.21+ buyilds fine

**Comment by lodriguez** [comment]
> wdym, 3.14.21+ builds fine

How with this Check? https://github.com/ValveSoftware/gamescope/blob/3b69847e15c84c0a4f93e82c2eb16b623f9765b9/src/meson.build#L37

**Comment by jackun** [comment]
Previously configured build dir. Delete it.

**Comment by lodriguez** [comment]
> Previously configured build dir. Delete the check.

Then it runs into errors. Looks like the ABI changed.

**Comment by HanabishiRecca** [comment]
Gamescope does provide a fallback for that. This is Arch package issue.
I made a fix in https://gitlab.archlinux.org/archlinux/packaging/packages/gamescope/-/merge_requests/3

**Comment by kode54** [comment]
Switching to using the system library was a leftover from when bundling it resulted in installing a copy to the system, conflicting with the system library.

**Comment by MBA380** [comment]
Fixed in today's arch package update.

**Comment by Gpinchon** [comment]
Could someone validate @tgurr merge request ?
This issue breaks gamescope on Tumbleweed too
