### ISSUE TITLE
Mura Compensation has no effect

### ISSUE THREAD

**Issue by mwsimmonite** [ValveSoftware/gamescope#1417]
Hi there,

I noticed bad Mura on my steam deck OLED (had only played a game with heavy film grain after getting it so took a while to realise what it was). I checked the new Mura Compensation switch was enabled in developer options, and found that enabling or disabling had no effect whatsoever, in or out of games.

Looking into it I found this script had been suggested previously as what makes up the solution (galileo-mura). In case that is relevant here’s my experience of digging into that:

I manually tried running it’s download script option - it errors out and gives a 404 if I go to the link for the .tar file it’s supposed to produce containing the mura map manually.

Running it’s setup component errors out.

Running the extractor component does produce a blob.tar zip in /tmp/mura - however it isn’t extractable and says it’s damaged or I don’t have permissions to open it. It has a file size of 2.0MB so I believe the data is in there and it isn’t just a failed export or something.

I’ve tried one or two older versions of this script but with the same results.

Is there anything I can do to try get the mura compensation working as expected? Is there anything I can do besides visually see no change to check what may be the issue or if it is indeed doing something but with no effect.

I’ve tried this on a Steam OS install on an SSD taken directly out of my old LCD deck, and on an install on the included SSD reset to factory settings. I’ve not been able to try a totally fresh install or restore.

Thanks for your time and help,
Mark

**Comment by matte-schwartz** [comment]
Are you using an OLED Deck with an SDC panel or a BOE panel? You can check in Game Mode with Settings -> System -> Model/Serial Numbers and looking under OLED Display Assembly. Also, which SteamOS version did you try?

**Comment by mwsimmonite** [comment]
It’s a Samsung panel, I’ve tried it on 3.6, on prerelease and on main, all have 0 effect…

**Comment by mwsimmonite** [comment]
I’ve now tried another fresh install from the steam deck recovery image, and also the latest version of bazzite (which apparently has added the Mura compensation feature).

In no instance on any version of the OS does the Mura compensation have any effect (zero change even looking close up to my face…)

A long shot but could this be a hardware thing? I’ve no idea why it would but I’m clutching at straws.

**Comment by Joshua-Ashton** [comment]
Hello.

If you `/home/deck/.config/gamescope/mura` folder, restart, and then restart again, it should be fixed now.

Thanks for the report.

**Comment by mwsimmonite** [comment]
Deleted the folder and rebooted twice (had to go from stable which is reverted to, up to beta).

Now on 3.68 and it’s night and day. 

Thanks Joshua

**Comment by lukas150800** [comment]
The mura compensation seems to not Work for me still, and it also affects total blacks, e.g. a fully black screen transition is grainy worse from left to right.

Any idea?

**Comment by Joshua-Ashton** [comment]
The issue that was fixed above was related to that user's specific deck.

What you are describing sounds like s totally different issue.
