### ISSUE TITLE
Mangoapp frozen/not updating

### ISSUE THREAD

**Issue by gorgbus** [ValveSoftware/gamescope#1431]
I run gamescope from the launch options of games like this `gamemoderun gamescope -h 1080 -f --mangoapp %command%`
the game itself runs without any issues but the mangoapp in the top left corner stays frozen without updating any of the information
same happens when I try to run the vkcude `gamescope -- sh -c "mangoapp& vkcube"` where even the cube was static image, also tried it with the glxgears and the result was the same

https://github.com/user-attachments/assets/b77103b7-b610-473d-be92-9582c32d9c00

**Comment by matte-schwartz** [comment]
Does `gamemoderun gamescope -h 1080 -f --mangoapp -- vkcube` work? I don't think you should need the bash scripting.

**Comment by gorgbus** [comment]
> Does `gamemoderun gamescope -h 1080 -f --mangoapp -- vkcube` work? I don't think you should need the bash scripting.
> 
same result

> Also, what desktop environment/window manager?

I run hyprland

**Comment by matte-schwartz** [comment]
> > Also, what desktop environment/window manager?
> 
> I run hyprland

most likely https://github.com/hyprwm/Hyprland/issues/6376

**Comment by gorgbus** [comment]
> most likely [hyprwm/Hyprland#6376](https://github.com/hyprwm/Hyprland/issues/6376)

yea that was it, fixed it with the `--backend sdl`
didnt stumble across that, since I didnt really word it right when searching
