### ISSUE TITLE
Clipboard sync between game and host wayland not working

### ISSUE THREAD

**Issue by neonmoe** [ValveSoftware/gamescope#1440]
Minimal reproduction steps:
1. Run `gamescope emacs` (or Crusader Kings III, where I first noticed this, or presumably some other applications)
2. (Write something, select text, and) copy text.
3. Try to paste into a wayland or xwayland window outside of gamescope.

What happens: nothing is pasted.

What I expect: the text from inside gamescope is pasted.

Adding `--backend wayland` didn't help, at least.

**Comment by Joshua-Ashton** [comment]
That feature is not implemented on the Wayland backend -- just `--backend sdl` at the moment.

I imagine it's a good first issue for someone to tackle.

**Comment by neonmoe** [comment]
Oh, I didn't even realize to check, good to know! Apparently indeed copying from wayland/xwayland to the gamescoped application works, but I can't seem to copy from the game (/emacs in the example) to wayland/xwayland.
