### ISSUE TITLE
-S strectched flag causes failure to boot

### ISSUE THREAD

**Issue by AsheCanid** [ValveSoftware/gamescope#1452]
I am attempting to stretchh CS2 to fit either 5:4 (1350 x 1080) or 4:3 (1440 x 1080) but if and only if I boot with -S stretched the game fails to boot.

**Comment by Joshua-Ashton** [comment]
Because it's `-S stretch` not `-S stretched`? =)

**Comment by AsheCanid** [comment]
I was using -S stretch but I was using - f instead of -f I may be stupid.
