### ISSUE TITLE
gamescope wont display some item in wine and flicker

### ISSUE THREAD

**Issue by l12436** [ValveSoftware/gamescope#1457]
Sometimes gamescope will flicker and turn into black with no reason
Some item like dropbox also not shown
It did not happened if not run under gamescope

Test program: windows steam with game Final Fantasy 9 with MoguriMod 8.3.0.0

Run with gamescope and desktop: https://www.mediafire.com/file/8vx5hdmflx3gotl/2024-08-06_10-20-55.flv/file
Run without gamescope, with desktop: https://www.mediafire.com/file/n36squ3fu2rs3v9/2024-08-06_10-27-16.flv/file

Env
Ubuntu 22.04
Gamescope: 3.14.27

**Comment by Joshua-Ashton** [comment]
The focus window might be changing. I don't recommend using Gamescope + Wine virtual desktop. They probably conflict in some way.

**Comment by l12436** [comment]
OK, I know why focus error, there are a patch in WINE allow gamescope working correctly.
So I am going to close this issue
