### ISSUE TITLE
Weird artifacts on Fullscreen/Borderless

### ISSUE THREAD

**Issue by DavutHaxor** [ValveSoftware/gamescope#1471]
![PIXP_12 Aug 03-07-29-PM Mon_lmcl_8 4](https://github.com/user-attachments/assets/058cd0b0-d398-4b09-ae92-e9f5af789a72)

**Comment by DavutHaxor** [comment]
These are not visible when in alt tab, recording, taking a screenshot. Only visible when i focus to the game while its in fullscreen or borderless

**Comment by Virkkunen** [comment]
I have noticed these artifacts as well on 3.14.29-1. I'm on a NVIDIA card, Wayland, with `nvidia-beta-dkms` 560.31.02-1 and `egl-wayland` 3:1.1.15-1

**Comment by Virkkunen** [comment]
I had an update on `egl-wayland` to 4:1.1.16-1 today and I decided to check if this bug still occurs, and it is gone. I have noticed that this issue happens when I add the `--hdr-itm-enable` flag.

**Comment by DavutHaxor** [comment]
The issue fixed. Thank you valve for fixing it. And thank you for ruining gamescope completely now. Another issue persists. Is this your way to solve the issue? Just control the game from outside of fullscreen window. Which results in mouse not focusing
