### ISSUE TITLE
Gamescope prevents Steam from taking screenshots.

### ISSUE THREAD

**Issue by Gibitwit** [ValveSoftware/gamescope#1476]
When running a game with Gamescope and Steam I can not use Steam to take screenshots.  There is no sound or anything when I press F12, which I checked to make sure F12 was bound to screenshot.

Gamescope version:  3.14.24-11

**Comment by kisak-valve** [comment]
Hello @Gibitwit, you've described the Steam overlay not loading up with the game. This issue is already being tracked at #835. Closing as a duplicate.
