### ISSUE TITLE
Gamescope blocks the Steam frame rate counter.

### ISSUE THREAD

**Issue by Gibitwit** [ValveSoftware/gamescope#1477]
When running a game with Steam and Gamescope, while Steam's frame rate counter is enabled, the counter will not appear.  I think this problem is related to the screenshot issue.  https://github.com/ValveSoftware/gamescope/issues/1476

Gamescope version:  3.14.24-11

**Comment by kisak-valve** [comment]
Hello @Gibitwit, the same as #1476. Closing as a duplicate of #835.
