### ISSUE TITLE
Frametime Issues After 30~40 Minutes with Gamescope on Arch Linux (NVIDIA GPU)

### ISSUE THREAD

**Issue by FaelLiberatori** [ValveSoftware/gamescope#1511]
Steps to reproduce:
1. Open a Steam game with Gamescope (tested with both *Baldur's Gate III* and *Death Stranding Director's Cut*);
2. Load any save;
3. Do nothing (or play the game, it doesn't matter);
4. After 30~40 minutes, the frametime becomes unstable, making the game unplayable.

Currently, I'm using the following Steam launch arguments:
`DXVK_HDR=1 gamemoderun gamescope --mangoapp -e -f -w 3440 -h 1440 -r 165 --hdr-enabled %command%`

HDR on/off makes no difference. The game launches and runs perfectly fine until this bug starts. Before that, the frametime is completely normal. I initially thought it was a Proton issue, but after testing the games without Gamescope, I couldn’t reproduce the issue, which makes me think it’s a Gamescope bug (or maybe an NVIDIA one?).

Screenshot before the issue:  
![start_frametime](https://github.com/user-attachments/assets/5ec868a0-cbfc-40ef-acce-ab00e2e5011e)

Screenshot after the issue (after 30~40 min):  
![end_frametime](https://github.com/user-attachments/assets/91881126-51ee-48ee-a07c-3bd943fbeca4)

Some observations:
1. The frametime is synced. Usually, when there’s a performance issue, the frametime graph fluctuates a lot with big and small crests randomly. In this case, all the graph crests are the same size and repeat at the same intervals.
2. MangoHUD cannot detect my GPU info inside Gamescope. Not sure if this is a known issue, but it’s most likely unrelated to the frametime bug. That’s why I included `nvidia-smi` in the screenshot.
3. The frametime issue also seems to mess up the average FPS metric.
4. There’s nothing on the hardware side to explain it. Temperatures and speeds remain consistent throughout gameplay, and this doesn’t happen when running without Gamescope.

System information:
```
Operating System: Arch Linux 
KDE Plasma Version: 6.1.4
KDE Frameworks Version: 6.5.0
Qt Version: 6.7.2
Kernel Version: 6.10.8-zen1-1-zen (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 7700 8-Core Processor
Memory: 32 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3080/PCIe/SSE2
NVIDIA driver version: 560.35.03
Gamescope version: 3.14.29
```
Not sure if this helps, but I'm attaching the Proton/Steam logs below.
[steam-1086940.log](https://github.com/user-attachments/files/16920264/steam-1086940.log)

**Comment by matte-schwartz** [comment]
can you try: https://github.com/ValveSoftware/gamescope/issues/697#issuecomment-2140972389

**Comment by FaelLiberatori** [comment]
> can you try: [#697 (comment)](https://github.com/ValveSoftware/gamescope/issues/697#issuecomment-2140972389) the LD_PRELOAD part of this?

Yeah, it worked. Thank you! It’s pretty frustrating that a bug from 2022 is still around these days, though.

**Comment by kisak-valve** [comment]
Hello @FaelLiberatori, that makes your symptom the same issue as the older issue report. Feel free to add a note with your experience to the older issue report.

Closing as a duplicate.
