### ISSUE TITLE
HDR ITM causing corruption on display playing Persona 3 Reload

### ISSUE THREAD

**Issue by sjohal21** [ValveSoftware/gamescope#1522]
Recently, running Gamescope with HDR ITM enabled has caused severe display corruption. This was on an Arch Linux system running the latest Gamescope git as of the 11th September 2024. I was running an RX 7900 XTX connected to an Alienware AW3423DWF, and was running Mesa 24.2.2 and kernel version 6.10.9 on KDE Plasma 6.1.5, with all other software being fully updated as of the test date. For my test, I launched Persona 3 Reload with and without the HDR tone mapping enabled but with all other flags the same. Without ITM, the game launches fine, and looks as expected for a non tone mapped output. However, when enabling ITM, there was severe display corruption. For example, some of the on screen text was jumbled up in random blocks across the screen. In addition, some of these blocks were out of bounds (the game is 16:9 locked and I am running a 21:9 monitor, so this meant that some of the blocks were in the black bars not ordinarily used by the game). The only change was using the --hdr-itm-enable command line flag in Steam. Unfortunately, I am unable to provide any logs as I am currently running Windows 11 to get HDR fully functional, but none of the console output indicated any abnormal errors when I checked it back on Arch. If anyone has a similar setup and is able to test with a few more games or a different monitor or GPU or something, this might help to figure out this issue, as it may not just be this game affected. I previously used a very similar setup with the same hardware but a few months ago so using an older version of Gamescope, and this error was not present then with HDR ITM enabled on the same game.

**Comment by matte-schwartz** [comment]
Not able to see this in Persona 3 Reload on my AW3423DW or Samsung G95NC on Arch kernel 6.10.9, plasma 6.1.4. My initial guess would be an outdated gamescope layer or interfering Vulkan layer somewhere.

**Comment by sjohal21** [comment]
Well that's kind of odd. Have you got the prerelease Vulkan HDR layers from the AUR (vk-hdr-layer-kwin6-git) installed or not? Maybe not having those messed with my specific setup, although I didn't need those last time either.

**Comment by matte-schwartz** [comment]
No, those are not necessary with up-to-date Gamescope for HDR on Plasma. Just gamescope's own layer. I do also have a 32-bit Gamescope layer in place, so I can try without that, but I'd be a bit surprised if that was circumventing the issue in this case.

**Comment by sjohal21** [comment]
Huh. I'll try this again then on a fresh Arch install then, I'm going to close this issue then since it's clearly not reproducible.

**Comment by matte-schwartz** [comment]
Re-open if it still happens since there could be a lingering bug somewhere. I'll keep trying a couple other games and see if it happens.

**Comment by sjohal21** [comment]
Can confirm, on my current install of Fedora 41 there was no corruption of any kind, and it works perfectly as intended. Must have been a bug elsewhere in the system.
