### ISSUE TITLE
Keyboard bindings incomplete for PIN input

### ISSUE THREAD

**Issue by aria-dos** [ValveSoftware/gamescope#1528]
When using the steam deck with a keyboard, inserting my PIN is very hard without using the gamepad or touch screen.
Backspace seems to be mapped to something, and I'm assuming the arrow keys line up with the D-pad. Escape is mapped to B thus deleting characters, however nothing else seems to be linked.

I don't know how keyboard bindings are dealt with under the hood, I think ideally you'd enter the PIN using the number keys and/or numpad (I think 8,2,4,6 on the numpad copy the arrow keys currently).

**Comment by kisak-valve** [comment]
Hello @aria-dos, this is unlikely to be a gamescope issue. Closing as a duplicate of https://github.com/ValveSoftware/SteamOS/issues/804.
