### ISSUE TITLE
Gamescope is not syncing the clipboard

### ISSUE THREAD

**Issue by lavadrop** [ValveSoftware/gamescope#1529]
Apparently this was fixed last year but I can't paste anything in the FFXIV log in window.

gamescope: 3.15.9-1.1

Operating System: openSUSE Tumbleweed 20240911
KDE Plasma Version: 6.1.5
KDE Frameworks Version: 6.5.0
Qt Version: 6.7.2
Kernel Version: 6.10.9-1-default (64-bit)
Graphics Platform: Wayland
Processors: 16 × AMD Ryzen 7 5800X3D 8-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 7800 XT
Manufacturer: Gigabyte Technology Co., Ltd.
Product Name: B550 AORUS ELITE AX V2

**Comment by matte-schwartz** [comment]
https://github.com/ValveSoftware/gamescope/issues/1440 I believe it has not been implemented for the Wayland backend yet, but should work if you use `--backend sdl`

**Comment by lavadrop** [comment]
Ah, I see, thank you.

**Comment by Jeorge01** [comment]
Big thanks! This drove me crazy
