### ISSUE TITLE
Gamescope 3.15.9 totally broken on my system

### ISSUE THREAD

**Issue by radek-stasta** [ValveSoftware/gamescope#1530]
As I described here: https://github.com/NixOS/nixpkgs/issues/342512, current version of gamescope is totally broken on my system. Video: https://streamable.com/ls8zm0. Using Proton GE 9-13

**Comment by matte-schwartz** [comment]
```
❯ gamescope --version
[gamescope] [Info]  console: gamescope version 3.15.9 (gcc 14.2.1)
```
just checked and am not seeing any issue with Everspace 2's demo with either DX11 or DX12 on Plasma 6 Wayland (I don't own the full game to test):

![Screenshot_20240917_095135](https://github.com/user-attachments/assets/23fa4918-a67b-4830-8366-8b3aee0e0a71)

What launch command are you using? Any relevant logging from gamescope? What desktop environment, or are you talking about the DRM backend when run from TTY?

**Comment by radek-stasta** [comment]
I launch whole steam inside gamescope with: 'gamescope -w 2560 -h 1440 -f -- steam'. Im using NixOS with Hyprland. Maybe is something broken on my side, but Im now downgraded to 3.14.29 and everything is running just fine, only if I update gamescope those problems suddently appear

**Comment by matte-schwartz** [comment]
that also works fine for me. sounds like a hyprland issue.

**Comment by radek-stasta** [comment]
[gamescope.log](https://github.com/user-attachments/files/17032907/gamescope.log)
[gamescopeWorking.log](https://github.com/user-attachments/files/17032908/gamescopeWorking.log)

Logs from working and not working runs

**Comment by radek-stasta** [comment]
And yes, setting that variable does not have any effect. It might be hyprland or maybe NixOS, but still something must have changed, since it is working all right with previous version

**Comment by matte-schwartz** [comment]
in your case it's likely https://github.com/ValveSoftware/gamescope/commit/ef3ff8a62a32458d5811768c7c8be5337a6610f5 that caused this issue. probably something to do with how Hyprland interacts with explicit sync since it works fine on Plasma 6 Wayland/X11. don't think this is our bug but rather a different bug that gamescope's implementation exposed. if you set https://github.com/ValveSoftware/gamescope/blob/d87f6d9b9d98ea8064e4063c01d483895fef87f0/src/Backends/DRMBackend.cpp#L70 to true and re-compile, gamescope might work for you again.

**Comment by radek-stasta** [comment]
I'm sorry, I don't have enough knowledge how to compile it myself and how to then push to NixOS package so I can test it on my system :(

**Comment by radek-stasta** [comment]
So I finally had time to revisit this problem. I created my own fork here: https://github.com/radek-stasta/gamescope and modified the line you suggested:

[#](https://github.com/ValveSoftware/gamescope/compare/master...radek-stasta:gamescope:master#diff-98121d8bfe66603c83b25acbf33ccea585feb869e4759d9f510d79a9bedf6f6b)

And indeed the gamescope is working correctly as before without any issues. Can I do something more about it or is there a way how to use fix this on some side so I can use official release and not my forked version?

**Comment by zeptic99** [comment]
> So I finally had time to revisit this problem. I created my own fork here: https://github.com/radek-stasta/gamescope and modified the line you suggested: [master...radek-stasta:gamescope:master#diff-98121d8bfe66603c83b25acbf33ccea585feb869e4759d9f510d79a9bedf6f6b](https://github.com/ValveSoftware/gamescope/compare/master...radek-stasta:gamescope:master#diff-98121d8bfe66603c83b25acbf33ccea585feb869e4759d9f510d79a9bedf6f6b) And indeed the gamescope is working correctly as before without any issues. Can I do something more about it or is there a way how to use fix this on some side so I can use official release and not my forked version?

Wow, this fixed "The Finals" for me. Valve should definitely look into fixing this!

**Comment by radek-stasta** [comment]
https://github.com/radek-stasta/gamescope/releases/tag/3.15.13
Updated to 3.15.13 until we get some official info

**Comment by matte-schwartz** [comment]
Still unable to repro here... I am pretty sure this is not our bug tbh, if that workaround did help for you it seems like we're just avoiding some Hyprland issue :/

**Comment by radek-stasta** [comment]
So what is the correct solution here? Expose this issue to Hyprland team?

**Comment by matte-schwartz** [comment]
Likely yes, although I don't know how Hyprland issue reporting works. you have a decent amount of useful info now that you know disabling explicit sync makes it work again.

**Comment by radek-stasta** [comment]
Im closing this issue and will keep my repository updated with gamescope releases until it is resolved somehow. Thanks for support
