### ISSUE TITLE
175% scale breaks fullscreen window sizing

### ISSUE THREAD

**Issue by ninja-** [ValveSoftware/gamescope#1536]
With gamescope running at native monitor resolution(3840x2160) at 175% scale, it will leave a few pixels at the bottom and right side of the screen to the system instead of being properly fullscreen.
This issue does not happen at 150% and 200%.
This doesn't look like a KWin bug either because other games seem to fullscreen just fine.

Version: 3.15.9

**Comment by anthr76** [comment]
I see this at 140% as well.

**Comment by anthr76** [comment]
This seems to be a duplicate of https://github.com/ValveSoftware/gamescope/issues/1392

**Comment by ammuench** [comment]
+1, seeing this on KDE  6.2.2.

Ultrawide monitor 3440x1400.  150% scale is off by a few pixels on the right, 140% scale off by a few on the right and bottom.  Fine at 125% scale

**Comment by dubiousgit** [comment]
Ooooh is that what's happening? I was starting to think I was going mad.

120, 125, 150, 160 are all fine for me.

The rest in the range 105 - 195 report an incorrect resolution in gamescope, and exhibit this issue.

`[gamescope] [Info]  console: gamescope version  (gcc 14.2.1)`

**Comment by retrixe** [comment]
This issue seems to occur for me on GNOME with Fedora Workstation 41 as well, with Minecraft running using `-W 1920 -H 1200` at 175% fractional scaling (2880x1800), I observe a sliver of the screen is visible at the bottom which is causing the cursor to get stuck there

**Comment by dinotheextinct** [comment]
same issue here on KDE with 135% fractional scaling

Operating System: openSUSE Tumbleweed 20241121
KDE Plasma Version: 6.2.3
KDE Frameworks Version: 6.8.0
Qt Version: 6.8.0
Kernel Version: 6.11.8-1-default (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 5600X 6-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 7900 XT
Manufacturer: ASUS

**Comment by matte-schwartz** [comment]
it's fixed for me with Colin's PR: https://github.com/ValveSoftware/gamescope/pull/1630
