### ISSUE TITLE
Minecraft Mouse Movement Extremely Sensitive

### ISSUE THREAD

**Issue by HurricanePootis** [ValveSoftware/gamescope#1541]
# System Information
Arch Linux
Gamescope 3.15.11
GNOME 47 (Wayland w/ Fractional XWayland Scaling)
AMD Ryzen 5 5600
AMD Radeon RX 6800 w/ Mesa stack

# Background
Due to GNOME's new Xwaylan fractional scaling method, they are setting XWayland's resolution where apps need to only integer scale up or something; it is better described [here](https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/3567#note_2191910).

Therefore, since some games (Minecraft with sodium, celeste, etc) do not have a resolution slider, it will render at a much higher resolution than the screen, resulting in a tangible drop in performance and worse battery life on laptops. Some people told me to try gamescope, and here we are.

# Problem
In minecraft, I am unable to look around with my mouse at all. Here is an attached video of the bug  

https://github.com/user-attachments/assets/5d9ff10e-a6dd-4044-b768-59d0f3064bc4

I am using the following gamescope command:
`gamescope -w 2560 -h 1440 -W 2560 -H 1440 -S auto`

This happens with modded minecraft and on vanilla minecraft. I have only tested this on GNOME and not KDE.

**Comment by misyltoad** [comment]
Is this on Gnome X11 or Gnome Wayland? What Gamescope backend?

**Comment by HurricanePootis** [comment]
Gnome Wayland, as indicated by the fractional Xwayland scaling. I tried it right now with both the sdl and wayland backend, and I am still getting the same mouse movement issues.

**Comment by Ictoan42** [comment]
I'm getting the same issue in Trackmania, X11 on AwesomeWM. The mouse behaves normally for mousing over buttons, but when the game grabs the mouse for camera rotation it is uncontrollable

**Comment by HurricanePootis** [comment]
Could this be an issue with GLFW, which is used by minecraft, or a minecraft specific issue?

**Comment by misyltoad** [comment]
fractional xwayland scaling in Gnome should not affect games run inside gamescope on the wayland backend though

**Comment by HurricanePootis** [comment]
Yeah, seems like this is more of a gamescope issue with mouse input? But, I am using gamescope because GNOME's fractional scaling for XWayland works (I think) in a way where an XWayland app will need to scale 2X by itself, but will show up as whatever scale. For example, using a 1.25X on my 1920x1200 screen, I get the following resolutions from Xrandr with native xwayland fractional scaling enabled:

```
hurricane@TheCloutBook ~ $ xrandr
Screen 0: minimum 16 x 16, current 3072 x 1920, maximum 32767 x 32767
eDP-1 connected primary 3072x1920+0+0 (normal left inverted right x axis y axis) 300mm x 190mm
   3072x1920     59.99*+
   2048x1536     59.95  
   1920x1440     59.97  
   1600x1200     59.87  
   1440x1080     59.99  
   1400x1050     59.98  
   1280x1024     59.89  
   1280x960      59.94  
   1152x864      59.96  
   1024x768      59.92  
   800x600       59.86  
   640x480       59.38  
   320x240       59.52  
   2560x1600     59.99  
   1920x1200     59.88  
   1680x1050     59.95  
   1440x900      59.89  
   1280x800      59.81  
   1152x720      59.97  
   960x600       59.63  
   928x580       59.88  
   800x500       59.50  
   768x480       59.90  
   720x480       59.71  
   640x400       59.95  
   320x200       58.96  
   2880x1620     59.96  
   2560x1440     59.96  
   2048x1152     59.90  
   1920x1080     59.96  
   1600x900      59.95  
   1368x768      59.88  
   1280x720      59.86  
   1024x576      59.90  
   864x486       59.92  
   720x400       59.55  
   640x350       59.77  
```

**Comment by HurricanePootis** [comment]
In the mean time, if anyone else is having this problem, I would use [Xwayland-run](https://gitlab.freedesktop.org/ofourdan/xwayland-run) for playing on GNOME xwayland fractional scaling.

**Comment by laurirasanen** [comment]
Does the issue happen with `--force-grab-cursor`?

**Comment by HurricanePootis** [comment]
@laurirasanen No it does not. I guess problem solved?
