### ISSUE TITLE
git error updating wlroots when following readme

### ISSUE THREAD

**Issue by adamdmoss** [ValveSoftware/gamescope#1549]
```
~/code/gamescope % git submodule update --recursive --init
fatal: remote error: upload-pack: not our ref 4bc5333a2cbba0b0b88559f281dbde04b849e6ef
fatal: Fetched in submodule path 'subprojects/wlroots', but it did not contain 4bc5333a2cbba0b0b88559f281dbde04b849e6ef. Direct fetching of that commit failed.
```
I've tried nuking `subprojects` and a `git reset --hard` and a few other things.  Guess the subproject really is pointing to a `wlroots` ref (4bc5333a2cbba0b0b88559f281dbde04b849e6ef) that doesn't exist, but I dunno.

**Comment by kisak-valve** [comment]
Hello @adamdmoss, check if https://github.com/ValveSoftware/gamescope/issues/1468#issuecomment-2283949929 helps.

**Comment by adamdmoss** [comment]
Wow yeah, that did it, thanks!
I searched for a similar issue including closed issues but for some reason that one didn't come up.
Cheers.
