### ISSUE TITLE
Gamescope WSI does not let proton games to be screenshare when enforced

### ISSUE THREAD

**Issue by Theoldnation** [ValveSoftware/gamescope#1563]
when WSI is enabled in a game using proton screenshare will not work for applications like discord that normally make use of xwaylandvideobridge under desktops environments like KDE or gnome, the games using proton will appear in black this affects mainly steamos gaming mode

**Comment by misyltoad** [comment]
This is not fixable, without us implementing some proper screenshare portal in Gamescope, which we should do.

But XWayland sharing with Gamescope WSI will always be broken, and it is not fixable, sorry.

**Comment by IsaacFehr** [comment]
Hello!  I was pointed here from the SteamOS issue linked above, and I'm looking to understand the issue a bit more.  

Sorry for the dumb question, but is the WSI referenced the Vulkan extension for Window System Integration?  Can you explain or point me somewhere to help me understand why screen-sharing isn't possible with WSI through XWaylandVideoBridge to GameScope?

Is this a matter of writing a new xdg-desktop-portal backend with a `ScreenCast` implementation for gameecope?

Would this problem still exist if Proton was run using the Wayland driver?

And finally, is this work planned anywhere?

Thanks in advance 😃

**Comment by ali-alidoust** [comment]
I made a custom swayfx desktop to be run in Game Mode and created a fake xdg-desktop-portal wrapper that fixes this issue. I've been streaming the whole screen with audio without any issues so far. Maybe it's possible to just use the xdg-desktop-portal wrapper without going through the whole process.
repo: https://github.com/ali-alidoust/dactyl
xdg wrapper: https://github.com/ali-alidoust/dactyl/blob/main/bin/xdg-desktop-portal-dactyl.py
