### ISSUE TITLE
need help. finished building and installing.

### ISSUE THREAD

**Issue by Talion117** [ValveSoftware/gamescope#1588]
hi, i need help with an issue.

Installing layer/libVkLayer_FROG_gamescope_wsi_x86_64.so to /usr/local/lib/x86_64-linux-gnu
Installation failed due to insufficient permissions.
Attempt to use /usr/bin/sudo to gain elevated privileges? [y/n] 

meson install -C build/ --skip-subprojects
ninja: Entering directory `/home/talion117/gamescope/build'
ninja: no work to do.
Installing layer/libVkLayer_FROG_gamescope_wsi_x86_64.so to /usr/local/lib/x86_64-linux-gnu
Installation failed due to insufficient permissions.
Attempt to use /usr/bin/sudo to gain elevated privileges? [y/n] 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py", line 194, in run
    return options.run_func(options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 873, in run
    installer.do_install(datafilename)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 553, in do_install
    self.install_targets(d, dm, destdir, fullprefix)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 750, in install_targets
    file_copied = self.do_copyfile(fname, outname, makedirs=(dm, outdir))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 412, in do_copyfile
    self.remove(to_file)
  File "/usr/lib/python3/dist-packages/mesonbuild/minstall.py", line 311, in remove
    os.remove(*args, **kwargs)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/x86_64-linux-gnu/libVkLayer_FROG_gamescope_wsi_x86_64.so'

ERROR: Unhandled python OSError. This is probably not a Meson bug, but an issue with your build environment.

**Comment by matte-schwartz** [comment]
I'm pretty sure that's just the error you get if you don't respond y when it asks for elevated privileges to install to a directory

**Comment by Talion117** [comment]
> I'm pretty sure that's just the error you get if you don't respond y when it asks for elevated privileges to install to a directory

i see, so im fine then? its installed?

**Comment by matte-schwartz** [comment]
Well no, you didn't give it permission to install by responding "y" hence the error. If you install to a privileged directory like /usr/local then it needs permission before it'll actually install anything.

**Comment by Talion117** [comment]
> Well no, you didn't give it permission to install by responding "y" hence the error. If you install to a privileged directory like /usr/local then it needs permission before it'll actually install anything.

how do i fix it?

**Comment by Talion117** [comment]
also, i decide to delete the folder.

now it seems i have to reinstall epoll-shim and it seems to be missing xcb-errors.
wlroots| Run-time dependency xcb-errors found: NO (tried pkgconfig and cmake)
wlroots| Message: Required for printing X11 errors.
