### ISSUE TITLE
OpenGL ES backend

### ISSUE THREAD

**Issue by BBaoVanC** [ValveSoftware/gamescope#1610]
### Feature request

Is it possible to add a GLES-based backend when running on top of DRM directly? My usecase is the Spotify Car Thing, and I want to just run Chromium close to metal without any sort of window management. Its GPU is Mali G31 which doesn't seem to have any mature Vulkan driver, but there is OpenGL via the Mesa Panfrost driver.

**Comment by misyltoad** [comment]
There are no plans to add GL support. Sorry.

**Comment by BBaoVanC** [comment]
> You can use cage compositor instead. I have a video demo on the same gpu.

Can you share? I think I will try cage.

**Comment by neofeo** [comment]
It's a very basic tutorial, just take it as reference. https://www.youtube.com/watch?v=I5nopJwDGqg
