### ISSUE TITLE
CS2 Dual monitor: --force-grab-cursor does not work when using -S stretch  

### ISSUE THREAD

**Issue by Kladdiskakan** [ValveSoftware/gamescope#1628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using any gamescope patches or a forked version of gamescope?

- [X] The issue occurs on upstream gamescope without any modifications

### Current Behavior

Seems like --force-grab-cursor won't be recognized when I have set the scaler flag to stretch. I can keep dragging my mouse over to the other screen. 

### Steps To Reproduce

1. Launch CS2 from Steam with the launch option ´gamescope -W 1920 -H 1440 -f -S stretch --force-grab-cursor -- %command%´
2. Try to move the cursor to another screen from the game

### Hardware information

```markdown
- Distro: Arch Linux
- CPU: 6-Core AMD Ryzen 5 5600X
- GPU: AMD Radeon RX 7800 XT (RADV NAVI32)
- Driver Version: Mesa 24.2.6-arch1.1
```

### Software information

```markdown
- Desktop environment: Gnome 47
- Session type: wayland
- Gamescope version: gamescope version 3.15.14 (gcc 14.2.1)
- Gamescope launch command(s): gamescope -W 1920 -H 1440 -f -S stretch --force-grab-cursor -- %command%
```

### Which gamescope backends have the issue you are reporting?

- [X] Wayland (default for nested gamescope)
- [ ] DRM (default for embedded gamescope, i.e. gamescope-session)
- [ ] SDL
- [ ] OpenVR

**Comment by kisak-valve** [comment]
Hello @Kladdiskakan, this issue is already being tracked at #1605. Closing as a duplicate.
