### ISSUE TITLE
do i need epoll-shim for gamescope?

### ISSUE THREAD

**Issue by Talion117** [ValveSoftware/gamescope#1635]
Hi, im trying to figured it if i need epoll-shim for gamescope.

but i do the following:

git clone https://github.com/jiixyj/epoll-shim.git

cd epoll-shim

mkdir build

cd build

cmake ..

make.

then itries to install a d gives me a 100% dsyncy fail?

if i cant install it. do i need it?

what about for xcb-errors?

both says run time dependency error not found.

**Comment by misyltoad** [comment]
Are you using BSD?

**Comment by Talion117** [comment]
> Are you using BSD?

BSD? whats that?

**Comment by Talion117** [comment]
so anyone can help?
