### ISSUE TITLE
`--force-grab-mouse` don't respect the host mouse acceleration

### ISSUE THREAD

**Issue by yvvki** [ValveSoftware/gamescope#1639]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using any gamescope patches or a forked version of gamescope?

- [X] The issue occurs on upstream gamescope without any modifications

### Current Behavior

I need to use `--force-grab-cursor` when playing Counter-Strike 2 in Wayland since without it, the in-game camera movement is borked. However using it makes the main menu cursor sensitivity faster.

### Steps To Reproduce

1. Launch Counter-Strike 2 with this option
   ```
   gamemoderun gamescope -W 1920 -H 1200 -w 1280 -h 800 -S stretch -e -f --force-grab-cursor --expose-wayland --immediate-flips -- %command% +fps_max 75 -nojoy -softparticlesdefaultoff -console -vulkan -high +engine_low_latency_sleep_after_client_tick true +exec autoexec.cfg
   ```
2. Move mouse around in the main menu
3. See the cursor move faster than on the host compositor 

### Hardware information

```markdown
- Distro: Arch Linux (linux-zen 6.12.1.zen1-1)
- CPU: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
- GPU: Intel TigerLake-LP GT2 [Iris Xe Graphics]
- Driver Version: Mesa 24.2.7-arch1.1
```

### Software information

```markdown
- Desktop environment: Hyprland (0.45.2-3)
- Session type: Wayland
- Gamescope version: 3.15.14 (gcc 14.2.1)
- Gamescope launch command(s): gamescope -W 1920 -H 1200 -w 1280 -h 800 -S stretch -e -f --force-grab-cursor
```

### Which gamescope backends have the issue you are reporting?

- [X] Wayland (default for nested gamescope)
- [ ] DRM (default for embedded gamescope, i.e. gamescope-session)
- [ ] SDL
- [ ] OpenVR

**Comment by kisak-valve** [comment]
Hello @yvvki, this issue is already being tracked at #196. Closing as a duplicate.
