### ISSUE TITLE
gamescope restarts every time the game is closed (SteamDeck)

### ISSUE THREAD

**Issue by omfgnuts** [ValveSoftware/gamescope#1640]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using any gamescope patches or a forked version of gamescope?

- [X] The issue occurs on upstream gamescope without any modifications

### Current Behavior

Every time I launch the game & close it or put the Steam Deck to sleep while the game is running - gamescope restarts.

It started happening after the recent SteamDeck update.

I would appreciate any debugging instructions & log instructions. If you feel that is the SteamOS issue - i'll delete the ticket and re-submit it to the SteamOS bugtracker.

### Steps To Reproduce

1. Launch the game
2. Close it in any way
3. steam (I assume it's the gamescope) just restarts 

or

1. Launch the game
2. Press the power button once
3. gamescope restarts

### Hardware information

```markdown
- Distro: SteamOS Holo, latest Main Branch
- CPU: APU 0932
- GPU: Steam Deck OLED GPU
- Driver Version: 4.6, Mesa 24.0.5
```

### Which gamescope backends have the issue you are reporting?

- [X] Wayland (default for nested gamescope)
- [ ] DRM (default for embedded gamescope, i.e. gamescope-session)
- [ ] SDL
- [ ] OpenVR

**Comment by matte-schwartz** [comment]
fwiw its slated to be fixed in a upscoming Steam Deck beta client update: https://github.com/ValveSoftware/steam-for-linux/issues/11498
