### ISSUE TITLE
Steam immediately exits when started with gamescope

### ISSUE THREAD

**Issue by orbea** [ValveSoftware/gamescope#1664]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using any gamescope patches or a forked version of gamescope?

- [X] The issue occurs on upstream gamescope without any modifications

### Current Behavior

When starting Steam with gamescope from an unused tty it just immediately exits without any clear errors. However starting vkcube from the same tty works without issue.

### Steps To Reproduce

1. Open an unused tty.
2. Start steam with gamescope.
3. Renders a black screen for a moment and then immediately exits.

### Hardware information

```markdown
- Distro: Gentoo
- CPU: AMD Ryzen 9 7900X 12-Core Processor
- GPU: AMD Radeon RX 5700 XT (RADV NAVI10)
- Driver Version: Mesa 25.0.0-devel (git-191d7c6cb6)
```

### Software information

```markdown
- Desktop environment: tty
- Session type: tty
- Gamescope version: 3.15.15 (gamescope --version has an empty version string?)
- Gamescope launch command(s): See script:
```
```
#!/bin/sh

set -euf

cd -- "$HOME"/games/steam-launcher

export XDG_RUNTIME_DIR='/tmp/runtime-steam'

mkdir -p -- "$XDG_RUNTIME_DIR"

export STEAM_RUNTIME=1
export ENABLE_GAMESCOPE_WSI=0
export WAYLAND_DEBUG=client

gamescope=" \
  --expose-wayland \
  --steam \
  --xwayland-count 2"

eval "set -- $gamescope"
/usr/bin/gamescope "$@" -- ./steam -tenfoot
```

### Which gamescope backends have the issue you are reporting?

- [ ] Wayland (default for nested gamescope)
- [X] DRM (default for embedded gamescope, i.e. gamescope-session)
- [ ] SDL
- [ ] OpenVR

### Logging, screenshots, or anything else

Gamescope log: [steam-gamescope.log](https://github.com/user-attachments/files/18133837/steam-gamescope.log)

**Comment by matte-schwartz** [comment]
I tried your script using my own Steam install (so not `./steam`) and I was not able to reproduce this on Arch with a 7900XTX

would be helpful to see Steam client logs as well, at first glance this looks more like a possible Steam issue than a gamescope issue to me. does gamescope coredump when this happens? also, do you have amdvlk installed?

**Comment by orbea** [comment]
It used to work for me too, at least enough to open the client. However its been a while so I'm not sure when or why it broke. Steam still works fine in X11 without gamescope at least.

> would be helpful to see Steam client logs as well

Where do I find these? Or how do I enable them?

> also, do you have amdvlk installed?

No, only mesa.

**Comment by matte-schwartz** [comment]
`tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs` is the standard method to grab logs, but you can adjust it to wherever your steam folder actually is. those dmp files also look like steam to me. you can typically check if gamescope is coredumping with `coredumpctl list` and seeing if anything is present there

**Comment by orbea** [comment]
Actually that helps a lot, thanks! The error in `console-linux.txt` is:
```
src/steamexe/updateui_gl.cpp (308) : UpdateUI CreateGlFont regular failed
```
Making this a duplicate of issue https://github.com/ValveSoftware/gamescope/issues/951

I solved it by moving `~/.local/share/Steam/tenfoot` out of the way and then starting steam in X11 to regenerate the directory. Now the client starts using gamescope again.
