### ISSUE TITLE
Gamescope launches as a separate window

### ISSUE THREAD

**Issue by Akeem29** [ValveSoftware/gamescope#1684]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using any gamescope patches or a forked version of gamescope?

- [X] The issue occurs on upstream gamescope without any modifications

### Current Behavior

When launching a Steam game (in my case it's Finding Paradise), Gamescope launches as a separate invisible window, seemingly unable to affect the game window in any way, in my case I tried to make game's window scale using "pixel" method, but the window scales up with the default interpolation that is present when gamescope isn't running. The problem does not happen outside of Steam (specifically - in Bottles, also installed through Flatpak)

### Steps To Reproduce

1. Install Steam and Gamescope through flatpak (flatpak install flathub com.valvesoftware.Steam; flatpak install flathub org.freedesktop.Platform.VulkanLayer.gamescope)
2. Install a game
3. Add "gamescope -w 640 -h 480 -W 1920 -H 1080 -F pixel -S fit -f -- %command%" to the launch options
4. Launch the game

### Hardware information

```markdown
- Distro: Fedora Kinoite 41
- CPU: Intel core i5 12400
- GPU: Nvidia GTX 1650
- Driver Version: NVIDIA 565.77
```

### Software information

```markdown
- Desktop environment: KDE Plasma 6.2.4
- Session type: wayland
- Gamescope version: 3.16.1
- Gamescope launch command(s): gamescope -w 640 -h 480 -W 1920 -H 1080 -F pixel -S fit -f -- %command%
```

### Which gamescope backends have the issue you are reporting?

- [X] Wayland (default for nested gamescope)
- [ ] DRM (default for embedded gamescope, i.e. gamescope-session)
- [ ] SDL
- [ ] OpenVR

### Logging, screenshots, or anything else

This file is a copy of terminal output of "flatpak run com.valvesoftware.Steam", with the information outputted before the launch of the game removed
[gamescope_log.txt](https://github.com/user-attachments/files/18246270/gamescope_log.txt)

![gamescope_is_a_separate_window](https://github.com/user-attachments/assets/1a58b761-f7ce-4751-841e-6b65e8d62aa9)

**Comment by matte-schwartz** [comment]
I checked Finding Paradise with your launch options on my ROG Ally while using non-flatpak Gamescope/Steam on Arch and was not able to reproduce the issue. I'm inclined to say this will either be an issue with one of the two Flatpak packages, or an Intel/NVIDIA issue (which I don't have easy access to for the next few weeks while traveling) of some sort. 

Maybe worth trying to select your NVIDIA card as your Vulkan device with `--prefer-vk-device` as well since it looks like it's currently using the iGPU.

**Comment by Akeem29** [comment]
> I checked Finding Paradise with your launch options on my ROG Ally while using non-flatpak Gamescope/Steam on Arch and was not able to reproduce the issue. I'm inclined to say this will either be an issue with one of the two Flatpak packages, or an Intel/NVIDIA issue (which I don't have easy access to for the next few weeks while traveling) of some sort.
> 
> Maybe worth trying to select your NVIDIA card as your Vulkan device with `--prefer-vk-device` as well since it looks like it's currently using the iGPU.

Addition of "--prefer-vk-device" did nothing, but running non-flatpak Steam and Gamescope solved the issue. Thank you!
