### ISSUE TITLE
Changing resolution from within an old windows game using wine.

### ISSUE THREAD

**Issue by Quackdoc** [ValveSoftware/gamescope#253]
I've been trying to play old games via Wine + Gamescope, some old games want to set resolution manually and when they can't they either fall back to software rendering or do internal scaling. This is the message that gets dumped when trying to change resolution from ingame. Even if the resolution is set right.

```
Unhandled NET_WM_STATE property change: _NET_WM_STATE_ABOVE
Unhandled NET_WM_STATE property change: _NET_WM_STATE_MAXIMIZED_VERT
Unhandled NET_WM_STATE property change: _NET_WM_STATE_MAXIMIZED_HORZ
```

Would it be possible to change resolution from in game with wine games?

**Comment by emersion** [comment]
Xwayland has emulation for this in place, ref https://github.com/Plagman/gamescope/issues/68

**Comment by Joshua-Ashton** [comment]
The XServer exposes other modes now in the latest release and fakes them succeeding.

We rely on our internal scaling systems for the user to pick what they want.
