### ISSUE TITLE
Add flag to rotate the screen.

### ISSUE THREAD

**Issue by ruineka** [ValveSoftware/gamescope#370]
I'm using gamescope on ChimeraOS and its upside down on my OneXPlayer. For the default steam compositor I need to set the ROTATION=left flag in the configuration file.

**Comment by ruineka** [comment]
Issue remains today with kernel quirks that rotate the display for other distros, but not with steam using gamepadui on a gamescope-session with the OneXPlayer.

The display remains rendered upsidedown without a way to rotate it.

**Comment by Joshua-Ashton** [comment]
Does replacing DRM_MODE_ROTATE_270 with DRM_MODE_ROTATE_90 in `drm.cpp` fix it?

We could definitely expose more rotation params if that fixes it for you.

**Comment by ruineka** [comment]
> Does replacing DRM_MODE_ROTATE_270 with DRM_MODE_ROTATE_90 in `drm.cpp` fix it?
> 
> We could definitely expose more rotation params if that fixes it for you.

That worked!!! I changed to 90 and now it's working.

**Comment by ruineka** [comment]
The touchscreen inputs appear to be off now though. They were correct in the upsidedown direction. Up is down, down is up etc.

**Comment by Joshua-Ashton** [comment]
That's to be expected, I can do a proper fix tomorrow.

**Comment by ruineka** [comment]
> That's to be expected, I can do a proper fix tomorrow.

Awesome, I appreciate it!

**Comment by Joshua-Ashton** [comment]
Hm, can add a workaround for rotated displays for now potentially, but ideally we'd want to get this from the drm display prop eventually

**Comment by ruineka** [comment]
> Hm, can add a workaround for rotated displays for now potentially, but ideally we'd want to get this from the drm display prop eventually

It's worth noting OneXPlayer and I believe GPD Win devices have a tendency of having incomplete EDID's configured with their displays so having options to manually rotate and add supported resolutions for these circumstances would be beneficial. With X11 on ChimeraOS we had to manually add resolutions using xrandr to get the steam compositor to work correctly.

For example my OneXPlayer's EDID only lists 1600x2560 as a compatible resolution and other units list more complete options.

Not sure whats different with Wayland's approach, but it lists the resolutions correctly. I can upload my EDID if it helps any.

**Comment by Joshua-Ashton** [comment]
IIRC, rotation is not a part of EDID. It's in some extended thing.

It's more likely that it'll need to set the panel orientation quirk in the kernel for the display or something to solve this properly.

**Comment by ruineka** [comment]
> IIRC, rotation is not a part of EDID. It's in some extended thing.
> 
> It's more likely that it'll need to set the panel orientation quirk in the kernel for the display or something to solve this properly.

The OneXPlayer has a kernel orientation quirk as of 5.17, but in some instances this is ignored. Gamescope was one of the instances that ignored it.

Patch: https://lkml.org/lkml/2022/1/12/989
Kernel git: https://github.com/torvalds/linux/blob/master/drivers/gpu/drm/drm_panel_orientation_quirks.c

Pop OS 21.10 with updates and 22.04 does not require any rotation because in landscape it is correct.

Holos KDE is sideways (Steam Deck distro clone) and attempting to rotate the display results in a black screen with a cursor only.

**Comment by ruineka** [comment]
I rotated the touchscreen inputs with the display by making use of DRM_MODE_PANEL_ORIENTATION_LEFT_UP instead of DRM_MODE_ROTATE, but now I have to figure out how to get the touch inputs not to act like a trackpad (dragging the screen to move the cursor). Any ideas?

**Comment by jxu91** [comment]
> The touchscreen inputs appear to be off now though. They were correct in the upsidedown direction. Up is down, down is up etc.

Find a very dirty way to fix the touch orientation issue, just add 
`x = 1280 - x;
y = 800 - y;`
in the wlserver_handle_touch_motion and wlserver_handle_touch_down function of wlserver.cpp for AMD OneXPlayer mini. Adjust the parameters may fit other machines. Works on my AMD OneXPlayer mini.  May be a temporary method

**Comment by ruineka** [comment]
> > The touchscreen inputs appear to be off now though. They were correct in the upsidedown direction. Up is down, down is up etc.
> 
> Find a very dirty way to fix the touch orientation issue, just add `x = 1280 - x; y = 800 - y;` in the wlserver_handle_touch_motion and wlserver_handle_touch_down function of wlserver.cpp for AMD OneXPlayer mini. Adjust the parameters may fit other machines. Works on my AMD OneXPlayer mini. May be a temporary method

Useful find, definitely will be making use of this until the official fix is out. Thanks for the information!

**Comment by ruineka** [comment]
> > The touchscreen inputs appear to be off now though. They were correct in the upsidedown direction. Up is down, down is up etc.
> 
> Find a very dirty way to fix the touch orientation issue, just add 
> `x = 1280 - x;
> y = 800 - y;`
> in the wlserver_handle_touch_motion and wlserver_handle_touch_down function of wlserver.cpp for AMD OneXPlayer mini. Adjust the parameters may fit other machines. Works on my AMD OneXPlayer mini.  May be a temporary method

I tested this on my mini and it didn't work. I must be placing it in the wrong place perhaps? Are you able to share a snippet of the functions?

**Comment by jxu91** [comment]
> > > The touchscreen inputs appear to be off now though. They were correct in the upsidedown direction. Up is down, down is up etc.
> > 
> > 
> > Find a very dirty way to fix the touch orientation issue, just add
> > `x = 1280 - x; y = 800 - y;`
> > in the wlserver_handle_touch_motion and wlserver_handle_touch_down function of wlserver.cpp for AMD OneXPlayer mini. Adjust the parameters may fit other machines. Works on my AMD OneXPlayer mini.  May be a temporary method
> 
> I tested this on my mini and it didn't work. I must be placing it in the wrong place perhaps? Are you able to share a snippet of the functions?

I place the code as below in both wlserver_handle_touch_motion and wlserver_handle_touch_down function. I reinstalled ChimeraOS 33 with the OXP-90 branch of your gamescope-onexplayer fork and it consistently worked
`static void wlserver_handle_touch_down(struct wl_listener *listener, void *data)
{
	struct wlserver_touch *touch = wl_container_of( listener, touch, down );
	struct wlr_event_touch_down *event = (struct wlr_event_touch_down *) data;

	if ( wlserver.mouse_focus_surface != NULL )
	{
		double x = g_bRotated ? event->y : event->x;
		double y = g_bRotated ? 1.0 - event->x : event->y;

		x *= g_nOutputWidth;
		y *= g_nOutputHeight;

		x += focusedWindowOffsetX;
		y += focusedWindowOffsetY;

		x *= focusedWindowScaleX;
		y *= focusedWindowScaleY;

		x = 1280 - x;
		y = 800 - y;

		wlserver.mouse_surface_cursorx = x;
		wlserver.mouse_surface_cursory = y;`

**Comment by ruineka** [comment]
> > > > The touchscreen inputs appear to be off now though. They were correct in the upsidedown direction. Up is down, down is up etc.
> > > 
> > > 
> > > Find a very dirty way to fix the touch orientation issue, just add
> > > `x = 1280 - x; y = 800 - y;`
> > > in the wlserver_handle_touch_motion and wlserver_handle_touch_down function of wlserver.cpp for AMD OneXPlayer mini. Adjust the parameters may fit other machines. Works on my AMD OneXPlayer mini.  May be a temporary method
> > 
> > I tested this on my mini and it didn't work. I must be placing it in the wrong place perhaps? Are you able to share a snippet of the functions?
> 
> I place the code as below in both wlserver_handle_touch_motion and wlserver_handle_touch_down function. I reinstalled ChimeraOS 33 with the OXP-90 branch of your gamescope-onexplayer fork and it consistently worked
> 
> 
> 
> static void wlserver_handle_touch_down(struct wl_listener *listener, void *data)
> {
> 	struct wlserver_touch *touch = wl_container_of( listener, touch, down );
> 	struct wlr_event_touch_down *event = (struct wlr_event_touch_down *) data;
> 
> 	if ( wlserver.mouse_focus_surface != NULL )
> 	{
> 		double x = g_bRotated ? event->y : event->x;
> 		double y = g_bRotated ? 1.0 - event->x : event->y;
> 
> 		x *= g_nOutputWidth;
> 		y *= g_nOutputHeight;
> 
> 		x += focusedWindowOffsetX;
> 		y += focusedWindowOffsetY;
> 
> 		x *= focusedWindowScaleX;
> 		y *= focusedWindowScaleY;
> 
> 		x = 1280 - x;
> 		y = 800 - y;
> 
> 		wlserver.mouse_surface_cursorx = x;
> 		wlserver.mouse_surface_cursory = y;
> ......
> 

Thanks that ended up working. It also works on the 1600p unit as well since Steam defaults to 800p. With a specified resolution set for gamescope-session I'd imagine this value would need to match what the user puts there.

**Comment by jxu91** [comment]
> > > > > The touchscreen inputs appear to be off now though. They were correct in the upsidedown direction. Up is down, down is up etc.
> > > > 
> > > > 
> > > > Find a very dirty way to fix the touch orientation issue, just add
> > > > `x = 1280 - x; y = 800 - y;`
> > > > in the wlserver_handle_touch_motion and wlserver_handle_touch_down function of wlserver.cpp for AMD OneXPlayer mini. Adjust the parameters may fit other machines. Works on my AMD OneXPlayer mini.  May be a temporary method
> > > 
> > > 
> > > I tested this on my mini and it didn't work. I must be placing it in the wrong place perhaps? Are you able to share a snippet of the functions?
> > 
> > 
> > I place the code as below in both wlserver_handle_touch_motion and wlserver_handle_touch_down function. I reinstalled ChimeraOS 33 with the OXP-90 branch of your gamescope-onexplayer fork and it consistently worked
> > static void wlserver_handle_touch_down(struct wl_listener *listener, void *data)
> > {
> > struct wlserver_touch *touch = wl_container_of( listener, touch, down );
> > struct wlr_event_touch_down *event = (struct wlr_event_touch_down *) data;
> > if ( wlserver.mouse_focus_surface != NULL )
> > {
> > double x = g_bRotated ? event->y : event->x;
> > double y = g_bRotated ? 1.0 - event->x : event->y;
> > ```
> >   x *= g_nOutputWidth;
> >   y *= g_nOutputHeight;
> > 
> >   x += focusedWindowOffsetX;
> >   y += focusedWindowOffsetY;
> > 
> >   x *= focusedWindowScaleX;
> >   y *= focusedWindowScaleY;
> > 
> >   x = 1280 - x;
> >   y = 800 - y;
> > 
> >   wlserver.mouse_surface_cursorx = x;
> >   wlserver.mouse_surface_cursory = y;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ......
> 
> Thanks that ended up working. It also works on the 1600p unit as well since Steam defaults to 800p. With a specified resolution set for gamescope-session I'd imagine this value would need to match what the user puts there.

Glad to hear that. I knew the lack of customization part in this code, however my major is biology and just learned a little coding by my self, so I don't know how to complete the self-adapting part to the resolution. Maybe you can help making the touch screen perfect on other resolutions.

**Comment by ruineka** [comment]
> > > > > > The touchscreen inputs appear to be off now though. They were correct in the upsidedown direction. Up is down, down is up etc.
> > > > > 
> > > > > 
> > > > > Find a very dirty way to fix the touch orientation issue, just add
> > > > > `x = 1280 - x; y = 800 - y;`
> > > > > in the wlserver_handle_touch_motion and wlserver_handle_touch_down function of wlserver.cpp for AMD OneXPlayer mini. Adjust the parameters may fit other machines. Works on my AMD OneXPlayer mini.  May be a temporary method
> > > > 
> > > > 
> > > > I tested this on my mini and it didn't work. I must be placing it in the wrong place perhaps? Are you able to share a snippet of the functions?
> > > 
> > > 
> > > I place the code as below in both wlserver_handle_touch_motion and wlserver_handle_touch_down function. I reinstalled ChimeraOS 33 with the OXP-90 branch of your gamescope-onexplayer fork and it consistently worked
> > > static void wlserver_handle_touch_down(struct wl_listener *listener, void *data)
> > > {
> > > struct wlserver_touch *touch = wl_container_of( listener, touch, down );
> > > struct wlr_event_touch_down *event = (struct wlr_event_touch_down *) data;
> > > if ( wlserver.mouse_focus_surface != NULL )
> > > {
> > > double x = g_bRotated ? event->y : event->x;
> > > double y = g_bRotated ? 1.0 - event->x : event->y;
> > > ```
> > >   x *= g_nOutputWidth;
> > >   y *= g_nOutputHeight;
> > > 
> > >   x += focusedWindowOffsetX;
> > >   y += focusedWindowOffsetY;
> > > 
> > >   x *= focusedWindowScaleX;
> > >   y *= focusedWindowScaleY;
> > > 
> > >   x = 1280 - x;
> > >   y = 800 - y;
> > > 
> > >   wlserver.mouse_surface_cursorx = x;
> > >   wlserver.mouse_surface_cursory = y;
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ......
> > 
> > Thanks that ended up working. It also works on the 1600p unit as well since Steam defaults to 800p. With a specified resolution set for gamescope-session I'd imagine this value would need to match what the user puts there.
> 
> Glad to hear that. I knew the lack of customization part in this code, however my major is biology and just learned a little coding by my self, so I don't know how to complete the self-adapting part to the resolution. Maybe you can help making the touch screen perfect on other resolutions.

Sure no problem. I'm currently studying C++ now and experimenting with gamescope to learn the ropes myself. We'll get it figured out. :)

**Comment by gfl699468** [comment]
> > > > > The touchscreen inputs appear to be off now though. They were correct in the upsidedown direction. Up is down, down is up etc.
> > > > 
> > > > 
> > > > Find a very dirty way to fix the touch orientation issue, just add
> > > > `x = 1280 - x; y = 800 - y;`
> > > > in the wlserver_handle_touch_motion and wlserver_handle_touch_down function of wlserver.cpp for AMD OneXPlayer mini. Adjust the parameters may fit other machines. Works on my AMD OneXPlayer mini.  May be a temporary method
> > > 
> > > 
> > > I tested this on my mini and it didn't work. I must be placing it in the wrong place perhaps? Are you able to share a snippet of the functions?
> > 
> > 
> > I place the code as below in both wlserver_handle_touch_motion and wlserver_handle_touch_down function. I reinstalled ChimeraOS 33 with the OXP-90 branch of your gamescope-onexplayer fork and it consistently worked
> > static void wlserver_handle_touch_down(struct wl_listener *listener, void *data)
> > {
> > struct wlserver_touch *touch = wl_container_of( listener, touch, down );
> > struct wlr_event_touch_down *event = (struct wlr_event_touch_down *) data;
> > if ( wlserver.mouse_focus_surface != NULL )
> > {
> > double x = g_bRotated ? event->y : event->x;
> > double y = g_bRotated ? 1.0 - event->x : event->y;
> > ```
> >   x *= g_nOutputWidth;
> >   y *= g_nOutputHeight;
> > 
> >   x += focusedWindowOffsetX;
> >   y += focusedWindowOffsetY;
> > 
> >   x *= focusedWindowScaleX;
> >   y *= focusedWindowScaleY;
> > 
> >   x = 1280 - x;
> >   y = 800 - y;
> > 
> >   wlserver.mouse_surface_cursorx = x;
> >   wlserver.mouse_surface_cursory = y;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ......
> 
> Thanks that ended up working. It also works on the 1600p unit as well since Steam defaults to 800p. With a specified resolution set for gamescope-session I'd imagine this value would need to match what the user puts there.

should update those lines

> double x = g_bRotated ? event->y : event->x;
> double y = g_bRotated ? 1.0 - event->x : event->y;

to 

> double x = g_bRotated ? 1.0 - event->y : event->x;
> double y = g_bRotated ? event->x : event->y;

resolution will be handled by next few lines, hardcode resolution is unnecessary

>   x *= g_nOutputWidth;
>   y *= g_nOutputHeight;

**Comment by ruineka** [comment]
> 

I tested this with the 800p mini and it worked well. I also tested on the 1600 Intel unit where hard coding 800p worked and it didn't seem to work. It's possible I made a mistake, I'll look at this when I get off work. The code I used is called branch "another-experiment-intel" at my fork of gamescope.

**Comment by rapenne-s** [comment]
this can be closed :+1: as `--force-orientation` has been added

**Comment by ruineka** [comment]
> this can be closed :+1: as `--force-orientation` has been added

I didn't realize it was even still open. I'm the one who did the PR too 😂.
