### ISSUE TITLE
Allow multiple refresh rates for display modes outside of the max reported display mode in-game.

### ISSUE THREAD

**Issue by isaboll1** [ValveSoftware/gamescope#460]
When using gamescope with the `-h` and `-w` options, I've found that it only allows the supported monitor refresh rates in-game when the game is utilizing the resolution that was used for the command-line option. So for example if i'm using a 1920x1080p 165hz monitor, but I set the virtual display resolution through gamescope to be 2160x1440, in-game the max refresh rate for any resolution besides 1440p would be 60Hz, instead of the 165Hz of the monitor, even for the 1920x1080p resolution option in-game.

Since gamescope doesn't touch the physical monitor's display mode properties, and only sets an internal virtual monitor's properties with respect to refresh rates and resolution, it would be nice if gamescope reported the same set of refresh rates up to the actual used refresh rate of the physical monitor, throughout all of the virtual resolution/display modes reported to the game that is running.

**Comment by Joshua-Ashton** [comment]
There is a refresh option, (-r), but I agree we should default to native refresh rate when not set.

**Comment by ilievi187** [comment]
Hello Joshua i have a problem , when i use the AMD FSR my refresh rate is halved. I have 200hz monitor and when i enable AMD FSR my refresh rate is become 100hz ,if there is no FSR no refresh problem i test it out

**Comment by isaboll1** [comment]
Addressed since Steam Deck was supported with refresh rate switching
