### ISSUE TITLE
Stuttering observed with games that enforce an FPS lock.

### ISSUE THREAD

**Issue by isaboll1** [ValveSoftware/gamescope#575]
On both my personal PC with an RX 6600, as well as on the Steam Deck, I've noticed that there tends to be stuttering or latency, particularly with games that themselves enforce an FPS cap. Some examples of games that I tried that exhibit this behavior are fighting games such as Guilty Gear XRD Rev 2, Dragon Ball FighterZ, as well as games like Strider 2014, Metal Gear Rising: Revengence, and Batman Arkham Knight (however for Batman Arkham Knight, the issue goes away when you set the FPS cap to a higher number than the refresh rate, such as 90 when playing on a 60Hz screen) as well as Crosscode. This in particular doesn't seem to happen outside of gamescope, nor does it happen for games that don't seem to enforce arbitrary FPS caps. It seems to primarily apply to games with arbitrary fps caps that tie the game logic to the frame rate.

**Comment by mystrdat** [comment]
When using gamescope in Back 4 Blood, after a while I start experiencing extreme stuttering. The framerate in mangohud looks stable but the game turns unplayable.

**Comment by isaboll1** [comment]
Closing since this is tracking same issue https://github.com/ValveSoftware/gamescope/issues/847
