### ISSUE TITLE
Gamescope crash after using "Return to Gaming Mode" with external Monitor

### ISSUE THREAD

**Issue by kuhjunge** [ValveSoftware/gamescope#642]
My Steam Deck crashes (and verifying my installation on reboot) every time when I switch from Desktop Mode to Gaming Mode on my dock. 
I tried to troubleshoot the problem myself and found that my display (MSI Optix MPG321UR-QD connected via USB-C) is causing the problem.

I use SteamOS version: 3.3.2 (latest Beta). I have no Plugins installed in Gaming Mode and only (just now) 'gamescope-debug' installed on the Deskop Mode.

I added the log and a coredump:

[log.txt](https://github.com/Plagman/gamescope/files/9758697/log.txt)
[coredump.zip](https://github.com/Plagman/gamescope/files/9758706/coredump.zip)

Do you need any other information?

**Comment by deftdawg** [comment]
I'm also seeing this behavior with HoloISO on the same screen...  I think it's because gamescope is puking on the 144hz refresh rate...

In my `gamescope-session` this block appeared in the most recent update, if I comment it out everything works... 
```sh
# Plop GAMESCOPE_MODE_SAVE_FILE into $XDG_CONFIG_HOME (defaults to ~/.config).
export GAMESCOPE_MODE_SAVE_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/gamescope/modes.cfg"

# There is no way to set a color space for an NV12
# buffer in Wayland. And the color management protocol that is
# meant to let this happen is missing the color range...
# So just workaround this with an ENV var that Remote Play Together
# and Gamescope will use for now.
export GAMESCOPE_NV12_COLORSPACE=k_EStreamColorspace_BT601 

# Make path to gamescope mode save file.
mkdir -p "$(dirname "$GAMESCOPE_MODE_SAVE_FILE")"
touch "$GAMESCOPE_MODE_SAVE_FILE"
echo "Making Gamescope Mode Save file at \"$GAMESCOPE_MODE_SAVE_FILE\""
```

If I look at the `modes.cfg` config file it has this:
```
cat ~/.config/gamescope/modes.cfg 
Microstep MPG321UR-QD:3840x2160@144
```

**Comment by Joshua-Ashton** [comment]
@deftdawg can you grab a coredump from coredumpctl?

**Comment by deftdawg** [comment]
Attached is the core and backtrace that shows it dying in `drm_set_refresh`:

```
echo 'bt' | coredumpctl debug # echo "bt" | gdb --core=gamescope.core.2022-11-20 
...
GNU gdb (GDB) 12.1
...
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000056173d6b33eb in drm_set_refresh (drm=0x56173d773100 <g_DRM>, refresh=60) at ../src/drm.cpp:2315
2315            drmModeConnector *connector = drm->connector->connector;
[Current thread is 1 (Thread 0x7fa9077fe6c0 (LWP 1125))]
(gdb) #0  0x000056173d6b33eb in drm_set_refresh(drm_t*, int) (drm=0x56173d773100 <g_DRM>, refresh=60) at ../src/drm.cpp:2315
#1  paint_all(bool) (async=<optimized out>) at ../src/steamcompmgr.cpp:1885
#2  0x000056173d6c2851 in steamcompmgr_main(int, char**) (argv=<optimized out>, argc=<optimized out>) at ../src/steamcompmgr.cpp:5731
#3  steamCompMgrThreadRun(int, char**) (argc=<optimized out>, argv=<optimized out>) at ../src/main.cpp:607
#4  0x00007fa9220e02f3 in std::execute_native_thread_routine(void*) (__p=0x56173f7c5c40) at /usr/src/debug/gcc/libstdc++-v3/src/c++11/thread.cc:82
#5  0x00007fa921d9f8fd in  () at /usr/lib/libc.so.6
#6  0x00007fa921e21a60 in  () at /usr/lib/libc.so.6
(gdb) 
quit
```

[gamescope.core.2022-11-20.gz](https://github.com/Plagman/gamescope/files/10050549/gamescope.core.2022-11-20.gz)

**Comment by kuhjunge** [comment]
This seems to be fixed in the latest Steam Deck Beta.
