### ISSUE TITLE
[Feature Request] Add option to zoom rendered output ratio to fill display area ratio

### ISSUE THREAD

**Issue by SaltyBet** [ValveSoftware/gamescope#664]
For example, rendering at 16:9 ratio on a 8:5 ratio screen shows black bars on the top and on the bottom:

![16-9d](https://user-images.githubusercontent.com/66281060/201206094-ad192eaf-c0e6-4ae2-82b7-5f53a4c48d82.png)

The requested option should allow to zoom the 16:9 image to fill the 8:5 display area, hiding a bit of the left and right borders:

![8-5d](https://user-images.githubusercontent.com/66281060/201206119-638a00d3-d557-4732-806e-c06e91189607.png)

Ideally, this option should be available for both locally installed games as well as streamed games.

Finally, arbitrary render/display ratio settings for any available display would be nice.

EDIT: Updated images for clarity.

EDIT 2: Fix small 8:5 image snafu.

EDIT 3: OCD Fix.

**Comment by RyuSeisuke1992** [comment]
I think the developers are already working on a solution. Why some games don't support widescreen is a mystery to me. Every current engine must have that as a standard
https://github.com/Plagman/gamescope/commit/a7203603fe2fab3b8d5bb40c317dfe049e6f5d75

**Comment by SaltyBet** [comment]
> I think the developers are already working on a solution.

Thanks for the info, @RyuSeisuke1992. Will keep an eye out for when the feature becomes available.

> Why some games don't support widescreen is a mystery to me. Every current engine must have that as a standard

Yes, it is baffling, even more so, considering many of those modern engines can run on all kinds of mobile devices, with the myriad crazy display aspect ratios available on such a vast market...

**Comment by Joshua-Ashton** [comment]
This is available in SteamOS 3.4 beta in Gamescope -- the UI on the Steam side isn't hooked up though.

**Comment by RyuSeisuke1992** [comment]
@Joshua-Ashton Does that mean you can already test it out?

**Comment by Joshua-Ashton** [comment]
Not easily without setting the properties manually.

**Comment by sawb** [comment]
Is there any way to do this right now on desktop with the latest gamescope? Not sure how to set the upscaler to stretch.

**Comment by RyuSeisuke1992** [comment]
I think soon this feature should be available via power menu bar
You still have to give time to the developers

**Comment by SaltyBet** [comment]
This was implemented a long time ago, and I did not update this Issue, sorry for the delay.

Thanks to the Valve team for implementing this.

Cheers.
