### ISSUE TITLE
Gamescope resolution issue with title THUG Pro

### ISSUE THREAD

**Issue by Kevman95** [ValveSoftware/gamescope#672]
Hello,

I am having a resolution issue with gamescope with this specific title on Steam Deck. When its set to its default resolution for the deck (1280×800) and the game itself is set to that resolution in its launcher settings, it isn't actually displaying it properly. It displays it all cropped.

If i use the Steam deck desktop mode without gamescope in the way, it displays at the intended resolution.

Inside gamescopes window (ran it on desktop mode with gamescope -w 1280 -h 800 -- %command%) 
https://kevman95.com/i/2022-11-17_08-08-14_183d816c-3773-4cbd-ab64-f55ca6bf0515.png

Regular (without gamescope): https://kevman95.com/i/2022-11-17_08-09-57_4021251d-fba9-4dab-9a8e-1c0b6641fc6d.png

Games launcher settings: https://kevman95.com/i/2022-11-17_08-09-23_541003ca-3b97-41a7-bba0-81fede7edd04.png

Any tips?

EDIT: The only work-around to have this title appear properly within gamescope/gamemode on the Steam Deck ive found is to set the resolution in the shortcut properties to 1920x1080 for both internal/external, then set the game launcher resolution properties to 1600x900. This allows the game to be displayed, but with black bars on the top/bottom.

**Comment by Kevman95** [comment]
Oh wow! Actually is fixed!

**Comment by parkerlreed** [comment]
:tada: Thank you! Had not booted the game in a while due to the resolution bug.

**Comment by kisak-valve** [comment]
Closing per the last handful of comments.
