### ISSUE TITLE
Improper Scaling with Ares Emulator

### ISSUE THREAD

**Issue by Sterophonick** [ValveSoftware/gamescope#686]
When using the Ares emulator with the `--fullscreen` flag or pressing the F11 key will lead to improper scaling.

Expected behavior: Game window scales to entire vertical resolution.
Actual behavior: Small window of game on the top left of the Gamescope display.

![image](https://user-images.githubusercontent.com/34801996/204420332-f4296875-3864-47b5-b6e2-514eb23c3631.png)

Screenshot is of a nested instance, but this also happens in embedded.

Gamescope version: `gamescope-git 3.11.49.r23.g48ba04f-1`

**Comment by DocMAX** [comment]
same with yuzu

**Comment by Joshua-Ashton** [comment]
Wonder if https://github.com/Plagman/gamescope/commit/10ca15cc1c4a3c2ae7ecfeb872bb7399ae9cceeb helps.

**Comment by Sterophonick** [comment]
Not fixed unfortunately.

**Comment by Sterophonick** [comment]
Tested https://github.com/Plagman/gamescope/commit/d3ce381ff46ee0a88709c5b37609889fd6dcee42, not fixed.

**Comment by Sterophonick** [comment]
Fixed in Ares with https://github.com/ares-emulator/ares/commit/d13715d8bb252ba89b377d0630ad8a956be198a3.

Closing.
