### ISSUE TITLE
meson.build:33:0: ERROR: Dependency "hwdata" not found, tried pkgconfig and cmake

### ISSUE THREAD

**Issue by nebadon2025** [ValveSoftware/gamescope#731]
I can not get the latest gamescope code to compile on Ubuntu 22.10

```
nebadon@BIFROST:~/install/gamescope$ meson build/
The Meson build system
Version: 0.62.2
Source dir: /home/nebadon/install/gamescope
Build dir: /home/nebadon/install/gamescope/build
Build type: native build
Project name: gamescope
Project version: undefined
C compiler for the host machine: cc (gcc 11.3.0 "cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0")
C linker for the host machine: cc ld.bfd 2.38
C++ compiler for the host machine: c++ (gcc 11.3.0 "c++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0")
C++ linker for the host machine: c++ ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C++ supports arguments -Wno-unused-parameter: YES 
Compiler for C++ supports arguments -Wno-missing-field-initializers: YES 
Compiler for C++ supports arguments -Wno-c99-designator: NO 
Compiler for C++ supports arguments -Wno-invalid-offsetof: YES 
Compiler for C++ supports arguments -Wno-unused-const-variable: YES 
Found pkg-config: /usr/bin/pkg-config (1.8.0)
Run-time dependency libpipewire-0.3 found: YES 0.3.63
Library rt found: YES
Found CMake: /usr/bin/cmake (3.22.1)
Run-time dependency hwdata found: NO (tried pkgconfig and cmake)

meson.build:33:0: ERROR: Dependency "hwdata" not found, tried pkgconfig and cmake

A full log can be found at /home/nebadon/install/gamescope/build/meson-logs/meson-log.txt

```
[meson-log.txt](https://github.com/Plagman/gamescope/files/10326813/meson-log.txt)

**Comment by eli-schwartz** [comment]
> I can not get the latest gamescope code to compile on Ubuntu 22.10

It very clearly says the problem -- you're missing a dependency that you need to install.

But also, see #632

**Comment by charmandercha** [comment]
I have this problem too, but that packages is installed by synpatic.

**Comment by strycore** [comment]
I managed to workaround this by cloning hwdata from github and running make && sudo make install

**Comment by magicalraccoon** [comment]
I'm also facing this issue on pop_os. I have hwdata installed through the package manager, but meson doesn't seem to be recognizing it.

@strycore could you please post the exact steps to your workaround?

**Comment by strycore** [comment]
@magicalraccoon I've run the following:

```
sudo apt install libx11-xcb-dev libxdamage-dev libxcomposite-dev libxtst-dev
git clone https://github.com/vcrhonek/hwdata.git
cd hwdata
./configure
make
sudo make install
```

Then when running `meson build/` again in the gamescope folder, it fails with a version mismatch for libdrm: 

```
Dependency libdrm found: NO found 2.4.110 but need: '>= 2.4.113'
Run-time dependency libdrm found: NO (tried cmake)

src/meson.build:11:0: ERROR: Invalid version of dependency, need 'libdrm' ['>= 2.4.113'] found '2.4.110'.
```

I'm not sure there is an easy way to build gamescope on Pop OS 22.04 sadly...

**Comment by magicalraccoon** [comment]
Cheers @strycore, some progress! But I'm running into the same problem with Vulkan, despite having it installed

```
hackoon@pop-os:~/git-content/gamescope$ meson build/
The Meson build system
Version: 0.61.2
Source dir: /home/hackoon/git-content/gamescope
Build dir: /home/hackoon/git-content/gamescope/build
Build type: native build
Project name: gamescope
Project version: undefined
C compiler for the host machine: cc (gcc 11.3.0 "cc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0")
C linker for the host machine: cc ld.bfd 2.38
C++ compiler for the host machine: c++ (gcc 11.3.0 "c++ (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0")
C++ linker for the host machine: c++ ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C++ supports arguments -Wno-unused-parameter: YES 
Compiler for C++ supports arguments -Wno-missing-field-initializers: YES 
Compiler for C++ supports arguments -Wno-c99-designator: NO 
Compiler for C++ supports arguments -Wno-invalid-offsetof: YES 
Compiler for C++ supports arguments -Wno-unused-const-variable: YES 
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency libpipewire-0.3 found: YES 0.3.63
Library rt found: YES
Run-time dependency hwdata found: YES 0.366
Run-time dependency x11 found: YES 1.7.5
Run-time dependency vulkan found: NO (tried pkgconfig and system)

meson.build:36:0: ERROR: Dependency "vulkan" not found, tried pkgconfig and system

A full log can be found at /home/hackoon/git-content/gamescope/build/meson-logs/meson-log.txt
```

**Comment by strycore** [comment]
that should be resolved by installing libvulkan-dev 
If there is another missing dependency, it's usually in a package called lib<name-of-missing-thing>-dev

**Comment by magicalraccoon** [comment]
You're the best @strycore !

But I can't seem to get `wayland-scanner` to be recognized now. I installed `librust-wayland-scanner-dev` as you suggested, but it's still  failing.

**Comment by eli-schwartz** [comment]
wayland-scanner is not provided by rust-wayland-scanner, neither with nor without a "lib" prefix and "-dev" suffix.

**Comment by eli-schwartz** [comment]
When Meson prints a message about a "dependency", it is usually looking for a file called `[name-of-missing-dep].pc`, on Debian-based distributions such as Ubuntu or Pop!_OS you can generally find what package provides that file using the `apt-file search <filename>` command.

```
apt-file search wayland-scanner.pc
```

This will either report:
- nothing found, in which case you may need to guess at other likely package names (such as the heuristic lib{name}-dev suggestion) because meson *can* use cmake as a fallback search, or also implement custom library lookups for a handful of dependencies.
- or, most commonly, it will report the exact package name that is 100% guaranteed to contain a file named `wayland-scanner.pc`, which means there is no longer any guesswork -- that package, no matter what it's called, is definitely what you want


I'm not on a Debian-based system, so I cannot actually run that command. But I did do the next-best thing: I went to https://www.debian.org/distrib/packages and scrolled down to "Search the contents of packages", and ran the same search. It produced a match for https://packages.debian.org/bullseye/libwayland-dev

**Comment by magicalraccoon** [comment]
@eli-schwartz appreciate the `apt-file` tip, I just ran a regular search before that. I've included the missing dependencies, but now I'm at the `libdrm` versioning problem listed before: https://github.com/Plagman/gamescope/issues/731#issuecomment-1383009603

**Comment by eli-schwartz** [comment]
Yeah, updating the version of a system-installed library can be a bit fiddly...

You can run `meson wrap install libdrm` and it will install a https://wrapdb.mesonbuild.com version into your subprojects/ directory. Meson will then know how to build a private copy just for gamescope.

This is still a bit fiddly, because you don't want to overwrite your system version of libdrm, so you probably want to either build libdrm statically (`-Dlibdrm:default_library=static`) or install into a custom prefix.

**Comment by magicalraccoon** [comment]
Making progress, but I'm still getting stuck at
```
wlroots| Dependency wayland-protocols found: NO found 1.25 but need: '>=1.27' (cached)

subprojects/wlroots/protocol/meson.build:1:0: ERROR: Dependency 'wayland-protocols' is required but not found.
```

Looks like I have `1.25-1` with no option to upgrade any higher.

**Comment by strycore** [comment]
I'm hitting a similar error with 

```
Dependency wayland-server found: NO found 1.20.0 but need: '>=1.21'
Run-time dependency wayland-server found: NO (tried cmake)

src/meson.build:13:0: ERROR: Invalid version of dependency, need 'wayland-server' ['>=1.21'] found '1.20.0'.
```
Neither wayland-server nor wayland-protocols are recent enough in wrapdb.

My suggestion would be to checkout a version of gamescope from April 2022, which is what I'm using on my main gaming machine. Hopefully, the next release of Pop OS will have a version of Wayland recent enough to build gamescope.

**Comment by raziel100** [comment]
> I'm hitting a similar error with
> 
> ```
> Dependency wayland-server found: NO found 1.20.0 but need: '>=1.21'
> Run-time dependency wayland-server found: NO (tried cmake)
> 
> src/meson.build:13:0: ERROR: Invalid version of dependency, need 'wayland-server' ['>=1.21'] found '1.20.0'.
> ```
> 
> Neither wayland-server nor wayland-protocols are recent enough in wrapdb.
> 
> My suggestion would be to checkout a version of gamescope from April 2022, which is what I'm using on my main gaming machine. Hopefully, the next release of Pop OS will have a version of Wayland recent enough to build gamescope.

you can bypass the wayland-server, building from [git](https://wayland.freedesktop.org/building.html) and build wayland and Wayland protocols and you're ready to go

**Comment by charmandercha** [comment]
I tried to compile wayland but i get some error, sadly.

I still use a gamescope version that i compiled months ago

**Comment by raziel100** [comment]
> I tried to compile wayland but i get some error, sadly.
> 
> I still use a gamescope version that i compiled months ago

Well. I have successfully compile wayland and all dependency from it and compile successfully gamescope in popOS 22.04 lts. It's just to get every package saying is missing when in make and installing it one by one.

**Comment by strycore** [comment]
I've compiled all the information from this thread in a script, I'm missing the part where we tell gamescope to use the locally built wayland server.

It still fails with this error:
```src/meson.build:13:0: ERROR: Dependency lookup for wayland-server with method 'pkgconfig' failed: Invalid version, need 'wayland-server' ['>=1.21'] found '1.20.0'.```

[build-gamescope.txt](https://github.com/Plagman/gamescope/files/10462759/build-gamescope.txt)

**Comment by akdor1154** [comment]
I have packaged gamescope for Ubuntu/Pop 22.04 by pulling in new libdrm etc from Debian Sid and vendoring them. Packages at https://github.com/akdor1154/gamescope-pkg .

**Comment by ar-lex** [comment]
I've managed to build recent gamescope for both Ubuntu 22.04 and 22.10 in [my PPA](https://launchpad.net/~ar-lex/+archive/ubuntu/gamescope). I used git snapshot because latest commits seem to be more stable and organized than version 3.11.51.

All the needed dependencies including `libdisplay-info` and `vkroots` are also packaged here, so VR and HDR features are enabled during build. Newer libraries are backward compatible and shouldn't break system dependencies - I ran gamescope and KDE Plasma Wayland sessions in Ubuntu 22.10 without any issue, haven't tested in 22.04 though.

Regarding this issue - I think it should be closed. It's a distribution-specific incompatibility, not a gamescope bug.

**Comment by gbaraldi** [comment]
@ar-lex on your ppa with pop-os (similar to ubuntu 22.04) I get the following error
> The following packages have unmet dependencies.
 gamescope : Depends: libdrm2 (>= 2.4.113) but 2.4.110-1pop0~1648761328~22.04~166056a is to be installed
             Depends: libwlroots11 (>= 0.16.0) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

Is there something one can do here?

**Comment by ar-lex** [comment]
@gbaraldi probably some packages in Pop!_OS are [held back](https://manpages.ubuntu.com/manpages/bionic/man8/apt-mark.8.html), idk why, there were multiple reports about it. You can see which packages are held back with the following command
```
dpkg --get-selections | grep hold
```
Normally there is no such packages. You can cancel the hold by running
```
sudo apt-mark unhold <package>
```
for all or just for problematic packages. Then the installation of gamescope should be correct.

**Comment by gbaraldi** [comment]
The package isn't held, it sees that version of libdrm as the latest oddly enough.

**Comment by ar-lex** [comment]
@gbaraldi if I understood correctly, Pop!_OS has [highest priority](https://github.com/pop-os/iso/blob/master/data/apt-preferences) for own apt repositories and libdrm2 package [is older](http://apt.pop-os.org/release/pool/jammy/libdrm/166056ac722c6b794b0c9f42ffbfee941d00778a/) in one these repos, while PPAs include [packages from jammy-updates repo](https://packages.ubuntu.com/jammy-updates/libdrm2) during build. If this is your case, you can try to add `/etc/apt/preferences.d/libdrm-updates` file with the following content:
```
Package: libdrm*
Pin: release a=pop-os-release
Pin-Priority: 500
```
to make the priorities lower for all `libdrm` packages from apt.pop-os.org.
After that these package should update via `sudo apt update && sudo apt upgrade`

**Comment by gbaraldi** [comment]
Thanks!, that worked (After I broke my gpu install twice, but it did 🥳 )

**Comment by nebadon2025** [comment]
I ended up installing hwdata manually from sid on to Ubuntu to get around this.

download latest here > https://packages.debian.org/sid/hwdata

install : `sude dpkg -i hwdata_0.368-1_all.deb`

**Comment by Thrane20** [comment]
+1 to the @nebadon2025 - this also worked for me. 
On a completely separate note, I've managed to containerize a full gamescope builder in a docker container. This worked for me -- your mileage may vary. You can take a look at how I achieved this in my docker file here: [https://github.com/Thrane20/dillinger/blob/main/docker/images/gamescope/Dockerfile]

**Comment by AAVVIronAlex** [comment]
For some reason I get a dependency error, but from what I understand I have hwdata, or are these "NO"s what it's talking about.

earthmapspictures@H-E-R-A-N:/mnt/BA6029B160297573/Downloads/gamescope/gamescope$ meson build/
The Meson build system
Version: 0.61.2
Source dir: /mnt/BA6029B160297573/Downloads/gamescope/gamescope
Build dir: /mnt/BA6029B160297573/Downloads/gamescope/gamescope/build
Build type: native build
Project name: gamescope
Project version: undefined
C compiler for the host machine: cc (gcc 11.4.0 "cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
C linker for the host machine: cc ld.bfd 2.38
C++ compiler for the host machine: c++ (gcc 11.4.0 "c++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
C++ linker for the host machine: c++ ld.bfd 2.38
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C++ supports arguments -Wno-unused-parameter: YES 
Compiler for C++ supports arguments -Wno-missing-field-initializers: YES 
Compiler for C++ supports arguments -Wno-c99-designator: NO 
Compiler for C++ supports arguments -Wno-invalid-offsetof: YES 
Compiler for C++ supports arguments -Wno-unused-const-variable: YES 
Compiler for C++ supports arguments -Wno-volatile: YES 
Compiler for C++ supports arguments -Wno-deprecated-volatile: NO 
Compiler for C++ supports arguments -Wno-ignored-qualifiers: YES 
Compiler for C++ supports arguments -Wno-missing-braces: YES 
Compiler for C++ supports arguments -ffast-math: YES 
Found pkg-config: /usr/bin/pkg-config (0.29.2)
Run-time dependency libpipewire-0.3 found: YES 0.3.84
Library rt found: YES
Found CMake: /usr/bin/cmake (3.22.1)
Run-time dependency hwdata found: NO (tried pkgconfig and cmake)

meson.build:41:0: ERROR: Dependency "hwdata" not found, tried pkgconfig and cmake

A full log can be found at /mnt/BA6029B160297573/Downloads/gamescope/gamescope/build/meson-logs/meson-log.txt

**Comment by Flashwalker** [comment]
> I'm also facing this issue on pop_os. I have hwdata installed through the package manager, but meson doesn't seem to be recognizing it.
I got the same
