### ISSUE TITLE
Starting with GDB gives wl_event_loop_dispatch failed

### ISSUE THREAD

**Issue by Joshua-Ashton** [ValveSoftware/gamescope#743]
This regressed at some point. Need to figure out why. Maybe wlroots 0.16 update?

**Comment by Joshua-Ashton** [comment]
First bad commit is 91fbb22bda68d069cb71aed589ef946ae61687ef which is the wlroots 0.16 update.

**Comment by emersion** [comment]
I can't reproduce, on my system I can run gamescope in gdb just fine…

**Comment by Joshua-Ashton** [comment]
Turns out this epoll_wait is failing https://gitlab.freedesktop.org/wayland/wayland/-/blob/main/src/event-loop.c#L1004 and getting EINTR.

Something is sending some signal under GDB which is causing this epoll_wait to be interrupted.

Not sure whether the interrupt should be handled on the libwayland or Gamescope side by checking errno though.
