### ISSUE TITLE
Validation Layer error affected by INTEL_DEBUG=norbc

### ISSUE THREAD

**Issue by nchery-intel** [ValveSoftware/gamescope#754]
Unless I use `INTEL_DEBUG=norbc`, I am seeing the following validation error when running `gamescope glxgears`:

> VUID-VkImageCreateInfo-imageCreateMaxMipLevels-02251(ERROR / SPEC):
>
> msgNum: -1094930823 - Validation Error: [ VUID-VkImageCreateInfo-imageCreateMaxMipLevels-02251 ]
>  
> Object 0: handle = 0x564aa34cdf30, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 0xbebcae79 | vkCreateImage():
>  
> Format VK_FORMAT_B8G8R8A8_UNORM is not supported for this combination of parameters and VkGetPhysicalDeviceImageFormatProperties returned back VK_ERROR_FORMAT_NOT_SUPPORTED.
>
> The Vulkan spec states: Each of the following values (as described in Image Creation Limits) must not be undefined : imageCreateMaxMipLevels, imageCreateMaxArrayLayers, imageCreateMaxExtent, and imageCreateSampleCounts (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkImageCreateInfo-imageCreateMaxMipLevels-02251)

Note that there are many other validation errors, but this one is the most interesting due to the impact that this environment variable has on https://github.com/Plagman/gamescope/issues/356.

From that message, it looks like the Intel driver tries to report that it doesn't support certain image properties with that format, but gamescope creates an image with that format and unsupported properties anyways.

Tested with:
* Intel Ice Lake
* mesa from git (sha `fe3b467eb9eddac8232d2cfa448813ddf948330a`)
* gamescope 3.11.51 and with gamescope built from git (sha `eff0ac0`)
* version 1.3.231.1 of the validation layers

**Comment by Samsagax** [comment]
Maybe this is related. When initializing formats the wayland server calls vulkan_init_formats that tryes to init all formats one by one by calling `vulkan_init_format()`. That function checks for `VK_ERROR_FORMAT_NOT_SUPPORTED` and returns `false` but the caller ignores that value:
https://github.com/Plagman/gamescope/blob/d3ce381ff46ee0a88709c5b37609889fd6dcee42/src/rendervulkan.cpp#L2626

Maybe the caller should look into formats that are supported and create the image with that one?

**Comment by djdeath** [comment]
Probably fixed by https://github.com/ValveSoftware/gamescope/commit/243582c0c7625577a2535c3363ae345de713f323 

@nchery-intel : please confirm, thanks

**Comment by nchery-intel** [comment]
I just tried to reproduce this. The validation error actually disappeared after I upgraded the Arch Linux package of the validation layer from version 1.3.250.0-2 -> 1.3.261.1-1.

With the latest gamescope, setting `INTEL_DEBUG=norbc` does not affect the validation layer output.

**Comment by Izaic** [comment]
While I don't get the error INTEL_DEBUG=norbc still does change whether I get artifacts or not on gamescope git (I also have mesa-git)

**Comment by djdeath** [comment]
> While I don't get the error INTEL_DEBUG=norbc still does change whether I get artifacts or not on gamescope git (I also have mesa-git)

Can you specify what platform you're using? Under X/wayland? Also with what application do you reproduce?

Thanks

**Comment by nchery-intel** [comment]
Should we continue this discussion in https://github.com/ValveSoftware/gamescope/issues/356?

**Comment by Izaic** [comment]
> > While I don't get the error INTEL_DEBUG=norbc still does change whether I get artifacts or not on gamescope git (I also have mesa-git)
> 
> Can you specify what platform you're using? Under X/wayland? Also with what application do you reproduce?
> 
> Thanks

Glxgears in Gamescope-git (3.13.19.r16.gd434d86-1) on Plasma Wayland 5.27.10 with Mesa 24.0.0-devel (git-c05261a7d8) on Arch Linux

Using the intel norbc flag fixes the artifacting at the cost of performance. Going without there is still artifacts.

**Comment by djdeath** [comment]
> Should we continue this discussion in #356?

Sure
