### ISSUE TITLE
1280x720?

### ISSUE THREAD

**Issue by DocMAX** [ValveSoftware/gamescope#805]
Can someone explain to me who is switching resolution 1600x900 to 1280x720 when starting a game with steam?
My command:
gamescope -e -W 1600 -H 900  --xwayland-count 2 -- steam ...

With DISPLAY=:2 xrandr i can see the switch to 720p resolution

**Comment by Joshua-Ashton** [comment]
-W is output resolution. -w is nested (game) resolution.

**Comment by lennie420** [comment]
Read the manual. "Defaults to 1280×720."

**Comment by DocMAX** [comment]
If i start gamescope with -H 1080 only Xwayland :1 is 1080, the second Xwayland :2 is max 720. So my games only run on 720. How to fix?

**Comment by DocMAX** [comment]
ok replaced -tenfoot with -gamepadui, that did it. steam is really complicated.

**Comment by Joshua-Ashton** [comment]
Steam has an option to control the size of the second XWayland in the game properties.

**Comment by DocMAX** [comment]
> Steam has an option to control the size of the second XWayland in the game properties.

yeah just found it thanks. seems it's not possible to set all games to native at once.
