### ISSUE TITLE
Dark souls 3 and elden ring bugs with mouse and keyboard

### ISSUE THREAD

**Issue by kassindornelles** [ValveSoftware/gamescope#830]
If you press the inventory button to change weapons or do anything else mouse moves a lot for a second when you leave inventory and is ultra annoying
That's on proton experimental and stable 

I use mouse and keyboard 
AMD GPU Rx 560

**Comment by kassindornelles** [comment]
Playing at 1080 native or fsr 720 doesn't matter both games get weird with gamescope

**Comment by RSerejo** [comment]
> If you press the inventory button to change weapons or do anything else mouse moves a lot for a second when you leave inventory and is ultra annoying That's on proton experimental and stable
> 
> I use mouse and keyboard AMD GPU Rx 560

send gamescope text are you using.
