### ISSUE TITLE
Wrong colors when use gamescope FSR upscaling

### ISSUE THREAD

**Issue by IDeathByte** [ValveSoftware/gamescope#850]
vkcube as example
Maybe it relative with latest HDR changes
with NIS upscaler i didn`t see problem

mesa-tkg-git-23.2.0_devel.170125.9a6b70da0bb
gamescope-git-3.11.52.beta6.r86.gc6d3ac7 (last commits for both)

![изображение](https://user-images.githubusercontent.com/41571062/233550304-08eaa9ad-b187-40b9-ba48-9e54d1054224.png)
![изображение](https://user-images.githubusercontent.com/41571062/233550412-5660c993-cf74-4c83-9fac-0a0e1923f068.png)

**Comment by Astrobald** [comment]
Same here, the color washing occurs when I switch the game to full screen, with FSR enabled.

**Comment by Joshua-Ashton** [comment]
Thanks for the report, I'll investigate this later today.

**Comment by Joshua-Ashton** [comment]
Should be fixed now.
