### ISSUE TITLE
Gamescope fails to run standalone in the TTY [bisected]

### ISSUE THREAD

**Issue by ruineka** [ValveSoftware/gamescope#852]
Attempting to run `gamescope -e -- steam -gamepadui` or the full command `gamescope -e -f --xwayland-count 2 -- steam -steamos3 -steamdeck -steampal -gamepadui` fails to run after recent commits.

I bisected the issue to this commit:

```
faee3be9def04a0493a4cb6359ce5b6b9202e1b1 is the first bad commit
commit faee3be9def04a0493a4cb6359ce5b6b9202e1b1
Author: Joshua Ashton <joshua@froggi.es>
Date:   Fri Mar 31 11:32:15 2023 +0100

    drm: Move to per-plane 3D LUT + Shaper
    
    Need to do some cleanup here and version checks before merging.

 src/drm.cpp          | 131 ++++++++++++++-------------------------------------
 src/drm.hpp          |   3 +-
 src/steamcompmgr.cpp |   2 +-
 3 files changed, 37 insertions(+), 99 deletions(-)
 ```

**Comment by brain-anti-freeze** [comment]
I experienced the same (although I bisected to an earlier commit).  I opened #854 which resolves it for me, might help your issue.  Are you on nvidia too ?

**Comment by ruineka** [comment]
> I experienced the same (although I bisected to an earlier commit).  I opened #854 which resolves it for me, might help your issue.  Are you on nvidia too ?

I'm using AMD, I'll look into your commit as well to see what it does for me.

**Comment by brain-anti-freeze** [comment]
Must be a different issue on AMD systems, sounds like your setup has some but not all of the required colour management  support. Does running with `--debug-layers` give any interesting log output ?

**Comment by DomiStyle** [comment]
Same issue here on an AMD GPU since the latest build from Nobara (3.11.52-5.git.20230421.c6d3ac7.fc38)

Here's the output of `gamescope --debug-layers -- vkcube`: https://gist.github.com/DomiStyle/55432d24afd411a0e99ef63467c3a3bd

**Comment by brain-anti-freeze** [comment]
@DomiStyle that looks similar to what I was getting - it reports `no VALVE1_CRTC_REGAMMA_TF support` but then tries to set it anyway.  Can you try the version from #854 ?

**Comment by DomiStyle** [comment]
@brain-anti-freeze Just tested, and it indeed works fine on that branch with AMD as well.

**Comment by brain-anti-freeze** [comment]
I've added a command line switch `--disable-color-management` to allow systems which do have the support to turn it off.  @BoukeHaarsma23 @ruineka does that prevent it crashing for you ? (Obviously without the hdr/color stuff working).

**Comment by ruineka** [comment]
> I've added a command line switch `--disable-color-management` to allow systems which do have the support to turn it off. @BoukeHaarsma23 @ruineka does that prevent it crashing for you ? (Obviously without the hdr/color stuff working).

I didn't need to use `--disable-color-management` because you had already fixed the issue with a previous commit.

**Comment by Joshua-Ashton** [comment]
Should be fixed in master now. Let me know if you are having more issues.

**Comment by ruineka** [comment]
> Should be fixed in master now. Let me know if you are having more issues.

Seems to have worked. Thanks for the fix!

**Comment by brain-anti-freeze** [comment]
> Should be fixed in master now. Let me know if you are having more issues.

Working great, thanks !
