### ISSUE TITLE
Warthunder: Mouse capture stops after "reaching" edge of screen

### ISSUE THREAD

**Issue by SkippTekk** [ValveSoftware/gamescope#877]
Not exactly where the logs are and what not. But here is my experience.

When im flying in warthunder, i would turn. then my mouse stops moving from side to side, causing me to either crash or die.

My way too "resolve" this issue is forcing the mouse back to the center of the screen by press L.ALT which pulls up the mouse to allow to move it around. BUT when i press the button my mouse is in the center. So not exactly what is going on with it. If i can produce a video i'll attach it. 

If anyone knows a way to fix this it would be great full.

current settings in Steam > Warthunder > General > Launch Options. **gamescope -W 1920 -H 1080 -b %command%**

Further verification. Does NOT happen in ground or flight tests. Only happens when im in a game against other players.

Video: https://www.youtube.com/watch?v=qgpBIvx8M68

**Comment by Joshua-Ashton** [comment]
Please try with `--force-grab-cursor`

**Comment by SkippTekk** [comment]
Added
**gamescope -W 1920 -H 1080 -b %command% --force-grab-cursor**

same result

**Comment by kisak-valve** [comment]
Hello @SkippTekk, I believe the intent was to pass --force-grab-cursor to gamescope, not the game, so that should be before %command%

**Comment by SkippTekk** [comment]
It didn't like it. so one second.

gamescope -W 1920 -H 1080 -b -force-grab-cursor %command%

and the game is running. testing it as i type this

**Comment by SkippTekk** [comment]
Just went in the air, and it still doesn't grab my mouse properly.

**Comment by nisehime** [comment]
>gamescope -W 1920 -H 1080 -b -force-grab-cursor %command%

It should be gamescope -W 1920 -H 1080 -b --force-grab-cursor %command% with double hyphen otherwise this option is ignored (maybe)

**Comment by SkippTekk** [comment]
Sorry, the game will not run with that line. **gamescope -W 1920 -H 1080 -b --force-grab-cursor -- %command%**

Game does the loading > start > crashs, i don't know where the logs are.

**Comment by SkippTekk** [comment]
Anymore ideas or nah?

**Comment by KczBen** [comment]
This is a game bug, unrelated to Gamescope. It happens when the chat window pops up in game, you can find more information about it on the game's bug tracker here: https://community.gaijin.net/issues/p/warthunder/i/mIu7lvCEUspl

**Comment by SkippTekk** [comment]
@KczBen gamescope does keep my mouse in check, but randomly stops and i gotta open the chat to correct it. Please have a look at the provided evidence at the start.

**Comment by KczBen** [comment]
@SkippTekk I did look at it, and looks like the same bug that most WarThunder players on Linux are experiencing right now. Notice how the issue went away when the chat faded out at 0:15 - the game can't capture the mouse properly while the chat window is on screen. It happens regardless of whether you use Gamescope, and the devs are aware of the issue.

**Comment by nisehime** [comment]
@SkippTekk does this issue present to you without gamescope in the first place?

**Comment by SkippTekk** [comment]
Correct, which is why i'm hoping that gamescope resolves this until it's actually fixed by the devs

**Comment by nisehime** [comment]
If it's not a gamescope bug, there's nothing to resolve

**Comment by SkippTekk** [comment]
I have had more progress using gamescope then not using it.

**Comment by xVanjaZ** [comment]
Disabling the chat from the settings seems to "solve" the issue.

![Screenshot from 2023-06-20 19-04-46](https://github.com/ValveSoftware/gamescope/assets/20064029/b06257d5-2046-47a5-851f-9129692b0b12)

**Comment by SkippTekk** [comment]
Kinda sucks that the chat is the issue... i like seeing people complain as i head shot them xD
