### ISSUE TITLE
Taking screenshots still appears broken with 3.12.0-beta8 on Steam Deck

### ISSUE THREAD

**Issue by JDGBOLT** [ValveSoftware/gamescope#887]
It looks like there was an attempted fix for taking screenshots in beta8, but it appears that the deck will still take straight black screenshots when beta8 is installed onto the steam deck itself with the current repository package. This does seem to be caused by the commit that changes rendering to be 10 bit by default at https://github.com/ValveSoftware/gamescope/commit/f6d9ef465dccafd8562b144bf259dee2db37f79e , as reverting this commit did in fact fix the screenshots getting taken as pure black. Just for reference this is on the main branch of steam os with the current beta client.

![PXL_20230527_200450672](https://github.com/ValveSoftware/gamescope/assets/791804/5128a667-9120-49ae-b622-222e635c708f)
![PXL_20230527_200410562 MP](https://github.com/ValveSoftware/gamescope/assets/791804/681ce079-28db-4b64-8e4d-917c9d8f060d)

**Comment by Joshua-Ashton** [comment]
Should be fixed with latest Gamescope.
