### ISSUE TITLE
System Shock (2023) crashes on start when running in gamescope with ENABLE_GAMESCOPE_WSI=1

### ISSUE THREAD

**Issue by DomiStyle** [ValveSoftware/gamescope#904]
I'm trying to play System Shock with HDR through gamescope but I can't get the game to launch with ENABLE_GAMESCOPE_WSI=1 set.

The game will crash on start with this message:

![Screenshot_20230630_112307](https://github.com/ValveSoftware/gamescope/assets/975131/db74f1b6-9624-499e-a103-e414fccf5c20)

I tried this in both nested and tty mode and it crashes in both.

This works:
`PROTON_LOG=1 gamescope -w 3440 -h 1440 -W 3440 -H 1440 --steam --fullscreen -- %command%`

This does not:
`PROTON_LOG=1 ENABLE_GAMESCOPE_WSI=1 gamescope -w 3440 -h 1440 -W 3440 -H 1440 --steam --fullscreen -- %command%`

Here's the proton log with WSI (crashing): 
[steam-482400-broken.log](https://github.com/ValveSoftware/gamescope/files/11915086/steam-482400-broken.log)

Here's the proton log without WSI (working): 
[steam-482400-working.log](https://github.com/ValveSoftware/gamescope/files/11915087/steam-482400-working.log)

The gamescope build is from the Nobara repo (3.11.52-6.git.20230627.e805c9c.fc38).

**Comment by GloriousEggroll** [comment]
Just noting that git commit e805c9c is wrong (i forgot to change it). It was actually built on 9b70b3b9e38057d51e0a0bdbccf68b36a7e751a4

**Comment by Joshua-Ashton** [comment]
Your Mesa is out of date.

**Comment by DomiStyle** [comment]
Launches with Mesa 23.2, thanks!
