### ISSUE TITLE
When using the `-U` argument

### ISSUE THREAD

**Issue by ZoomVA** [ValveSoftware/gamescope#922]
Whenever you add the `-U` argument to get FSR upscaling, it causes games to crash on launch. Sure you can wait until you're in game to turn the upscaling on, its just more for convenience sake.

**Comment by Astrobald** [comment]
There are a lot of changes in commit [7a1fe2d](https://github.com/ValveSoftware/gamescope/commit/7a1fe2def38e9c3ed4d12adb9f1bb81b6f9dcbe5).

You should use the new `-F fsr` flag to enable FSR and `--fsr-sharpness` (0 max to 20 min) to adjust the sharpness level.

`gamescope --help` for full list of options.

**Comment by ZoomVA** [comment]
Ah I've been using the `--fsr-sharpness` didn't know `-U` got changed to `-F `, thank you! Closing
