### ISSUE TITLE
gamescope no longer grabs mouse

### ISSUE THREAD

**Issue by dconz13** [ValveSoftware/gamescope#926]
Version 3.12.0-1 does not properly grab the cursor for games launched through gamescope. The gamescope instance is also rendered with a tool bar at the top rather than just a borderless window. If I use version 3.11.51 the mouse is properly captured (I have to alt tab to leave the window) and the gamescope instance defaults to a borderless window. 

Not sure if it makes a difference but the 3.12 version is installed through pacman and the 3.11.51 is the deprecated com.valvesoftware.Steam.Utility.gamescope flatpak still used by bottles. For 3.12 I am trying to launch through terminal / steam and seeing the issue. For 3.11.51 I'm launching games through bottles and getting the expected behavior. 

EDIT: I switched from a wayland session to x11 and the 3.12 version properly grabs the mouse. I think this issue is wayland related?

System specs:
OS: Arch Linux x86_64 
Host: B550M Steel Legend 
Kernel: 6.4.9-arch1-1 
DE: Plasma 5.27.7 
WM: kwin 
CPU: AMD Ryzen 5 5600X (12) @ 3.700GHz 
GPU: AMD ATI Radeon RX 7900 XT/7900 XTX 
Memory: 5439MiB / 32018MiB

**Comment by kisak-valve** [comment]
Hello @dconz13, this issue is already being tracked at #909. Since this issue report adds a bit more detail, I've gone ahead and transferred it to https://github.com/ValveSoftware/gamescope/issues/909#issuecomment-1673024871.
