### ISSUE TITLE
"Rubber-Banding" Mouse in 86box

### ISSUE THREAD

**Issue by Sterophonick** [ValveSoftware/gamescope#935]
Using Gamescope with 86box leads to the guest machine's mouse having this "Rubber banding" effect when captured, leading to an unusable pointer.

https://github.com/ValveSoftware/gamescope/assets/34801996/ffdc7535-e56c-457d-9f15-f97c1edeed79

In this video, I am moving the mouse back and forth horizontally. The mouse returns to _roughly_ its previous position after each swipe of the mouse.

Gamescope version:  3.12.3-1.1
86box version: 4.0 (Flatpak)

**Comment by Devorlon** [comment]
I've replicated this on my end too.

#### Gamescope 86Box Windows 98

https://github.com/ValveSoftware/gamescope/assets/19249443/3fad4c2e-fb85-4367-9917-4f9a021937ac

#### Gamescope 86Box Windows XP

https://github.com/ValveSoftware/gamescope/assets/19249443/49e34459-2c72-45c1-8748-233a9a52ed90

#### Native Gnome 86Box Windows 98

https://github.com/ValveSoftware/gamescope/assets/19249443/7656c597-5bad-4090-a926-47f0c5d007bf

#### Native Gnome 86Box Windows XP

https://github.com/ValveSoftware/gamescope/assets/19249443/22088440-1d0d-4315-8cff-5380881bd12a

<details open>
<summary>Specs / Versions</summary>

```
OS: Arch Linux [2023-09-12T19:41:36+0100]
gamescope: 3.12.5
Gnome: 44.4
Kernel: 6.4.12-arch
mesa-utils: 9.0.0
```

</details>

**Comment by Quackdoc** [comment]
Getting the same thing with qemu

**Comment by Sterophonick** [comment]
Currently no longer observing this behavior. Closing.
