### ISSUE TITLE
Gamescope thinks my refresh rate is 72Hz

### ISSUE THREAD

**Issue by NjlsShade** [ValveSoftware/gamescope#939]
If I enable VSync for a game in Gamescope it will lock the FPS to 72. Also, the FPS limiter (-r) does not seem to be working, as it does nothing. This affects Proton and native applications. It also appears that the gamescope window can not produce more than 72 fps, as if I set the fps in a given game to 144, mangohud will report 144fps, however, visually it is still 72fps.

Tested on Fedora 38 with an NVIDIA 3050 (laptop) using a single144Hz panel, no external displays attached. 

gamescope 3.12.3

**Comment by kisak-valve** [comment]
Hello @NjlsShade, this reads like a duplicate of #304. Please give the discussion on that issue report a read.

**Comment by NjlsShade** [comment]
Going to do some more testing and follow #304. Closing for now.

Thanks!
