### ISSUE TITLE
Fedora 39, Gnome 45: Trying gamescope results in reoccuring pop-up window "remote desktop" prompt, whenever mouse gets moved.

### ISSUE THREAD

**Issue by fakhraldin** [ValveSoftware/gamescope#970]
Affected version
        
      Fedora Linux 39
      Gnome 45       
      Mesa radv 23.2.0-rc3
      Kernel version 6.6.0-0.rc3.20230927gt0e945134.327.vanilla.fc39.x86_64

Bug summary
Starting a game with gamescope brings up a pop-up window "remote desktop" prompt, as soon as the mouse gets moved. Closing it does not help, because as soon as the mouse gets moved again even just slightly, that window prompt pops up again. This makes popular gamescope for games on gnome 45 completely useless. This behaviour shows up on all games, i've tested so far.

Steps to reproduce
In this example i used q2rtx, a 1GB sized demo freely available from [here](https://github.com/NVIDIA/Q2RTX/releases)

For possible hints read [here](https://gitlab.gnome.org/GNOME/mutter/-/issues/3047)

**Comment by Joshua-Ashton** [comment]
O_O

Is this with Gamescope master? Or on the latest stable release?

Can you take a picture of this prompt?

**Comment by fakhraldin** [comment]
Gamescope version 3.12.5 from the official Fedora 39 repositories. Here is a screenshot.
![Screenshot from 2023-09-24 13-34-32](https://github.com/ValveSoftware/gamescope/assets/86501302/3a641070-192b-45bd-9a65-9b7c52d0e185)

**Comment by Joshua-Ashton** [comment]
OK so this is before any of the new layer or forcing SDL_VIDEODRIVER wayland stuff... Great.

Idk what to say then, smells like a Gnome regression.

Does it still happen with Gamescope master?

**Comment by Joshua-Ashton** [comment]
Commented on the Gnome issue.

**Comment by Joshua-Ashton** [comment]
Not a Gamescope bug.
