### ISSUE TITLE
3.12.7 crash in present_wait_thread_func

### ISSUE THREAD

**Issue by q66** [ValveSoftware/gamescope#986]
After updating from 3.12.5 to 3.12.7, I'm getting a crash on gnome 45 wayland:

```
(lldb) bt
* thread #1, name = 'gamescope-wl', stop reason = signal SIGSEGV
  * frame #0: 0x0000000000000000
    frame #1: 0x0000564abaa43104 gamescope`present_wait_thread_func() at rendervulkan.cpp:2555:5
    frame #2: 0x0000564abaa155fa gamescope`void* std::__1::__thread_proxy[abi:v160006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (*)()>>(void*) [inlined] decltype(std::declval<void (*)()>()()) std::__1::__invoke[abi:v160006]<void (*)()>(__f=0x00007fb23f911e98) at invoke.h:394:23
    frame #3: 0x0000564abaa155f7 gamescope`void* std::__1::__thread_proxy[abi:v160006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (*)()>>(void*) [inlined] void std::__1::__thread_execute[abi:v160006]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (*)()>(__t=size=2, (null)=<unavailable>) at thread:282:5
    frame #4: 0x0000564abaa155f7 gamescope`void* std::__1::__thread_proxy[abi:v160006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct>>, void (*)()>>(__vp=0x00007fb23f911e90) at thread:293:5
    frame #5: 0x00007fb2406b266b ld-musl-x86_64.so.1`start(p=0x00007fb2305f6130) at pthread_create.c:208:17
    frame #6: 0x00007fb2406b5383 ld-musl-x86_64.so.1`__clone + 47
(lldb) quit
```

This corresponds to `g_device.vk.WaitForPresentKHR( g_device.device(), g_output.swapChain, present_wait_id, 1'000'000'000lu );` and https://github.com/ValveSoftware/gamescope/commit/1bb7ef50ba6b44811ea7349df4365fec41652aee.

Forcing `SDL_VIDEODRIVER=x11` makes it not crash, after noticing that it now defaults to wayland. Forcing `SDL_VIDEODRIVER=wayland` on 3.12.5 however still does not crash.

Environment is Chimera Linux, GNOME 45, Mesa 23.1.9, built with Clang 16. Hardware is Intel i7-1165G7 with Iris Xe graphics (and thus iris/anv drivers). Update PR is here https://github.com/chimera-linux/cports/pull/765, I have some new patches but they probably shouldn't be relevant to this.

I'm going to test before-and-after with and without the revision blame pointed me to later. I'm also going to test a different host wayland compositor to see what happens.

**Comment by Joshua-Ashton** [comment]
I believe this is simply a mesa version issue? Either that or for some reason the driver side isn't pickup up presentation time.

**Comment by q66** [comment]
it could be, i'm going to do mesa 23.2 soon, so we'll see then

**Comment by q66** [comment]
I can confirm that things work after updating to mesa 23.2.1
