### ISSUE TITLE
Error when launching game via gameschope with HDR enabled

### ISSUE THREAD

**Issue by S1ngl3-x** [ValveSoftware/gamescope#997]
### Description:
I encountered an error while trying to launch a game on ChimeraOS using Proton. The error seems to be related to enabled HDR in SteamDeckUI session. **I have no issues when launching game through Gnome session or when HDR is disabled.**
I reported this for "Uncharted Legacy of Thieves Collection" but the error also occurs for other games like Jedi Survivor. 

### Environment:

    Steam client update channel: Steam Deck Stable
    Steam stable version: 1696080661
    OS: ChimeraOS
    Kernel: 6.5.6-chos1-chimeraos-1
    Mesa: 23.1.9.chos1-1
    GPU: AMD RX 7900 XT
    CPU: AMD 5700 X
    RAM: 32 GB

### Steps to reproduce:

    Enable HDR in SteamDeck stable branch.
    [Display picks up HDR]
    Install [Name of the Game] through Steam.
    Launch the game using Proton.
    The error mentioned below appears.

### Expected behavior:
The game should launch without errors and be playable.

### Actual behavior:
Received an error related to Vulkan and Wine. The error details are:

`
Assertion Failed!
Program: Z:\home\gamer\.local\share\Steam\steamapps\common\Uncharted Legacy of Thieves Collection\u4.exe
File: ...src-wine\dlls\winevulkan\loader_thunks.c
Line: 5932
Expression: "!status && "vkWaitForPresentKHR""
`

Additional notes:
    I have ensured that my system is updated, including graphics drivers.
    I have tried different versions of Proton with no success.

**Comment by Joshua-Ashton** [comment]
Steam Deck stable has no support for HDR and doesn't have a new enough Mesa for it to work.

It should not be exposed there.

**Comment by Joshua-Ashton** [comment]
Oh this is ChimeraOS. Yeah probably not a new enough Mesa. Not our bug.
